### ISSUE TITLE
Patch Based version of VoxelMorph

### ISSUE THREAD

**Issue by nazib** [voxelmorph/voxelmorph#101]
Hi @adalca
I created a patch-based version of your model. Therefore, we feed randomly selected small patches of size 64x64x64 into the voxelmorph network and train it same as before. During test, we collect patches with 50% overlap and feed them to a trained model. The model gives a flow field which is than applied to the moving image patch. After coillecting all te patches we combine them with sigmoid like weighting function. In this way we get a full resolution image registered. But the problem is the flow field generated from the patches are not smooth and there is always some boundary effect due to discountinous flow in the full resolution image. Did you ever tried your method in patch based registration? If so how do you mange to get patch by patch smooth (continous) flow field.
Kind Regards
Nazib

**Comment by adalca** [comment]
Hi @nazib 

Please see #69 which talks about this. I in particular encourage you *not* to use patches, but if you do, you could penalize the center only (not the full field) and at inference time use a full-volume model. Please see that question for more details.

**Comment by nazib** [comment]
Hi @adalca,
                   excellent. I found what i need.
Kind regards
