### ISSUE TITLE
ValueError: setting an array element with a sequence. 

### ISSUE THREAD

**Issue by zoujinger** [voxelmorph/voxelmorph#102]
Dear author,

I train the model for lung CT images.
When I test the result, there is an error. It seems that the error comes from nibabel.
Or maybe something wrong with tensorflow settings.
It has bothered me for two days. Would you please give me some suggestions?
Thanks so much.
![image](https://user-images.githubusercontent.com/27009979/65043542-a72ef780-d98d-11e9-921b-f7daaa8ab5e5.png)

![image](https://user-images.githubusercontent.com/27009979/65043549-ac8c4200-d98d-11e9-8327-58440f279e2f.png)

Best Regards,
Jing

**Comment by zoujinger** [comment]
Sorry, here attached the code.
![image](https://user-images.githubusercontent.com/27009979/65043642-e2312b00-d98d-11e9-8212-abf71a4bb1a0.png)

**Comment by adalca** [comment]
is your goal to register or to test (i.e. register *and* measure Dice via registration ?

have you tried running register.py?

if you ran test.py, can you tell us what command you ran?

**Comment by zoujinger** [comment]
Thanks. 
I was runing test.py
python src/test.py model/500.h5 0

**Comment by adalca** [comment]
is your goal to register? you should use `register.py` then.

I think your nibabel error is that you're trying to pass the whole header to Nifti1Image, whereas it only requires the affine matrix. Try `moving.affine` -- see the bottom lines of https://github.com/voxelmorph/voxelmorph/blob/master/src/register.py
