### ISSUE TITLE
ValueError: A `Concatenate` layer requires inputs with matching shapes except for the concat axis. Got inputs shapes: [(None, 64, 64, 82, 32), (None, 64, 64, 81, 32)]

### ISSUE THREAD

**Issue by ShibaPrasad** [voxelmorph/voxelmorph#106]
IN addition to my (#104) and (#105) issue:
I changes the size (512 by 512 by 512) - to - <input file> and <mask file> - both. I verified the image size as (512 by 512 by 512) in simpleITK.

I put both the files in - test_examples.txt (as below):
Desktop/Sample-Reg/H-_V2_I_resampled.nii, /Desktop/Sample-Reg/H _V2_INSP_mask__resampled.nii

But, I am still getting the same error:

2019-10-01 13:16:34.575620: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
WARNING:tensorflow:From /user/iibi/skuanar/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
Traceback (most recent call last):
  File "/user/iibi/skuanar/Downloads/voxelmorph/src/test_miccai2018.py", line 109, in <module>
    test(sys.argv[1], sys.argv[2], sys.argv[3])
  File "/user/iibi/skuanar/Downloads/voxelmorph/src/test_miccai2018.py", line 63, in test
    net = networks.miccai2018_net(vol_size, nf_enc, nf_dec, use_miccai_int=False, indexing='ij')  
  File "/nfs/s-iibi54/users/skuanar/Downloads/voxelmorph/src/networks.py", line 146, in miccai2018_net
    unet_model = unet_core(vol_size, enc_nf, dec_nf, full_size=False)
  File "/nfs/s-iibi54/users/skuanar/Downloads/voxelmorph/src/networks.py", line 65, in unet_core
    x = concatenate([x, x_enc[-2]])
  File "/user/iibi/skuanar/anaconda3/lib/python3.7/site-packages/keras/layers/merge.py", line 649, in concatenate
    return Concatenate(axis=axis, **kwargs)(inputs)
  File "/user/iibi/skuanar/anaconda3/lib/python3.7/site-packages/keras/engine/base_layer.py", line 463, in __call__
    self.build(unpack_singleton(input_shapes))
  File "/user/iibi/skuanar/anaconda3/lib/python3.7/site-packages/keras/layers/merge.py", line 362, in build
    'Got inputs shapes: %s' % (input_shape))
ValueError: A `Concatenate` layer requires inputs with matching shapes except for the concat axis. Got inputs shapes: [(None, 64, 64, 82, 32), (None, 64, 64, 81, 32)]

Process finished with exit code 1

_**About the Shape Verification:**_
Image size: (512, 512, 647)
Image origin: (0.0, 0.0, 0.0)
Image direction: (1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0)
Image PixelID: 1
Image voxel spacing: (1.0, 1.0, 1.0)
[512, 512, 512]
Resampling Image
Resampled
Resampled size: (512, 512, 512)
Resampled voxel spacing: (1.0, 1.0, 1.0)
Resampled origin: (0.0, 0.0, 0.0)
Writing Resampled Image
Done

_**testMiccai2018 FILE:**_

# Test file and anatomical labels we want to evaluate
test_brain_file = open('/nfs/s-iibi54/users/skuanar/Downloads/voxelmorph/test_examples.txt')

test_brain_strings = test_brain_file.readlines()
test_brain_strings = [x.strip() for x in test_brain_strings]
n_batches = len(test_brain_strings)
good_labels = sio.loadmat('../data/labels.mat')['labels'][0]

# atlas files
atlas = np.load('../data/atlas_norm.npz')
**#atlas = np.load('../data/_V2_I_resampled.npz')  (MY INPUT COMMENTED OUR)**
atlas_vol = atlas['vol'][np.newaxis, ..., np.newaxis]
atlas_seg = atlas['seg']

def test(gpu_id, model_dir, iter_num,
         compute_type = 'GPU',  # GPU or CPU
         **_vol_size=(512, 512, 647),_**
         nf_enc=[16, 32, 32, 32],
         nf_dec=[32, 32, 32, 32, 16, 3],
         save_file=None):
    """
    test via segmetnation propagation
    works by iterating over some iamge files, registering them to atlas,
    propagating the warps, then computing Dice with atlas segmentations
    """

**Comment by adalca** [comment]
Hi @ShibaPrasad 

Can you please continue the questions on the issues you're already started? It helps us keep organized. Also, note that even if an issue is closed, you can keep postein on it, or re-open it if you need to

I am a bti confused. Aren't you saying at the very end that the vol_size is the wrong size? it's 647 in the third dimension, and it should be 512, no?

if you print `vol_size` right before line 63 in the python, what does it print?

**Comment by ShibaPrasad** [comment]
I printed the volume size it's was showing (512, 512, 647). 
But I changed at testMiccai2018:
def test(gpu_id, model_dir, iter_num,
         compute_type = 'GPU',  # GPU or CPU
         vol_size=(512, 512, 512),
         nf_enc=[16, 32, 32, 32],
         nf_dec=[32, 32, 32, 32, 16, 3],
         save_file=None):
**_after that is got below error:_**
Traceback (most recent call last):
  File "/user/iibi/skuanar/Downloads/voxelmorph/src/test_miccai2018.py", line 111, in <module>
    test(sys.argv[1], sys.argv[2], sys.argv[3])
  File "/user/iibi/skuanar/Downloads/voxelmorph/src/test_miccai2018.py", line 89, in test
    pred = diff_net.predict([X_vol, atlas_vol])
  File "/user/iibi/skuanar/anaconda3/lib/python3.7/site-packages/keras/engine/training.py", line 1441, in predict
    x, _, _ = self._standardize_user_data(x)
  File "/user/iibi/skuanar/anaconda3/lib/python3.7/site-packages/keras/engine/training.py", line 579, in _standardize_user_data
    exception_prefix='input')
  File "/user/iibi/skuanar/anaconda3/lib/python3.7/site-packages/keras/engine/training_utils.py", line 145, in standardize_input_data
    str(data_shape))
ValueError: Error when checking input: expected input_1 to have shape (512, 512, 512, 1) but got array with shape (512, 512, 647, [1)]

**_Note:_**
- _**I am giving CT.nii and CT.mask.nii file at -> test_examples.txt**_
-  I am still using **_/data/atlas_norm.npz_**
   # atlas files
_atlas = np.load('../data/atlas_norm.npz')_
#atlas = np.load('../data/H-18151_V2_I_resampled.npz')
atlas_vol = atlas['vol'][np.newaxis, ..., np.newaxis]
atlas_seg = atlas['seg']



![1_test](https://user-images.githubusercontent.com/12077129/65996471-12cc9680-e45d-11e9-915d-1b8ba3922933.png)

**Comment by adalca** [comment]
the error is saying that one of the volumes `X_vol, atlas_vol` has the wrong size.
Print their sizes just before `predict` and you will find out which one is the wrong size. This volume will need to be the right size (512x512x512) to work with this network.

For example, `print(X_vol.shape)`

**Comment by ShibaPrasad** [comment]
print(X_vol.shape) - giving (1, 512, 512, 647, 1)
and print(atlas_vol.shape) - giving - (1, 160, 192, 224, 1)

i am not sure which i am getting X_vol.shape as -  (1, 512, 512, 647, 1) though I have changed the size to (512, 512,512)

I have used atlas_norm.npz. Is that the reason i am getting - (1, 160, 192, 224, 1)

**Comment by adalca** [comment]
yes, that's why you're getting the size for the atlas.
The size of the X_vol, as I mentioned, you need to resize it to match the dimensions, and it seems like that did not work for you. Sorry, but this needs to be done separately from voxelmorph.

I would recommend trying to register your volume to the atlas affinely with some other tool, like ANTs affine, which should get you a new volume of size 160x192x224.

**Comment by ShibaPrasad** [comment]
Thank You !!!
