### ISSUE TITLE
Using the antsTransforms command of ANTs to get the wraped image is different from the image obtained using register.py

### ISSUE THREAD

**Issue by white-hy** [voxelmorph/voxelmorph#107]
Hi,Dear Author,Thanks for your wonderful work and code!I am using ANTs and Voxelmorph to complete the image registration of the lung image, then I get a question.

I used `registrater.py` to complete the registration of a pair of images `(Moving.nii.gz/Fixed.nii.gz)`, and then got the wraped image and deformation field, respectively `wraped.nii.gz` and `wrap.nii.gz`.
Then I use the ANTs command to apply the transformation field obtained by `register.py` to complete the transformation. I use ANTs to execute the following command: 
```
antsApplyTransforms \
-d 3 \
-i moving.nii.gz \
-o ANTs_warped.nii.gz \
-r Fixed.nii.gz \
-t wrap.nii.gz
```
I noticed that `wraped.nii.gz` and `ANTs_wraped.nii.gz` are different..`ANTs_wraped.nii.gz` just has a very small  change compared to `Moving.nii.gz`.
Why is `wraped.nii.gz` different from `ANTs_wrap.nii.gz`? Can you give me some tips?

**Comment by adalca** [comment]
hi @white-hy 

In short, ANT's transform standard is different than ours (and we weren't able to figure theirs out after a while). To warp images with a warp coming from ANTs, you should definitely use their tools. To actually warp the images with our warp, we recommend you use either the warped image given by register.py, or use a simple transform network, e.g.:

```
    ndims = len(vol_size)
    subj_input = Input((*vol_size, 1), name='subj_input')
    trf_input = Input((*vol_size, ndims) , name='trf_input')
    nn_output = nrn_layers.SpatialTransformer(interp_method='linear', indexing=indexing)
    nn_spatial_output = nn_output([subj_input, trf_input])
    warp_model = keras.models.Model([subj_input, trf_input], nn_spatial_output)
```

then use `warp_model.predict([moving_image, warp_from_vxm])`.

We are working on a `warp.py` file for this in the new release, and an easily accessible network!

**Comment by white-hy** [comment]
@adalca Thank you very much for your reply!
