### ISSUE TITLE
How to input paired data to train?

### ISSUE THREAD

**Issue by ggCCdeepo** [voxelmorph/voxelmorph#108]
Dear @adalca , 

I noticed that there is only one input path of the training dataset, and the name of data are not required. So I ask for help. 

-  For the subjust to subjust method, what is the rule of input sequence of training image? How to pair the series of data?

-   If I want to train paired data, how should I import it?

Thanks!

**Comment by adalca** [comment]
Hi @JCFu 

Sorry we missed this, did you end up getting this solved? To get paired data working, you would have to change the datagenerators yourself -- it wouldn't be a big deal, and you could do it in a variety of ways (e.g. one folder per subject). Did you manage to do one of these?
