### ISSUE TITLE
implementation in pytorch

### ISSUE THREAD

**Issue by zoujinger** [voxelmorph/voxelmorph#109]
Hi, author,
Is the pytorch version available?
I'm looking forward to that as the tensorflow is a bit difficult.
Thanks so much!

**Comment by farhanone** [comment]
Hi @zoujinger, there is implementation [PyTorch-Voxelmorph](https://github.com/Hsankesara/VoxelMorph-PyTorch). It already has some bugs.

**Comment by adalca** [comment]
@zoujinger @farhanone apologies for the delay, we've all been busy with MICCAI. We'll have an update on this next week. Thanks

**Comment by riccardosamperna** [comment]
Hi @adalca,
do you have any update about the Pytorch version?

**Comment by adalca** [comment]
@riccardosamperna yes, we have a version, and are actively testing it! Hopefully just a few more days.

**Comment by riccardosamperna** [comment]
Thank you for your reply. Looking forward to see the Pytorch version :)

**Comment by Rimay** [comment]
Looking forward to the Pytorch version!

**Comment by HP192080042** [comment]
Hi, author, do you have any update about the Pytorch version? Looking forward to the Pytorch version!

**Comment by HP192080042** [comment]
@adalca

**Comment by jacobdang** [comment]
Looking forward to the Pytorch version!@adalca

**Comment by pipehappy1** [comment]
Yeah, look forward to the pytorch version

**Comment by adalca** [comment]
We've uploaded a preliminary version for pytorch in the `pytorch` folder. Please note that this isn't as well developed or tested as the main tf/keras version, but should provide you with a nice place to start. 

@zoujinger @farhanone @jacobdang @pipehappy1 @riccardosamperna @Rimay @HP192080042 

Thanks to @balakg @VictorButoi for helping to get this version together quickly.
