### ISSUE TITLE
code for calculating |J| and number of folding voxels

### ISSUE THREAD

**Issue by regproj** [voxelmorph/voxelmorph#110]
My original post was kinda dumb sorry.  Going to change my question and ask if there was a way of calculating the jacobian determinant using ANTs command line given a warp field with dimensions [x,y,z,3] in a nifti format

**Comment by regproj** [comment]
Also have noticed that if you compute the stationary velocity field by sampling from a zero mean gaussian (as done in the miccai 2018 version) you get a displacement field  that is extremely noisy. Is there a way to reduce the noise? It seems like the KL loss should account for smoothness, and while it does smooth the mean velocity, the std deviation remains quite large.

**Comment by adalca** [comment]
Hi @regproj 
Sorry somehow we missed this message from last year. If you're still working on this, https://sourceforge.net/p/advants/discussion/840261/thread/9a6e6241/ should help you
