### ISSUE TITLE
The dice of metrics.The decimal and integer.

### ISSUE THREAD

**Issue by mamamadoge** [voxelmorph/voxelmorph#111]
In test.py, the dice is calculated.
`warp_seg = nn_trf_model.predict([X_seg, pred[1]])[0,...,0]`
`vals, _ = dice(warp_seg, atlas_seg, labels=labels, nargout=2)`

But, in metrics:
```
    dicem = np.zeros(len(labels))
    for idx, lab in enumerate(labels):
        vol1l = vol1 == lab
        vol2l = vol2 == lab
```
It seem that you only save ingeter volume of predicted volume, all the decimal volume are deleted.
However the mask predicted by STN will lead to decimal figure like 0.9？ 
So， is that normal for predicted volume?
Maybe it is also acceptable for dice score to calculate with decimal?

**Comment by adalca** [comment]
Hmm, `nn_trf_model` should be using a nearest-neighbor version of the spatial transformer layer, and should this not be giving any decimals if the input has no decimals (it should be a segmentation)

**Comment by mamamadoge** [comment]
Do you mean that the interp_method is nearest, not linear?
`def transform(vol, loc_shift, interp_method='linear', indexing='ij'):`
`def transform(vol, loc_shift, interp_method='nearest', indexing='ij'):`

**Comment by adalca** [comment]
yes, see `nn_trf` definition in https://github.com/voxelmorph/voxelmorph/blob/master/src/networks.py#L204

**Comment by mamamadoge** [comment]
I really appreciate your reply.
