### ISSUE TITLE
ants Syn registration runtime. 

### ISSUE THREAD

**Issue by liangyuandg** [voxelmorph/voxelmorph#115]
I tried to test the Ants Syn registration with brain images of similar dimension as mentioned in voxelmorph paper. I utilized similar parameters for Syn (including iteration times for each resolution and step size), however it only takes me ~20s for one pair of images, which was claimed to be ~9000s in the paper. 

I know the registration time can be heavily depadent on the parameter setup. Can I know what is the exact commend line for Ants Syn that you use to get the runtime stat in the table. Thanks!

**Comment by adalca** [comment]
Hi @liangyuandg , we've run several baselines in various tasks and experiments, but here's an example run (one a CPU): 

`/path/to/ANTS 3 -m CC[/path/to/atlas.nii.gz,/path/to/subject.nii.gz,1,4] -t Syn[0.25] -o /path/to/output_prefix --number-of-affine-iterations 0x0 -i 201x201x201 -r Gauss[9,0.2]`
