### ISSUE TITLE
Warp_Field

### ISSUE THREAD

**Issue by hfahad** [voxelmorph/voxelmorph#116]
Dear @adalca 
Is it possible to give me a code for showing the warp field grid that shows the deformation . can see in the attachment

Thanks in advance
Hafiz

![warp_field](https://user-images.githubusercontent.com/25321106/67947319-b2f41780-fbe3-11e9-8ccf-07134fe5527d.png)

**Comment by adalca** [comment]
Sure, we create a black and white grid via `bw_grid()` in [pynd](https://github.com/adalca/pytools-lib/blob/master/pynd/ndutils.py) to create an image the size of the input volume, and then use `model.predict()` on the resulting image, and show a slide from that. Does that make sense?

**Comment by white-hy** [comment]
@adalca Hi. Dear Author.

> and show a slide from that. Does that make sense?

I'm a little confused about what you said about ` slide` . Dose this  ` slide` is a slice?
I used Voxelmorph to complete the registration of the lung images. The Jacobian determinants of the resulting displacement field are all positve, which means I achieve a smooth displacemen field, right? However, I use the resulting displacement field to transform the grid image. Visually, the grid image is discontinuous. My results are shown as follows:
![image](https://user-images.githubusercontent.com/33248778/70597430-44af6580-1c23-11ea-896d-a1855a76b761.png)
![image](https://user-images.githubusercontent.com/33248778/70597831-534a4c80-1c24-11ea-91ee-b8e424a098ef.png)![image](https://user-images.githubusercontent.com/33248778/70597800-3e6db900-1c24-11ea-95bd-183de106eb22.png)
![image](https://user-images.githubusercontent.com/33248778/70598637-40387c00-1c26-11ea-892a-8849fb8cbfc1.png)![image](https://user-images.githubusercontent.com/33248778/70598725-6cec9380-1c26-11ea-8fb3-1af8ee3560dd.png)





Here is my code:
```
    with tf.device(gpu):
        pred = nib.load('./displacement_field.nii.gz').get_data()[np.newaxis, ...]  
        Warp_img = nn_trf_model.predict([Grid_image, pred])[0, ..., 0]
        Warp_img = Warp_img.transpose(2, 1, 0)
        Warp_img = sitk.GetImageFromArray(Warp_img)
        Warp_img.SetSpacing(img_spacing)
        sitk.WriteImage(Warp_img,'')
```
I don't know why the grid is discontinuous.Can you give me some hints.

**Comment by adalca** [comment]
positive Jacobian det simply means no foldings (good!) 

Mostly because you used nearest neighbour interpolation. Try building a model that warps without that uses linear interpolation (like `nn_trf` but `linear` instead of `nearest`). I think the results will look better.

Having said this, looking at your images it seems like the field isn't super regular, you might find it useful to increaes the regularity *just a bit*.

**Comment by white-hy** [comment]
@adalca  Thank you so much for your advice.  I'll do what you said right away.

I'm a little confused about this:
>  looking at your images it seems like the field isn't super regular

I adjusted the window width when I showed the three images of the displacement field. Here is the image before I adjusted the window level.
![image](https://user-images.githubusercontent.com/33248778/70676434-1c794280-1cc7-11ea-9759-c56f7b003502.png)![image](https://user-images.githubusercontent.com/33248778/70676462-3450c680-1cc7-11ea-954c-5bdd4b87c3ce.png)
![image](https://user-images.githubusercontent.com/33248778/70676504-55191c00-1cc7-11ea-9c26-bf7e390c5d17.png)![image](https://user-images.githubusercontent.com/33248778/70676767-323b3780-1cc8-11ea-8321-b5c05dfbf95d.png)
How can I get the conclusion that it is necessary to add regularization by observing the images of displacement field? Can you give me some hints.
