### ISSUE TITLE
How to use the voxelmorph to registration the CT and MRI image

### ISSUE THREAD

**Issue by YMBrianHung** [voxelmorph/voxelmorph#117]
Hi, author
The number of my CT data's slice is 103, and the number of the MR data's slice is 60, which both can't divide by the 32(the downsample stride of U-Net), how can I adjust the slice number to be able to input the U-Net(be the times of 32)

**Comment by adalca** [comment]
Hi @YMBrianHung 

Can you provide more information

(1) what are you trying to register -- MR to CT? Are they paired (same subjects)?
(2) If you have only 60 MR slices, it sounds a bit like your data is either thick slices or widely separated or both. I would recommend you first re-sample your data to be 1mm^3, and then affinely register it, then use voxelmorph. If your data is not a multiple of 16 by that point, you can use some padding in both domains.

**Comment by YMBrianHung** [comment]
Thank you for your reply.
Can you tell me how to resample my data to be 1mm^3?
Some information of my CT data:
spacing = [[0.9765625, 0.9765625, 3.0]
size = [512, 512, 103]

I used to use the SimpleITK(Python)  to extend the slice number from 103 to 128 as fellow:   

resampler = sitk.ResampleImageFilter()
resampler.SetInterpolator(sitk.sitkLinear)
resampler.SetDefaultPixelValue( 0 );

resampler.SetOutputDirection(img.GetDirection())
resampler.SetOutputOrigin(img.GetOrigin())
size = [512,512,128]
resampler.SetSize(size)
new_spacing = [0.9765625, 0.9765625, 1.5]
resampler.SetOutputSpacing(new_spacing)
newimage = resampler.Execute(img)

But the result of the new image is terrible, which the 104~128 slices are blank. And when I expose the nii image to the 3D Slicer, the sagittal image and the Coronal image become flat.
Is my code of SimpleITK for resample is error?
I note that in your paper, you say you first resample your data to be [256,256,256], what's your method to resample the data?

**Comment by adalca** [comment]
I'm sorry, I'm not familiar with ITK's re-samplers. I would simply use interpolation methods -- for example, [interpn](https://docs.scipy.org/doc/scipy-0.18.1/reference/generated/scipy.interpolate.interpn.html) in scipy -- but of course, there might be tools out there, I'm just not familiar with them. You could try asking on ITK's forums (https://discourse.itk.org/t/welcome-to-the-itk-discussion-forum/8)

Alternatively, you could use a linear registration method (like ANTs) first, which will re-sample your data in the space of your destination (e.g. if you use the atlas we provide).
