### ISSUE TITLE
A `Concatenate` layer requires inputs with matching shapes except for the concat axis. Got inputs shapes: [(None, 64, 64, 14, 32), (None, 64, 64, 13, 32)]

### ISSUE THREAD

**Issue by YMBrianHung** [voxelmorph/voxelmorph#118]
Hi, author
Can you tell me how to resample my data to be 1mm^3?
Some information of my CT data:
spacing = [[0.9765625, 0.9765625, 3.0]
size = [512, 512, 103]

I used to use the SimpleITK(Python) to extend the slice number from 103 to 128 as fellow:

resampler = sitk.ResampleImageFilter()
resampler.SetInterpolator(sitk.sitkLinear)
resampler.SetDefaultPixelValue( 0 );

resampler.SetOutputDirection(img.GetDirection())
resampler.SetOutputOrigin(img.GetOrigin())
size = [512,512,128]
resampler.SetSize(size)
new_spacing = [0.9765625, 0.9765625, 1.5]
resampler.SetOutputSpacing(new_spacing)
newimage = resampler.Execute(img)

But the result of the new image is terrible, which the 104~128 slices are blank. And when I expose the nii image to the 3D Slicer, the sagittal image and the Coronal image become flat.
Is my code of SimpleITK for resample is error?
I note that in your paper, you say you first resample your data to be [256,256,256], what's your method to resample the data?

**Comment by adalca** [comment]
Hi @YMBrianHung, let's continue the conversation on #117 where you first asked this question.
