### ISSUE TITLE
numpy

### ISSUE THREAD

**Issue by mxkai** [voxelmorph/voxelmorph#119]
Hello, I try to run your code, but there is a problem:
File "../ext/voxelmorph/src/losses.py", line 17, in binary_dice
    vol_axes = 1 + np.range(ndims)
AttributeError: module 'numpy' has no attribute 'range'
Can you tell me which version of numpy is used for this project，thanks

**Comment by adalca** [comment]
This actually seems to be a bug in our part. My apologies I'm not sure when it was introduced.
can you change `vol_axes = 1 + np.range(ndims)` to `vol_axes = list(range(1, ndims+1))` ?

**Comment by mxkai** [comment]
Thanks for your suggestion，I will try it
