### ISSUE TITLE
How to get the dataset?

### ISSUE THREAD

**Issue by ahuczp** [voxelmorph/voxelmorph#12]
Hi, I want to run your code ,so where can I download the dataset?Thankn you!

**Comment by adalca** [comment]
Hello. Thanks for your interest in VoxelMorph!
We used publicly available datasets, but unfortunately we can't redistribute them (e.g. ADNI, OASIS, ABIDE, etc), so you'd have to get those yourself. We give an example subject in the data folder as a simple testing demo.
