### ISSUE TITLE
Difference between 'ij' and 'xy' indexing

### ISSUE THREAD

**Issue by hassaanmahmood** [voxelmorph/voxelmorph#120]
Can you please mention use cases of both type. I could not grasp the concept here.

Thanks

**Comment by adalca** [comment]
Please see the detailed documentation at [meshgrid](https://docs.scipy.org/doc/numpy/reference/generated/numpy.meshgrid.html) in the Notes section.

My recommendation is to use `ij` indexing as much as possible. This is just the normal matrix indexing. `xy` indexing essentially switches the first two indexes -- which is useful in some computer vision applications, but here where we want to be dimension independent (work similarly for 2d and 3d) I think `ij` makes more sense.
