### ISSUE TITLE
Atlas construction and label transform

### ISSUE THREAD

**Issue by theoVag** [voxelmorph/voxelmorph#121]
Hello,
I am studying your article about deformable medical image registration and I have a question about the construction of atlas. Could you give me some reference (article or part of voxelmorph code) or the pipeline about the unconditional template construction? Also could you explain a bit the part of (s_m o φ) derivation (by spatial transforming each channel of s_m using linear interpolation) or spot it in the code?
Thanks in advance

**Comment by adalca** [comment]
Assuming you are reading the [NeurIPS paper](https://arxiv.org/abs/1908.02738), the unconditional atlas is figure 2 without the decoder. Instead, we essentialy learn a parameter at each voxel: the intensity of the image (Section 3.1, end of second para). In the code, the file is [train_img_template.py](https://github.com/voxelmorph/voxelmorph/blob/master/src/train_img_template.py) which uses the 
`img_atlas_diff_model()` network construction.

I'm not sure about the context of the segmentation question -- which paper are you reading? But Imagine having a segmentation map `HxWxD`, then having the one-hot representation of is `HxWxDxL` where `L` is the number of labels. You can apply a `SpatialTransformer()` layer to such a Tensor, and it will warp all the labels according to the transform.

**Comment by theoVag** [comment]
Hello and thank you for the fast reply I am studying both the Learning Conditional Deformable Templates with Convolutional Networks and VoxelMorph: A Learning Framework for Deformable Medical Image Registration. The segmentation question is related to the second one. More specific the part of the article that I didn't understand very well says 
![image](https://user-images.githubusercontent.com/32677031/68527762-58e60700-02f3-11ea-9f29-dc1f5e374260.png) . To clarify, the one hot encoding is used so it can be transformed in the network? In addition, this kind of encoding should be applied in atlas construction (in the label image) ?

**Comment by adalca** [comment]
The one hot encoding is used to warp the labels. Without a one-hot encoding you would have to use something a nearest-neighbor interpolation when warping, which does not have derivatives.

We didn't talk about segmentations in the atlas paper -- if you want to build a segmentation template, then yes you could do it this way!

**Comment by theoVag** [comment]
Thank you very much for your help! Keep up with the good work!
