### ISSUE TITLE
Registering images - Loss

### ISSUE THREAD

**Issue by theoVag** [voxelmorph/voxelmorph#123]
Hello,
I ran the train.py on my dataset with cvpr model and I got a model file after 1000epochs. Then I tried test.py but  couldn't get the transformed image on my test. I also tried register.py because I would like to see the result image (I got a flow vector from test.py) but register.py throw the error below:
ValueError: Unknown loss function:loss . How can I get the registered image from my trained model?

**Comment by hfahad** [comment]
Hello @theoVag 
I also faced the same problem in MICCAI code in the beginning but after that, I tried this way and its work you can also try in the CVPR version.

net = networks.miccai2018_net(vol_size, nf_enc, nf_dec, use_miccai_int=False, indexing='ij')
net.load_weights('weights.h5')
[moved_image, warp_field] = net.predict([moving,fixed])

or 

import networks
diff_net = keras.models.Model(net.inputs, net.get_layer('diffflow').output)
pred_field = diff_net.predict([moving,fixed])
nn_trf_model = networks.nn_trf(vol_size, indexing='ij')
warp_img = nn_trf_model.predict([moving_img, pred_field])
