### ISSUE TITLE
full_size option for MICCAI code 

### ISSUE THREAD

**Issue by hfahad** [voxelmorph/voxelmorph#124]
Dear @adalca,
I have some questions related to MICCAI 2018 Paper

1) Can you please tell me about why we use 1/2 size flow field as compare to full size?
2) what is the scaling and squaring layer doing in the field (i know the main purpose is  
    Diffeomorphism). but what 'ss' is doing in the field I thought in the beginning. integration layer will 
    resize from 1/2 to full size. but after 'ss' layer the field size still the same.

Thankx in advance
Hafiz Fahad

**Comment by riccardosamperna** [comment]
1. The answer is here: https://github.com/voxelmorph/voxelmorph/issues/122#issuecomment-552446676.
2. Scaling and squaring is a numerical integration method, it is not used to up-sample the velocity field.

Hope it helps also if I am not the author.
