### ISSUE TITLE
where is "vol_data"

### ISSUE THREAD

**Issue by chenyuhaosuai** [voxelmorph/voxelmorph#126]
dear author
when I try train with your data(atlas_norm.npz), but i dont find the "vol_data". can you tell me where is the vol_data and what it means

**Comment by adalca** [comment]
@chenyuhaosuai I see you opened up and closed #125. Have you found what you were looking for?

`vol_data` is the name of the volume variable in our npz files. You should change this to whatever type of files you have -- see `load_volfile()` in https://github.com/voxelmorph/voxelmorph/blob/master/src/datagenerators.py

**Comment by chenyuhaosuai** [comment]
thanks, I find the data in the atlas_norm.npz is named 'vol' not 'vol_data', I can train the model sucessfully. Beacuse it is my frist time to do  experiment of Image Registration, can you tell me more information about the experiment? If you do , I will be very grateful。

**Comment by adalca** [comment]
You can find a `vol_data` variable in `test_vol.npz` for example.

But again, if you are able to train your model with your own files, I wouldn't worry about `vol_data` anymore!

I'm not sure I understand what you mean about more details about the experiments, but I recommend you work through this tutorial: https://www.kaggle.com/adalca/learn2reg

**Comment by chenyuhaosuai** [comment]
Firstly ,thank you very much for writing back to me.
Secondly ,i want to know which files in the data file directory are training and those are testing, because I want to use your data for experiments. 
Isn't this file（atlas_norm.npz ) for training?

**Comment by chenyuhaosuai** [comment]
Your data refers to the data you provide in the project
