### ISSUE TITLE
A bug about bw_grid() in pynd

### ISSUE THREAD

**Issue by white-hy** [voxelmorph/voxelmorph#131]
Hi! Dear author! Great works!
I tried to creat a create a black and white grid using `bw_grid()` in [pynd](https://github.com/adalca/pytools-lib/blob/master/pynd/ndutils.py), but I got a image where the pixel values are all 1. The code I used is shown as fllows:
```
if __name__ == "__main__":
    spacing_img = [1, 1, 1]
    size_img = [256, 256, 256]
    grid_data = bw_grid(size_img, spacing_img)
    grid_img = sitk.GetImageFromArray(grid_data)
    grid_img.SetSpacing(spacing_img)
    sitk.WriteImage(grid_img, './data/zhy/grid/grid.nii.gz')
```

**Comment by adalca** [comment]
@white-hy can you try a spacing larger than 1? The way I coded `bw_grid`, spacing of 1 is essentially no spacing, akin to 'stride'  (sorry, this should probably be better documented)

**Comment by white-hy** [comment]
@adalca I'm sorry for my late reply.  I tried what you said, and I got the correct grid image. Thank you so much!
