### ISSUE TITLE
Brain MRI 2D

### ISSUE THREAD

**Issue by HP192080042** [voxelmorph/voxelmorph#132]
hello I use the Brain MRI 2D dataset    
this is my  Training process
![image](https://user-images.githubusercontent.com/53810832/70120008-7c0f9680-16a6-11ea-9605-a606bf275b79.png)
this is result 
![image](https://user-images.githubusercontent.com/53810832/70120608-f7257c80-16a7-11ea-8d16-bcacdcad82ee.png)

I don't understand why the score（dice） is so low？ Can you answer it for me？ thank you！

this is my dice code 
![image](https://user-images.githubusercontent.com/53810832/70120364-60f15680-16a7-11ea-8c73-be54dc6baddd.png)

@adalca

**Comment by adalca** [comment]
I am a bit confused, what are you applying Dice to? Do you have segmentations?

Those results look good to me in the visualization.
