### ISSUE TITLE
Scaling and squaring for miccai 2018 version

### ISSUE THREAD

**Issue by AnkitaJo** [voxelmorph/voxelmorph#133]
Please can you explain the intuition behind - why are the velocities added in the squaring step instead of repeatedly squaring them. Specifically the below lines of code:

https://github.com/voxelmorph/voxelmorph/blob/1b3fc4625135db74d4c64f1445adcf786157ad25/ext/neuron/neuron/utils.py#L359

**Comment by adalca** [comment]
Sure, the field in this case is a 'displacement' field, which is what is causing the problems.

This one line is meant to do a composition. That is, if point A goes to point B, and point B goes to point C, then the answer should go from A to C. 

A single call to `transform` will move the 'B->C' vector into the A location.  So this doesn't give you A->C quite yet. The missing vector is A->B. So we need to add this -- but this is the original field! So vec + `transform()` does the job.
