### ISSUE TITLE
Supervised edition

### ISSUE THREAD

**Issue by theoVag** [voxelmorph/voxelmorph#136]
Hello, I move the issue here for a more clear page. Is it possible to upload the train_supervised.py or some code about supervised loss(dice) and how to use it with the network? I am working in Osteoarthritis Initiative and I would like to use segmentation masks to try to get a better result.
Thanks a lot

**Comment by norris9410** [comment]
MARK. Waiting for author's kind response.

**Comment by adalca** [comment]
@theoVag @norris9410 sorry for the delay in this, I'm trying to go through the issues that I missed during December still. We have an example of this script in the new voxelmorph redesign at https://github.com/voxelmorph/voxelmorph/tree/redesign/scripts/tensorflow
