### ISSUE TITLE
how the voxelmorph output a flow with any float values from positive to negative?

### ISSUE THREAD

**Issue by Dongshengjiang** [voxelmorph/voxelmorph#137]
**Task** (what are you trying to do/register?)

[I wander voxelmorph using fully convolutuional network with input image size of [0,1], how to get a flow with any float values (such as -8.5,-1.3,0.6,8.2) from conv filters, espically those  negative deformation field. is the LeakyReLU works for it?]

**What have you tried**

Please describe specifics of your approach // use of `vxm`

**Details of experiments**

Please carefully specify details about your experiments. If you are training, when what is the setup? What loss are you using? What does the convergence look like? If you are registering, please show example inputs and outputs. etc.

**Comment by adalca** [comment]
@Dongshengjiang the last layer in voxelmorph that outputs the deformation or the velocity field does not have an activation, so any value (positive or negative) is possible.

**Comment by Dongshengjiang** [comment]
thanks for your explanation dongshengjiang 邮箱：dongshengjiang@aliyun.com 签名由 网易邮箱大师 定制 On 12/28/2019 10:28, Adrian Dalca wrote: @Dongshengjiang the last layer in voxelmorph that outputs the deformation or the velocity field does not have an activation, so any value (positive or negative) is possible. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.
