### ISSUE TITLE
what is the resizing method

### ISSUE THREAD

**Issue by shuo-shuo-zhang** [voxelmorph/voxelmorph#138]
Dear author,

I really want to know the details of the resizing method which is given in https://github.com/adalca/neuron/blob/master/neuron/layers.py, I don't understand how it works. So I want to know if it is possible for you to explain the resizing process. 

Thank you very much!

**Comment by adalca** [comment]
it does something similar to [`scipy.ndimage.interpolate.zoom`](https://docs.scipy.org/doc/scipy-0.15.1/reference/generated/scipy.ndimage.interpolation.zoom.html) but as a layer in keras -- basically resizes the volume using an interpolation scheme.

**Comment by shuo-shuo-zhang** [comment]
Thank you very much, that's very helpful.
