### ISSUE TITLE
Running inference using provided model weights

### ISSUE THREAD

**Issue by thomshaw92** [voxelmorph/voxelmorph#139]
**Task** (what are you trying to do/register?)

I'm trying to test the unconditional model weights provided to create a 3D brain template with a couple of MRI scans

**What have you tried**

Went through the example https://www.kaggle.com/adalca/learn2reg 
Tried using the script train_img_template.py and editing the options

**Details of experiments**

Getting caught at 
`No module named 'PIL'`
If possible, could you please provide an example of how to use the model weights for template creation?

**Comment by adalca** [comment]
@thomshaw92 were you able to tackle this? the error above is simply telling you to install `pillow`: https://pypi.org/project/Pillow/, although to be honest I find it hard to recall where we used it for the brain template.

**Comment by thomshaw92** [comment]
@adalca No sorry I wasn't. I'll keep playing around with it though. 
Could you please point me in the right direction for the prediction code (not training) for recreating the neuro (unconditional) templates made in the arXiv article?  Thanks for your help!

**Comment by adalca** [comment]
@thomshaw92 to get the atlas you simply have to get the weights of the `atlas` layer! Since we are learning the atlas as network parameters of that layer. so something like `model.get_layer('atlas').get_weights()`
