### ISSUE TITLE
Duplicate of 2#' Data loaded error

### ISSUE THREAD

**Issue by Alison-brie** [voxelmorph/voxelmorph#14]
Hi @rongrongxiangxin, I am still having this issue
Duplicate of 2#'
I used the data provided. When I run train.py, the code X = np.load(vol_names[idx])['vol_data'] in datagenerators.py raise the KeyError: 'vol_data is not a file in the archive'.

**Comment by adalca** [comment]
can you let us know the full command line that you run? and which version of voxelmorph you are running (when did you pull the repository)?

**Comment by meggiezhou** [comment]
hello，sir you said you provided T1 brain atlas,but why the atlas_vol is all zero matrix
