### ISSUE TITLE
How to obtain the deformation field and use it to morph other files?

### ISSUE THREAD

**Issue by neuronflow** [voxelmorph/voxelmorph#140]
**Task** (what are you trying to do/register?)
Hi, I want to segment neuro-anatomic brain regions on patients. I therefore have a segmented atlas. I now want to segment the atlas T1 file to the patient T1 file (so far so good). But:
1) do I obtain the deformation field to morph the segmentation of the atlas file to the patient
2) which method should I use to do the actual morphing?
**What have you tried**
I found this thread but could not solve it with the information in it:
https://github.com/voxelmorph/voxelmorph/issues/90

**Comment by adalca** [comment]
hi @neuronflow , apologies for missing this.

To be clear, are you asking how to warp a T1 image to a T1 atlas (voxelmorph), or how you should do segmentation given an atlas (our MICCAI2019 paper on segmentation)?

**Comment by neuronflow** [comment]
Hi @adalca thanks for looking into this.

I have an atlas which provides me a T1 and T2 and multiple segmentation files.

My main goal is to segment my patients, so to warp these segmentation maps into patient space. Besides of that it would be interesting to warp the atlas T1 and T2 too.

**Comment by adalca** [comment]
@neuronflow are the patient scans T1 as well?

I would first recommend doing some training/fine-tuning of one of the vxm models.

To obtain the warp, please see an example in `test.py`. Essentially you:
- load the model (e.g.  `net = networks.cvpr2018_net(vol_size, nf_enc, nf_dec); net.load_weights(model_name);`) 
- the warp is the second output of the model. e.g. `[_, warp] = net.predict(data)`
- if you want to use the warp, please see `networks.nn_trf()` , and again see how it's used in `test.py`

**Comment by YuchuanQiao** [comment]
@adalca hi, is the warp in physical space or image space? the unit of the warp is in mm? or not? thank you.

**Comment by adalca** [comment]
@YuchuanQiao -- image space (voxels)

**Comment by YuchuanQiao** [comment]
@adalca I see, thank you.

**Comment by armaneshaghi** [comment]
> @neuronflow are the patient scans T1 as well?
> 
> I would first recommend doing some training/fine-tuning of one of the vxm models.
> 
> To obtain the warp, please see an example in `test.py`. Essentially you:
> 
> * load the model (e.g.  `net = networks.cvpr2018_net(vol_size, nf_enc, nf_dec); net.load_weights(model_name);`)
> * the warp is the second output of the model. e.g. `[_, warp] = net.predict(data)`
> * if you want to use the warp, please see `networks.nn_trf()` , and again see how it's used in `test.py`

@adalca I think this could become part of register.py, so people can run it from command line. 

Would you like me to send a PR for this?

**Comment by armaneshaghi** [comment]
@adalca or a second command line, such as `applyWarp.py` specifically for this.

**Comment by adalca** [comment]
@armaneshaghi thanks for the idea -- we have this already in the new branch, see https://github.com/voxelmorph/voxelmorph/blob/redesign/scripts/tensorflow/warp.py

This will be released soon and will replace the current code structure.
