### ISSUE TITLE
Coregistering with your own imaging data

### ISSUE THREAD

**Issue by nswinburne** [voxelmorph/voxelmorph#142]
Is it possible to add more instructions to the Registration section of the README?

When attempting to run register.py to coregister a patient brain MRI to the SPGR atlas, I get shape errors:

ValueError: Error when checking input: expected input_49 to have shape (160, 192, 224, 1) but got array with shape (256, 256, 32, 1)         

It seems that it's expecting the same shape as the provided atlas even though my reference is a different atlas.  I've tried first coregistering to the provided atlas using FSL but this fails due to the unusual orientation of that atlas.  Is there a good workaround?  Thanks.

**Comment by adalca** [comment]
@nswinburne we will add more instructions. For your case, could you please provide the command line that you ran? 

The models that we trained had the shape of `160x192x224x1`  The `load_model` function will load this model, and thus will expect that size. You can easily get around this by building the model you want, and loading the *weights* instead of the *model*. For example:

```
model = networks.cvpr2018_net(your_vol_size, nf_enc, nf_dec)
model.load_weights(the_model_file)
```

However, since you seem to have your own data, I would strongly recommend you do a few epochs of training (starting from our h5 models).

**Comment by nswinburne** [comment]
Thanks for the insight.  I am trying to register some internal brain MRI
data to the SRI24 atlas by running the following command:

python ./register.py --gpu 0 ../test_vol.nii ../sri24_atlas.nii --out_img
../out.nii.gz --model_file ../models/miccai2018_10_02_init1.h5

This gives me the aforementioned shape error.

If I want to train a model on my own data, I would first have to resample
all the nifti files so they have the same size (shape), is that correct?
Is there any other pre-processing required before the data can be used to
train?

**Comment by armaneshaghi** [comment]
> @nswinburne we will add more instructions. For your case, could you please provide the command line that you ran?
> 
> The models that we trained had the shape of `160x192x224x1` The `load_model` function will load this model, and thus will expect that size. You can easily get around this by building the model you want, and loading the _weights_ instead of the _model_. For example:
> 
> ```
> model = networks.cvpr2018_net(your_vol_size, nf_enc, nf_dec)
> model.load_weights(the_model_file)
> ```
> 
> However, since you seem to have your own data, I would strongly recommend you do a few epochs of training (starting from our h5 models).

@adalca 
could you provide examples of **re**training the model on new data?

**Comment by adalca** [comment]
@nswinburne The current version of vxm requires affine registered data -- we have a version that does this for you in the redesign branch, which will soon become the standard, but we're doing some final testing. So without this, you could: (1) affinely register all your images to some standard atlas space, then (2) run the train.py for the non-linear registration with vxm. Most of our experiments are on skull stripped normalized data, but it depends a lot on the type of data you have. 

@armaneshaghi retraining a model on new data is simply just using the train.py file with a `load_model_file` supplied.

**Comment by happybcloud** [comment]
when I trained train_seg_semisupervised.py,it had a mistake telling me Resource exhausted:OOM when allocating tensor with shape[88,104,88,57] ,I already add K.clear_session() to my code with batchsize=1
thx

**Comment by adalca** [comment]
@happybcloud did you try with a smaller image? perhaps your GPU is too small for that image size.

**Comment by happybcloud** [comment]
**@adalca** I will try your suggestions,thx
