### ISSUE TITLE
Instance specific optimization

### ISSUE THREAD

**Issue by theoVag** [voxelmorph/voxelmorph#143]
Hello,
I have a question from the article "VoxelMorph: A Learning Framework for Deformable Medical Image Registration". My question concerns the part from image below. Could you tell me what method did you use in instance specific optimization ? Is there any implementation to get a better understanding? Or could you give me a more detailed description for this part?

Thanks a lot and keep up the good work.
![Screenshot from 2020-02-03 14-02-21](https://user-images.githubusercontent.com/32677031/73652051-8b9f6180-468e-11ea-9efd-39c04f6fa215.png)

**Comment by adalca** [comment]
Hi @theoVag 

You can do this in several ways, but the simplest is to have a model that learns the displacement in a layer. The idea is to have a model that has as input the two models, and a layer that has a parameter at every voxel (this one layer replaces the unet in voxelmorph). Then you can warp one of the images with the output of this layer, and compare with the second image as you do in voxelmorph. 

To initialize the weights of this parameter, you can run your previously-trained vxm on some image pair, get the output, and load it as weights. 

The codebase has changed dramatically and this isn't one we've kept up, but we'll release a version of this in the `redesign`, hopefully in the next few days. Here's some semi-pseudo-code:

```
src = Input(shape=vol_size + (1,))
tgt = Input(shape=vol_size + (1,))
flow = neuron.layers.LocalParam(shape=vol_size + (3,)) # flow layer
y = neuron.layers.SpatialTransformer()([src, flow]) # warped image
insta_model = Model([src,tgt,v_flow], [y, flow])  # model

flow.set_weights(weights_from_vxm_output)  # load weights

model.compile(...)  # compile

model.fit(...)  # fit on your pair
```

@balakg do you have code for this lying around?

**Comment by adalca** [comment]
@theoVag 

@ahoopes has added an implementation of this in https://github.com/voxelmorph/voxelmorph/blob/redesign/scripts/tensorflow/train_instance.py -- this is part of a new refactoring of our code that will be up soon, but it enables you to see some instance-specific opt code.
