### ISSUE TITLE
Using VoxelMorph with 2d photon microscopy images

### ISSUE THREAD

**Issue by akatav** [voxelmorph/voxelmorph#149]
Is it possible to use VoxelMorph with 3d datasets obtained from 2d photon imaging of tissues at different focal lengths (3rd dim) to correct motion artifacts from breathing and head motion?Is there a use case of this ?Thank you.

**Comment by adalca** [comment]
We haven't done this, but perhaps vxm can be helpful if you give more details or explain more what your data is like?

**Comment by akatav** [comment]
@adalca  thanks for replying.sure,i can explain.Dataset consists of multichannel multiframe tiff files.Each frame is obtained at a deeper focal length of in-vivo tissue.We are looking to correct motion artifacts of brain images obtained by 2d photon microscopy on live mice at successive focal lengths along the axial plane. So, in summary, although we do not have a time scale right now(maybe in future),we are just looking to correct for motion artifacts within and between frames.
More formally,there are n tiff stacks. Each stack has Nimgs where each img is from a depth along the axial plane of the brain, n is the number of channels. Once motion corrected, we are looking to trace the dendrites belonging to a stack in 3d.

**Comment by adalca** [comment]
I think the motion between frames could definitely be done with vxm by using it on adjacent frames. Motion within frames I'm not sure, as I don't fully comprehend how this manifests in the images.

**Comment by akatav** [comment]
@adalca thanks again.Motion within frames happens because the images are taken row-wise (Raster scanning), sequentially (from left to right across and top-down fashion).Can you provide an example for between frame motion correction in vxm?

**Comment by adalca** [comment]
For that sort of setting, I've only done it experimentally with some histology data, but we have a 2-D tutorial at https://www.kaggle.com/adalca/learn2reg. Instead of using MNIST, you can just feed in adjacent images from your stack, and all else should be very similar.
