### ISSUE TITLE
Registration with own data

### ISSUE THREAD

**Issue by armaneshaghi** [voxelmorph/voxelmorph#151]
I am trying to retrain the MICCAI 2018 model with my own data. 

I have removed the skull, rescaled (range 0 to 1), recast to float, and resampled my images to 160 x 192 x 224 . I have converted my NIFTI files to .npz as explained in the documentation. 

I am using my own template as well, which I created by affine registration of my template to the one you have provided. 

I ran the following command:

`python train_miccai2018.py --atlas_file ./template_DL_noSkull.npz --load_model_file voxelmorph/models/miccai2018_10_02_init1.h5 --gpu 0,1 --steps_per_epoch 100 --epochs 1500 --lr 0.0001 --model_dir ./new_models_miccai/ --image_sigma 0.01 --batch_size 4 --prior_lambda 25  ./train/`

The loss seems to be quite high (about 200) and the model does not converge, I have waited up to 100 epochs. 

```

100/100 [==============================] - 250s 3s/step - loss: 220.5585 - spatial_transformer_1_loss: 209.7777 - concatenate_5_loss: 10.7808
Epoch 2/1500
100/100 [==============================] - 229s 2s/step - loss: 217.9164 - spatial_transformer_1_loss: 207.0999 - concatenate_5_loss: 10.8165
Epoch 3/1500
100/100 [==============================] - 227s 2s/step - loss: 216.2113 - spatial_transformer_1_loss: 205.4252 - concatenate_5_loss: 10.7861
Epoch 4/1500
100/100 [==============================] - 225s 2s/step - loss: 215.7948 - spatial_transformer_1_loss: 204.8948 - concatenate_5_loss: 10.9001
Epoch 5/1500
100/100 [==============================] - 225s 2s/step - loss: 217.0399 - spatial_transformer_1_loss: 206.2001 - concatenate_5_loss: 10.8399
Epoch 6/1500
100/100 [==============================] - 227s 2s/step - loss: 217.9617 - spatial_transformer_1_loss: 206.9990 - concatenate_5_loss: 10.9627
Epoch 7/1500
100/100 [==============================] - 226s 2s/step - loss: 222.8638 - spatial_transformer_1_loss: 211.8576 - concatenate_5_loss: 11.0062
Epoch 8/1500
100/100 [==============================] - 228s 2s/step - loss: 213.9191 - spatial_transformer_1_loss: 202.9843 - concatenate_5_loss: 10.9348
Epoch 9/1500
100/100 [==============================] - 225s 2s/step - loss: 220.6996 - spatial_transformer_1_loss: 209.7147 - concatenate_5_loss: 10.9850
Epoch 10/1500
100/100 [==============================] - 225s 2s/step - loss: 219.5768 - spatial_transformer_1_loss: 208.5653 - concatenate_5_loss: 11.0115
Epoch 11/1500
100/100 [==============================] - 224s 2s/step - loss: 214.5705 - spatial_transformer_1_loss: 203.5438 - concatenate_5_loss: 11.0267
Epoch 12/1500
100/100 [==============================] - 230s 2s/step - loss: 221.3336 - spatial_transformer_1_loss: 210.2824 - concatenate_5_loss: 11.0512
Epoch 13/1500
100/100 [==============================] - 229s 2s/step - loss: 221.3173 - spatial_transformer_1_loss: 210.3257 - concatenate_5_loss: 10.9917
Epoch 14/1500
100/100 [==============================] - 227s 2s/step - loss: 216.8826 - spatial_transformer_1_loss: 205.8614 - concatenate_5_loss: 11.0212
Epoch 15/1500
100/100 [==============================] - 227s 2s/step - loss: 216.0033 - spatial_transformer_1_loss: 204.9779 - concatenate_5_loss: 11.0254
Epoch 16/1500
100/100 [==============================] - 226s 2s/step - loss: 220.5126 - spatial_transformer_1_loss: 209.4179 - concatenate_5_loss: 11.0948
Epoch 17/1500
100/100 [==============================] - 226s 2s/step - loss: 213.2728 - spatial_transformer_1_loss: 202.2822 - concatenate_5_loss: 10.9906
Epoch 18/1500
100/100 [==============================] - 226s 2s/step - loss: 221.4961 - spatial_transformer_1_loss: 210.4481 - concatenate_5_loss: 11.0480
Epoch 19/1500
100/100 [==============================] - 225s 2s/step - loss: 213.0599 - spatial_transformer_1_loss: 202.0254 - concatenate_5_loss: 11.0345
Epoch 20/1500
100/100 [==============================] - 232s 2s/step - loss: 216.0980 - spatial_transformer_1_loss: 204.9946 - concatenate_5_loss: 11.1034

```
The registered image (using `register.py` and the newly trained model) looks like the below (range 0 to 1): 

![image](https://user-images.githubusercontent.com/4290297/74839931-01a5f880-531e-11ea-955b-3794149f6376.png)

I have also tried the CVPR version (with the `train.py` command instead of `train_miccai2018.py`) and looked at many different levels of lambda (0.01 to more than 10), although the loss is much different (gets to less than 1) but the alignment still does not look good, which means that there are gross misalignments. 

I would be grateful if you could  provide hints on how to improve.

**Comment by adalca** [comment]
@armaneshaghi to help us debug what is going on, could you please provide a panel of images with colorbars:

`input atlas | input image | warped image with vxm | deformation field` 

I would suggest we start with CVPR model since this is a bit simpler to parse. CC Loss with a lambda of 1 or 2 should be a good place to start. I'm happy to help you from there.

**Comment by armaneshaghi** [comment]
@adalca Thank you for the suggestion. CVPR models now work fine with your parameters. My focus is on diffeomorphic models from which I can also extract some measures of uncertainty. 

First row: fixed image
second row: moved image

<img width="1056" alt="image" src="https://user-images.githubusercontent.com/4290297/75578586-02483880-5a5c-11ea-8557-5297d780d834.png">

**Comment by adalca** [comment]
@armaneshaghi 

can you please show all the images I mentioned above? Without them it's quite hard to understand how good the registration is. Note that you can always warp one image to look like another by really torturing the warp field, but this is often not meaningful (see curt -- https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3274625/ )

**Comment by armaneshaghi** [comment]
Thanks @adalca . I agree with your statements and I am closing the issue.
