### ISSUE TITLE
From Model to Conditional Atlas

### ISSUE THREAD

**Issue by swinzeck** [voxelmorph/voxelmorph#152]
Thank you for providing the code for VoxelMorph. After training a model via `train_cond_template.py`, I am not entirely sure how the derive a conditional template. Could you please provide some more information on how to compute a conditional atlas (e.g. how to generate a template similar to the one you created for the brain-age dependency). Should this be multi-dimensional (3D volumes + conditional variables)?

**Comment by adalca** [comment]
@swinzeck looking at Figure 2 in our [paper](https://arxiv.org/pdf/1908.02738.pdf), the overall model essentially has the atlas as part of it. To extract this atlas model, simply use something like 

```
model_atlas_out = keras.models.Model(model.inputs[:2], model.get_layer('atlas').output)
```

This will then give you a model that outputs the atlas given some inputs. I believe the inputs (if you haven't changed anything) will be the first two inputs you have during training (which I think is a blurry initial atlas and the phenotipc value). Does this make sense?

**Comment by rsavjanimdphd** [comment]
Thank you very much for sharing this! I was able to get the model_atlas_out, but it's not so clear how to pass in the phenotypic value and output the atlas image. It would be great to loop through a range of phenotypic values and save out the corresponding nifti atlas images. Thank you!

**Comment by adalca** [comment]
@rsavjanimdphd , as mentioned above `model_atlas_out` does what you want. You simply need to:
``` 
for phenotype in my phenotypes:
  atlas = model_atlas_out.predict([phenotype])
```
Depending on how you set up the model (or which model you are using) you might need to pass in something else to the model, such as the initial blurry average. But that's the main idea

**Comment by rsavjanimdphd** [comment]
Ah, perfect, that was exactly what I needed, thank you!
