### ISSUE TITLE
SpatialTransformer

### ISSUE THREAD

**Issue by IemProg** [voxelmorph/voxelmorph#154]
I'm trying to duplicate the results published on Kaggle about Unsupervised  Deep Learning Registration "Learn2reg" using Neuro and Voxelmorph libraries.

https://www.kaggle.com/adalca/learn2reg

but I have a problem with using SpatialTransformer layer from neuron library as used in your tutorial.
But I'm getting an error which states that : 
""Wrap Tensors in `outputs` in `tf.identity` to avoid
    775                     # circular dependencies.
""
![Screen Shot 2020-02-24 at 12 03 02 AM](https://user-images.githubusercontent.com/29262325/75121932-38bb3780-5699-11ea-9526-db05c601953d.png)

What is the cause of this error even though I did follow the instructions as listed in the Kaggle jupyter ?

**Comment by adalca** [comment]
@IemProg,

did you get this error actually running the Kaggle jupyter (which you can do *in kaggle itself* by clicking 'copy and edit') or trying to remake the jupyter yourself?

This might be an issue with python/tensorflow versions and so on, so it would be great to know if you were able to run the jupyter within kaggle field.
