### ISSUE TITLE
We met some problems when we run uni_seg_test 

### ISSUE THREAD

**Issue by MoXiaoYing96** [voxelmorph/voxelmorph#155]
Hi! I'm trying to run the code of uni_seg_test.py by myself, but I have met the problem as same as the follower. It reminds me that there such file can't be found, and I have follow this topic for a long time, but it doesn't update for a while.

<img width="691" alt="uni_seg_test_error" src="https://user-images.githubusercontent.com/52778658/75339996-8c619700-58cc-11ea-8fe6-9facd1f9214c.png">

Please forgive me for the interrupting and maybe it will update recently or share the source model file for the public?

Thank you, wish you have a good day!

**Comment by adalca** [comment]
hi @MoXiaoYing96 

We don't have a file called `uni_seg_test.py`. If you mean `test_unsupervised_segmentation.py`, can you please tell us exactly what command you are running? With all the parameters, etc.

**Comment by MoXiaoYing96** [comment]
Hi! Forgive my lately response please!

I spelt wrong name of the file, it is test_unsupervised_segmentation.py. 
I am using **TensorFlow 1.8.0 & Python 3.6.7 & GPU Tesla V100 & CUDA9.0** .
I put the test_unsupervised_segmentation.py on the data folder and the command is **"python test_unsupervised_segmentation.py test_seg.npz 0222_uni_seg_test.nii"**.

It response to me that "**OSError: Unable to open file (unable to open file: name = '../models/unified_hardcodedstats_lambda_0.01_lr_0.001/60.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)**" .

Appreciate your warm response, thanks a lot!

**Comment by adalca** [comment]
Have you trained your own model? if so, you need to add the option `--model_file /path/to/your/model`.

**Comment by MoXiaoYing96** [comment]
Thank you so much! I will try it as soon!   : )
