### ISSUE TITLE
Training affine model (redesign branch) does not converge 

### ISSUE THREAD

**Issue by armaneshaghi** [voxelmorph/voxelmorph#156]
I am trying to train the affine model from the redesign branch. I am using the following command line on rescaled (0 to 1), resized, and brain extracted images. 

```
python train_affine.py --gpu 0 --steps-per-epoch 100 --epochs 1500 --lr 0.00001 --model-dir ./affine_models/ --batch-size 2 --prob-same 0.3  ./train/
```

Model loss starts at 0.88 but after a few epochs goes to -inf, 1 and stays at 1. 

If I use the affine model for registration, it produces empty outputs. 

Would you be able to provide a minimal example to train an affine model?

**Comment by armaneshaghi** [comment]
@ahoopes First thank you for making the codebase openly available. 

I have been working on this since my comment above. I have managed to solve the -inf issue. Usually the best (lowest) loss value I get is 0.93 or 0.94, which (I think) is a minor improvement over 0.98 or so loss value from my first epoch. I have tried epochs up to 500. 

These are the other things I have tried in vain:
1) increasing MRI volumes (up to 700 or so)
2) augmenting data by introducing random affine transformation


The model can perform good translation and possibly rotation, but *scaling* and **skewing**  do not work well (or at all). I can provide screenshot examples if it helps.  

Is the affine transformer expected to have scaling and skewing?

**Comment by adalca** [comment]
@armaneshaghi 
yes, the affine transformer should support scaling and skewing I believe.

Could you provide some screenshots (input images, output image, transform matrix). Also specify what loss you are using, etc.

**Comment by armaneshaghi** [comment]
@adalca 

affine matrix is : 
```
array([[ 4.71396357e-01, -1.29300207e-02,  1.43270925e-01,
         1.15289450e+01,  1.70000400e-02,  5.24089158e-01,
         4.06596586e-02,  3.65229874e+01, -1.26412570e-01,
         4.63673025e-02,  2.01046973e-01,  6.92713776e+01]])
```

Rows:
1) input or moving image
2) fixed image ( I have purposefully rescaled in my data augmentation)
3) Moved image

![image](https://user-images.githubusercontent.com/4290297/76635197-fde14c80-653e-11ea-82b9-e4b0933f1443.png)

**Comment by adalca** [comment]
Hi @armaneshaghi 

I guess I don't know that we've tested such exaggerated transformations, and perhaps we should -- but these are simulated, correct? Does the algorithm do very badly on real data?

**Comment by armaneshaghi** [comment]
thanks @adalca . 

Yes these are simulated. It fails similarly in real data. The reason to have simulated and exaggerated scaling was that the affine transformer was not learning scaling at all in real data, so I thought simulation might help, but it did not.

**Comment by adalca** [comment]
@armaneshaghi Could you show some real data example failures?

**Comment by armaneshaghi** [comment]
affine: 

```
array([[-4.16451506e-02, -5.90295233e-02,  4.61192429e-02,
         1.12353363e+01,  1.64070547e-01,  1.86138675e-02,
         4.44486961e-02,  2.19804173e+01, -7.39005059e-02,
        -3.22621502e-03,  1.65769190e-01,  5.57694855e+01]])
```
Rows (slices chosen based on the center of mass of the moved image):
- Input or moving image
- Fixed image ( I have purposefully rescaled in my data augmentation)
- Moved image (or transformed input image)



![image](https://user-images.githubusercontent.com/4290297/76637082-071fe880-6542-11ea-846e-bde912af1355.png)


Some trained models like your CVPR models to start with, could help to re-train.

**Comment by adalca** [comment]
Hm, while this isn't perfect, I am kind of confused about the comment of "the affine transformer was not learning scaling at all in real data" as it pertains to this example?

**Comment by armaneshaghi** [comment]
I should have said "scaling was not perfect". Thanks.

**Comment by adalca** [comment]
Yeah, that might be true. It would be interesting to (1) see how other methods (like ants, niftireg, etc) perform, and (2) aspects about your trianing -- how did the loss converge, etc?

**Comment by armaneshaghi** [comment]
The loss never went below 0.90, started from 0.98. Even after 500 epochs or so. The command line is what I used above with a change in Epochs (500). 

I have now added a fourth row with ANTs output using rigid+affine option in `antsRegistrationSyNQuick.sh` script. 

Rows:
- input or moving
- fixed
- moved by VM
- moved by ANTs
![image](https://user-images.githubusercontent.com/4290297/76640049-28370800-6547-11ea-89db-86404acec606.png)

**Comment by adalca** [comment]
Thanks, but regarding the loss it would be great to see a graph, to understand how fast it was changing, how converged it was at the end, etc?

We'll look into this after the MICCAI deadline. We found the results to be very comparable with ants.
