### ISSUE TITLE
Concatenating affine and warp with `warp.py`

### ISSUE THREAD

**Issue by armaneshaghi** [voxelmorph/voxelmorph#157]
A feature request for concatenating affine and warp outputs, so one will only need to interpolate the images once. Happy to help with a PR if you provide hints.

**Comment by adalca** [comment]
We have a `compose` function in https://github.com/adalca/neuron/blob/master/neuron/utils.py

To make it into a layer, You could wrap this function into a standard Layer in a few lines. If you feel like doing this, please help us with a PR to [neuron](https://github.com/adalca/neuron) in the layers.py file.

**Comment by ahoopes** [comment]
FYI as of f94e484f57aef27d3c024f98335265e84e623df8, there is a `ComposeTransform` layer available in the redesign branch (although, this does not solve the original request of concatenating affines and dense warps)

**Comment by adalca** [comment]
@ahoopes  thanks! 

It should be fairly easy to expand the functionality to be used with affine+dense (or dense+affine), no? Simply transform the affine to a dense (which we already do in the SpatialTransformer) and then apply the current functionality? or am I missing something?

**Comment by ahoopes** [comment]
Ah right, my mistake! You can use the `neuron.utils.affine_to_shift()` function to convert an affine matrix to a dense location shift tensor
