### ISSUE TITLE
Duplicate of 'Data Loaded Error'

### ISSUE THREAD

**Issue by satrajitgithub** [voxelmorph/voxelmorph#16]
Hi,
I am trying to run the command:

train_miccai2018.py C:/Users/schakr01/Desktop/NRG/voxelmorph/voxelmorph/data --gpu 0 --model_dir C:/Users/schakr01/Desktop/NRG/voxelmorph/voxelmorph/models

but getting the same error which I am copy-pasting below:

Using TensorFlow backend.
2018-11-16 14:32:06.593595: I tensorflow/core/platform/cpu_feature_guard.cc:141]
 Your CPU supports instructions that this TensorFlow binary was not compiled to
use: AVX2
Epoch 1/1500
Traceback (most recent call last):
  File "C:\Users\schakr01\Desktop\NRG\voxelmorph\voxelmorph\src\train_miccai2018
.py", line 191, in <module>
    train(**vars(args))
  File "C:\Users\schakr01\Desktop\NRG\voxelmorph\voxelmorph\src\train_miccai2018
.py", line 146, in train
    verbose=1)
  File "C:\Users\schakr01\AppData\Local\Programs\Python\Python36\lib\site-packag
es\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\schakr01\AppData\Local\Programs\Python\Python36\lib\site-packag
es\keras\engine\training.py", line 1415, in fit_generator
    initial_epoch=initial_epoch)
  File "C:\Users\schakr01\AppData\Local\Programs\Python\Python36\lib\site-packag
es\keras\engine\training_generator.py", line 177, in fit_generator
    generator_output = next(output_generator)
  File "C:\Users\schakr01\AppData\Local\Programs\Python\Python36\lib\site-packag
es\keras\utils\data_utils.py", line 793, in get
    six.reraise(value.__class__, value, value.__traceback__)
  File "C:\Users\schakr01\AppData\Local\Programs\Python\Python36\lib\site-packag
es\six.py", line 693, in reraise
    raise value
  File "C:\Users\schakr01\AppData\Local\Programs\Python\Python36\lib\site-packag
es\keras\utils\data_utils.py", line 658, in _data_generator_task
    generator_output = next(self._generator)
  File "C:\Users\schakr01\Desktop\NRG\voxelmorph\voxelmorph\src\datagenerators.p
y", line 41, in miccai2018_gen
    X = next(gen)[0]
  File "C:\Users\schakr01\Desktop\NRG\voxelmorph\voxelmorph\src\datagenerators.p
y", line 66, in example_gen
    X = load_volfile(vol_names[idx])
  File "C:\Users\schakr01\Desktop\NRG\voxelmorph\voxelmorph\src\datagenerators.p
y", line 127, in load_volfile
    X = np.load(datafile)['vol_data']
  File "C:\Users\schakr01\AppData\Local\Programs\Python\Python36\lib\site-packag
es\numpy\lib\npyio.py", line 239, in __getitem__
    raise KeyError("%s is not a file in the archive" % key)
KeyError: 'vol_data is not a file in the archive'

I have a TensorFlow version of 1.12.0 running on my computer.

**Comment by adalca** [comment]
Hi,

The error indicates that you have passed a filepath in `C:/Users/schakr01/Desktop/NRG/voxelmorph/voxelmorph/data/` with files that do not match how our data was organized. Originally, our data is organized in npz files, each of which has  'vol_data' variable with the volume in it. However, the data generator also handles other files (like nifti). Can you tell me what type of files you have?

Thanks!

**Comment by satrajitgithub** [comment]
After pulling the repo, I didn't modify the data folder so it has the original structure. It looks like this:
![image](https://user-images.githubusercontent.com/38768265/48663871-082f2b80-ea5c-11e8-8e7d-d3f94559a0f3.png)
Do I need to make any modifications in the folder?

**Comment by adalca** [comment]
We should be more clear -- the path you pass as the first argument to train should have all your subjects that you want to align. The `voxelmorph/data/` folder is simply folder that includes data users might want to play with (e.g. the atlas, the labels we use, and an example subject). 

If you'd like to train voxelmorph to work for a population, you need more images. But to get started, here's a quick thing you can do: copy `test_vol.npz` to some general data folder, and then pass that folder to voxelmorph, and the `voxelmorph/data/atlas_norm.npz` as the atlas. This should work.

**Comment by satrajitgithub** [comment]
Hi Adrian. It'll be great if you can provide the script. Thank you so much!

**Comment by satrajitgithub** [comment]
Hi @adalca 
It will be great if you can provide the script for running the registration.

**Comment by adalca** [comment]
@satrajitgithub apologies for the delay on this
I'm trying to write a robust script for people to use, but we have been travelling for a bit. Script should be up soon.  Did you try simple loading the model `model.load_weights` and then running `model.predict(ref, image)` ? This should do the trick for a quick experiment.

**Comment by satrajitgithub** [comment]
Hi @adalca I will try doing that. Thanks!

**Comment by adalca** [comment]
@satrajitgithub sorry about the delay. I've updated a rudimentary `register.py` in the `src` folder.

**Comment by ZQYzqyZ** [comment]
Hi adalca:
    When I run the train.py, I also encountered the problem mentioned above.(KeyError: 'vol_data is not a file in the archive').You said copy `test_vol.npz` to some general data folder, and then pass that folder to voxelmorph, and the `voxelmorph/data/atlas_norm.npz` as the atlas. This should work.But I don't know how to do this.So could you please send me the code and data after your change? I am looking forward to your reply.

**Comment by adalca** [comment]
Hi,

Can you tell me which part you don't know how to do? 

Here's what I am suggesting:
1. move `test_vol.npz` to `/some/path/wherever`
2. Then run train simply as: `train_miccai2018.py /some/path/wherever --atlas_file ../data/atlas_norm.npz`
This should work, I think.
