### ISSUE TITLE
Applying Trained Registration to Label Results in Interpolation on the Boundaries

### ISSUE THREAD

**Issue by emckenzi123** [voxelmorph/voxelmorph#160]
**Task** (what are you trying to do/register?)

First of all, thank you very much for putting this code together and making it available.  I really appreciate it!!  
So, I have successfully trained a network in Voxelmorph and would like to validate my registration using label comparison statistics (such as Dice, etc.).  I am able to pass two CT volumes into the network and get a good looking registered CT.  However, if I apply this corresponding warp field to a label map of the source CT's segmentations the boundaries of each label become mixed in values. With these mixed values I cannot use the label comparison methods.  

**What have you tried**

I used the nrn_layers.SpatialTransformer with nearest interpolation.  However there still appears to be some interpolation occurring on the boundaries.

code used:

**y_seg = nrn_layers.SpatialTransformer(interp_method='nearest', indexing=indexing)([src_seg, flow])**

-y_seg is the resulting deformed segmentation label map
-indexing is set to 'ij'
-src_seg is the original source undeformed segmentation label map
-flow is the flow field output from the Voxelmorph network.

example of output:

![image](https://user-images.githubusercontent.com/28455475/75955616-1aa8c080-5e6b-11ea-8d8e-d4012fa9d4e1.png)

**Details of experiments**

I have dug through the source code a bit trying to see where the interpolation was occurring and if it was somehow possible for me to fix, however after several hours of searching I decided to post here and ask for help.  I'm not sure if you have seen this happen?  

Thank you in advance,
-E

**Comment by adalca** [comment]
I agree that this looks from the image like it may be doing some weird interpolation, but we've never seen this for nearest neighbor interpolation option, so I am a bit confused and suspect there is a bug elsewhere. Some notes:

 - can you try `networks.nn_trf()` to warp your data? just get a model from that function, then use the model to apply your transform
- If that still behaves weirdly, to double check, can you send me your original image, original segmentation, and resulting flow (all in a numpy file, say)?
- To answer your question about the code, the code dependence follows `layers.SpatialTransform() -> utils.transform -> utils.interpn()` and in `internp` the nearest neighbour is implemented [here](https://github.com/adalca/neuron/blob/95ee00ea25bfe964a80aaa7a9198049e8a93e4b7/neuron/utils.py#L139). But I doubt there's an issue here, we've been using this code for a couple of years without this issue.

**Comment by emckenzi123** [comment]
Ah after getting some sleep and looking at it the next day I realized it was user error. Thank you so much for all of your help!

**Comment by hsiangyuzhao** [comment]
> **Details of experiments**
> 
> I have dug through the source code a bit trying to see where the interpolation was occurring and if it was somehow possible for me to fix, however after several hours of searching I decided to post here and ask for help. I'm not sure if you have seen this happen?
> 
> Thank you in advance, -E

Sorry to bother but I wonder what kind of bug you have encountered there? I have met the same problem and I have no idea where the fault lies.

**Comment by adalca** [comment]
If you are warping a segmentation map (not a one-hot representation), you need to warp with the nearest-neighbour interpolation - are you doing this? Alternatively, you need to go to one-hot (`tf.one_hot`), warp that, then take the `argmax` along the last dimension.

**Comment by hsiangyuzhao** [comment]
> If you are warping a segmentation map (not a one-hot representation), you need to warp with the nearest-neighbour interpolation - are you doing this? Alternatively, you need to go to one-hot (`tf.one_hot`), warp that, then take the `argmax` along the last dimension.

Thanks! That's exactly what I have mistaken.
