### ISSUE TITLE
An error occurred in the registration of the self-trained model

### ISSUE THREAD

**Issue by CGC1031** [voxelmorph/voxelmorph#162]
I'm trying to use my trained model, as shown on the command line below.However, the following error occurred. I have difficulty in solving the problem.Could you tell me  any good Suggestions?Looking forward to hearing from you. 
CMD:`python Register.py --gpu 0 --moving E:/voxelmorph-master/data/test_vol.nii.gz --fixed E:/voxelmorph-master/data/atlas_norm.nii.gz --out_img E:/voxelmorph-master/data/01.nii.gz --model_file E:/voxelmorph-master/models/01.h5`
ERRORS:
![QQ图片20200315122951](https://user-images.githubusercontent.com/53649087/76695314-c8f90500-66b8-11ea-873a-728b89de7761.png)
![QQ图片20200315123027](https://user-images.githubusercontent.com/53649087/76695316-ce564f80-66b8-11ea-8818-d1c8252e1036.png)

**Comment by adalca** [comment]
hi @CGC1031  can you tell us which version of tensorflow you are running, and when you downloaded the code? This feels like a version mismatch
