### ISSUE TITLE
What versions of tensorflow/keras is supported/expected? Perhaps a requirements.txt file would be useful.

### ISSUE THREAD

**Issue by ascourge21** [voxelmorph/voxelmorph#163]
**Task** (what are you trying to do/register?)
Right now, just testing the MNIST example from kaggle. Ultimately want to register 2D cardiac ultrasound images.

**What have you tried**
The spatial_transformer_network doesn't work for me. I get the following error:
> AttributeError: module 'tensorflow' has no attribute 'Dimension'

**Details of experiments**
Using tensorflow 1.15 seems to solve the problem. I can try adding a requirements.txt perhaps as well, but will leave this issue so its flagged.

**Comment by adalca** [comment]
we ran tf 1.14, btu are currently testing 2.0 as well. We'll add a requirements.txt to the redesign branch which we'll launch soon -- unless @ahoopes has a different idea?

**Comment by ahoopes** [comment]
Yeah that sounds good. I can add one. The soon-to-be-released redesign branch will be TF2 compatible, but as you mentioned, there are a few issues in the master branch preventing current 2.0 compatibility. If you manually update the neuron distribution in `ext/neuron` and replace all references to `tf.Dimension` with `tf.compat.v1.Dimension`, that might get things working. Haven't fully tested this though.

**Comment by adalca** [comment]
Just as a quick update, `voxelmorph` and `neurite` have setup files and are on pip now.
