### ISSUE TITLE
Trouble installing locally. It would be really helpful to have a requirements.txt and setup.py file

### ISSUE THREAD

**Issue by jayurbain** [voxelmorph/voxelmorph#167]
**Task** (what are you trying to do/register?)

Install voxelmorph repo locally

**What have you tried**
Unless I run from the root of the voxelmorph repo, I've had trouble running the package. 

Here's what I've tried:
Download voxelmorph repo as subdirectory of my working directory.

Added the following path command:
PYTHONPATH=$PYTHONPATH:/path/to/voxelmorph/ext/neuron/:/path/to/voxelmorph/ext/pynd-lib/:/path/to/voxelmorph/ext/pytools-lib/

In code added the following to system path
sys.path.append(path + 'voxelmorph/')

Get no error with the following imports:
import voxelmorph as vxm
import neuron

No problem using neuron package functions.

Get error using voxelmorph modules:
AttributeError                            Traceback (most recent call last)
<ipython-input-23-25fd7100013c> in <module>
      1 # first, let's get a unet (before the final layer)
----> 2 unet = vxm.networks.unet_core(vol_shape, nb_enc_features, nb_dec_features);

AttributeError: module 'voxelmorph' has no attribute 'networks'

Any direction would be appreciated.

Thanks,
Jay

**Comment by adalca** [comment]
Hi @jayurbain 

Can you clarify if you are installing the `master`, or the `redesign` branch?

**Comment by adalca** [comment]
Just as a quick update, `voxelmorph` and `neurite` have setup files and are on pip now.
