### ISSUE TITLE
How to calculate ‘bin_center’ in mi loss

### ISSUE THREAD

**Issue by SZUHvern** [voxelmorph/voxelmorph#168]
Thank you for sharing multiple loss functions to achieve multiple goals
I have encountered difficulties when using MI loss. I don't understand how to set ‘bin_center’ in MI. I have checked the documentation in the MIT library, but for me it is still unclear.
Could you please share the code that specifically uses MI loss?

**Comment by adalca** [comment]
bin centers should be the center of the bins that intensities will be put in.
So if your image intensity ranges from 0 to 1, then perhaps you can set the bin ranges to `np.linspace(0,1, nb_bins)` where nb_bins is something like 32. This will make the first and last bins behave slightly different than the rest, but that's ok.
