### ISSUE TITLE
Semisupervised training

### ISSUE THREAD

**Issue by theoVag** [voxelmorph/voxelmorph#169]
Hello,
I am not sure I understand how the semisupervised works. I would like to train the network (subject-2-subject) with labels for only some of the available volumes. How does the network take in the input the labels for a part of volumes? And how is being trained for the volumes where there are not available labels? In other words how does the network handle the fact that some volumes have labels and others don't?

Thank you very much

**Comment by adalca** [comment]
For your first part, so that I understand where to begin, did you read our description in the TMI paper (https://arxiv.org/abs/1809.05231)? The semi-supervised method is a big part of that paper. In this initial version, we did not use any of the non-labelled images, our point was more about how to use the labelled ones in training. The Figure in that paper should shed light on how the model works.

To combine labelled and unlabelled we have information here: https://arxiv.org/abs/1908.04466 . In terms of implementation, the simplest thing to do is to use the same implementation as the TMI paper, and just feed in a 'background' segmentation (e.g. segmentation map where everything is background for both images) for those, and I think this will work as you'll get no useful gradient from the segmentation loss for those images, which is what you want. Alternatively you can have a fancier implementation that turns off the segmentation weight for the unlabelled images, but I think that's unnecessary.

**Comment by ElegantLin** [comment]
Dear authors,

I also have some problem with semi-supervised training. I did not find the test program about semi-supervised and I create a new program based on the unsupervised test file. I change the model from `VxmDense` to `VxmDenseSemiSupervisedSeg` and load the checkpoint file from `train_semisupervised_seg.py`. The result I got is very strange and I wonder whether my steps are correct.

Thanks!

**Comment by adalca** [comment]
@ElegantLin can you provide more information? What is the result, etc. Overall the idea seems right, but there are a lot of details to get right, of course.

**Comment by ElegantLin** [comment]
Thanks for your quick reply.

The code I used is 

```
with tf.device(device):

    # load model and build nearest-neighbor transfer model
    registration_model = vxm.networks.VxmDenseSemiSupervisedSeg.load(args.model).get_registration_model()
    inshape = registration_model.inputs[0].shape[1:-1]
    transform_model = vxm.networks.Transform(inshape, interp_method='nearest')

    for i in range(len(img_pairs)):

        # load moving image and seg
        moving_vol = vxm.py.utils.load_volfile(
            img_pairs[i][0], np_var='vol', add_batch_axis=True, add_feat_axis=add_feat_axis)
        moving_seg = vxm.py.utils.load_volfile(
            seg_pairs[i][0], np_var='seg', add_batch_axis=True, add_feat_axis=add_feat_axis)

        # load fixed image and seg
        fixed_vol = vxm.py.utils.load_volfile(
            img_pairs[i][1], np_var='vol', add_batch_axis=True, add_feat_axis=add_feat_axis)
        fixed_seg = vxm.py.utils.load_volfile(
            seg_pairs[i][1], np_var='seg')

        # predict warp and time
        start = time.time()
        warp = registration_model.predict([moving_vol, fixed_vol])
        reg_time = time.time() - start
        if i != 0:
            # first keras prediction is generally rather slow
            reg_times.append(reg_time)

        # apply transform
        warped_seg = transform_model.predict([moving_seg, warp]).squeeze()

        # compute volume overlap (dice)
        overlap = vxm.py.utils.dice(warped_seg, fixed_seg, labels=labels)   
        dice_means.append(np.mean(overlap))
        print('Pair %d    Reg Time: %.4f    Dice: %.4f +/- %.4f' % (i + 1, reg_time,
                                                                    np.mean(overlap),
                                                                    np.std(overlap)))
```

The same testing data I used from `test.py` using unsupervised and the result is

```
Pair 1    Reg Time: 8.5144    Dice: 0.4222 +/- 0.2646
Pair 2    Reg Time: 3.0140    Dice: 0.4654 +/- 0.0843
Pair 3    Reg Time: 2.8464    Dice: 0.5470 +/- 0.0642
Pair 4    Reg Time: 2.8613    Dice: 0.3773 +/- 0.0864
Pair 5    Reg Time: 2.6998    Dice: 0.2471 +/- 0.0963
Pair 6    Reg Time: 2.7484    Dice: 0.1950 +/- 0.1238
Pair 7    Reg Time: 2.7477    Dice: 0.4867 +/- 0.1545
Pair 8    Reg Time: 2.7271    Dice: 0.0780 +/- 0.1351

Avg Reg Time: 2.8064 +/- 0.1015  (skipping first prediction)
Avg Dice: 0.3523 +/- 0.1522
```

However, when I used a weight from semi-supervised and tested it with the code above and the same data, the result is 

```
Pair 1    Reg Time: 8.3701    Dice: 0.0000 +/- 0.0000
Pair 2    Reg Time: 2.9412    Dice: 0.0000 +/- 0.0000
Pair 3    Reg Time: 2.7902    Dice: 0.0000 +/- 0.0000
Pair 4    Reg Time: 2.8090    Dice: 0.0000 +/- 0.0000
Pair 5    Reg Time: 2.8164    Dice: 0.0000 +/- 0.0000
Pair 6    Reg Time: 2.6783    Dice: 0.0000 +/- 0.0000
Pair 7    Reg Time: 2.7020    Dice: 0.0000 +/- 0.0000
Pair 8    Reg Time: 2.7635    Dice: 0.0076 +/- 0.0100

Avg Reg Time: 2.7858 +/- 0.0799  (skipping first prediction)
Avg Dice: 0.0009 +/- 0.0025
```

The semi-supervised training loss goes normally so I suspect there is something wrong with the testing code.

Could you please help me with it? I don't know where the mistake is.

Thanks!
