### ISSUE TITLE
Problem about train_unsupervised_segmentation.py

### ISSUE THREAD

**Issue by Alison-brie** [voxelmorph/voxelmorph#176]
**Task** (what are you trying to do/register?)

Try to re-implementation of  "Unsupervised deep learning for Bayesian brain MRI segmentation" using train_unsupervised_segmentation.py on my own brain vol data.

**What have you tried**

The train_unsupervised_segmentation.py doesn't work for me. I get the following error:

AttributeError: tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[1,160,192,224,11] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[{{node training/Adam/gradients/lambda_1/Sum_grad/Tile}}]]

**Details of experiments**

TensorFlow 1.13.1
Keras 2.2.4
gpu_device TITAN Xp
totalMemory: 12.00GiB freeMemory: 9.94GiB
Default parameters for the train_unsupervised_segmentation.py, except the data_dir.

I also tried the vm1 model with diffeomorphic=True, still got the same question. It seems that I need a GPU with more memory, and do you think so? Or do I have to reduce the model size more? (my data size is (160,192,224))
I wonder how much memory of GPU you run your code on?
And it would be great to give some suggestions or opinions.

Thanks for your time a lot.

**Comment by adalca** [comment]
Hi @Alison-brie 

Sorry for the delay, I know we missed this in April. It did seem like you had an issue with memory. Does the new code in the official branch help?
