### ISSUE TITLE
about liver preprocess

### ISSUE THREAD

**Issue by zzx332** [voxelmorph/voxelmorph#179]
Hi,
I saw the following sentence in the paper
"The  regions of interest (128×128×128 voxels) containing the liver  are extracted for further processing."
Is there any specific way to extract the regions?I extract by manual, the result seems not good enough.(the mean dice between the raw liver image is about 0.6)

**Comment by adalca** [comment]
In which paper? We don't have a paper related to VoxelMorph that tackles the liver.

Having said that, if you show us some images you cropped and are trying to register, we can probably give you hints.

Were the images normalized [0,1]? Did you train a new model? with `ncc` ?

**Comment by zzx332** [comment]
Sorry, this is a misunderstanding.
