### ISSUE TITLE
A request of atlas.nii

### ISSUE THREAD

**Issue by SY51826** [voxelmorph/voxelmorph#18]
hello,I am a newcomer to medical image processing.And I don't understand the process of preprocessing very well.Could you provide a copy of the original atlas.nii file rather than .npz format?I want to use it to do some tests.My email address is : 851128561@qq.com. Thank you very much.

**Comment by adalca** [comment]
We've added the atlas nifti to the data folder.

**Comment by SY51826** [comment]
Thanks @adalca.I tried to generate atlas nifti with ANTs, but I got the following result.
![image](https://user-images.githubusercontent.com/46043268/51658325-9a1a5e00-1fe2-11e9-88a0-5b63a0be3995.png)
![image](https://user-images.githubusercontent.com/46043268/51658351-b4543c00-1fe2-11e9-9dda-5be3ba3f8158.png)
atlas_norm.nii is on the left side.
The image I generated is on the right side.
I used ten different brainmask.nii data processed by affine transformation to build the template.The result is not very good.Could you tell me how to generate a template as good as yours like atlas_norm.nii ?How to set parameters when building a template？

**Comment by adalca** [comment]
Atlases depend on many things, not just algorithm parameters -- such as the data itself. What data did you use? 

The atlas we are using was built back in 2013 using [Buckner40](https://surfer.nmr.mgh.harvard.edu/fswiki/Buckner40Notes) data, and I don't recall what parameters we used to build it, unfortunately. However, if the image on the right is your  atlas, I'm not sure why you say it doesn't look so good, it looks fine to me.

**Comment by SY51826** [comment]
Sorry to bother you again.I use ADHD200 data to build the template with ANTs. But I can't generate the corresponding segmentation data in the process of making a template.

Could you tell me what tool did you use? ANTs or Freesurfer？
Could you share the command which you used？

Thank you very much！

**Comment by adalca** [comment]
do you have segmentations from your subjects? if so, you could try registering all your data to your atlas, and then propagating the segmentations. 

We used ANTs to create the 2013 atlas.

**Comment by SY51826** [comment]
I have 100 subjects and 100 segmentations corresponding to these subjucts. Suppose I don't have atlas,and I would like to build a template as atlas with these subjucts.So I couldn't " try registering all your data to your atlas, and then propagating the segmentations",according to your answer.I calculated the average of 100 subjects to get an atlas, but I couldn't propagate the segmentations to generate the segmentation of atlas with the output files.Do you have any suggestions on how to generate a segmentation of the atlas?

The output files when making atlsa：
![image](https://user-images.githubusercontent.com/46043268/60500939-bfc43580-9ced-11e9-8483-404ff20880a2.png)

**Comment by SY51826** [comment]
@adalca I have 100 subjects and 100 segmentations corresponding to these subjucts. Suppose I don't have atlas,and I would like to build a template as atlas with these subjucts.So I couldn't " try registering all your data to your atlas, and then propagating the segmentations",according to your answer.I calculated the average of 100 subjects to get an atlas, but I couldn't propagate the segmentations to generate the segmentation of atlas with the output files.Do you have any suggestions on how to generate a segmentation of the atlas?

The output files when making atlsa：
![image](https://user-images.githubusercontent.com/46043268/60501220-3e20d780-9cee-11e9-8c51-fe3b34b70301.png)

**Comment by adalca** [comment]
how did you create the atlas? could you show a screenshot of it? with ANTs, or just by averaging? The latter won't be sufficient, but if you used something like ANTs, then it should be good. BTW, sometime in within the next month we will release scripts that enable building atlases with voxelmorph directly.

If the atlas is built with ANTs or similar, then you should register all subjects to the atlas (e.g. by training voxelmorph), then propagate all the segments via those registrations (see `nn_trf_model.predict` line in `test.py` for an example)
