### ISSUE TITLE
code about the network structure

### ISSUE THREAD

**Issue by NovemberSun** [voxelmorph/voxelmorph#19]
I have some doubts about the code implementation of the network structure, which seems to be different from the version in the cvpr paper．
In the code, the order of downsampling is different, and the feature map is not the same. For example, the third layer is concatenated ​​with  the first layer(the original fixed and moving image).

**Comment by balakg** [comment]
Can you further clarify which part of the network code seems wrong with the paper? The third layer (which would belong to the encoder) is not connected to the first layer. There are four concatenations in the model, connecting one volume of the encoder with the appropriate volume in the decoder with similar dimensions.

**Comment by balakg** [comment]
Ah yes, you're right, that is inconsistent with the paper. The code is accurate for what we did in our experiments though.

**Comment by balakg** [comment]
The results in the paper correspond to the code in the repo. The figure has a slight error. That being said, based on our various experiments afterwards, such a minor change will not have any significant impact on results.
