### ISSUE TITLE
Is affine VoxelMorph available?

### ISSUE THREAD

**Issue by Noodles-321** [voxelmorph/voxelmorph#191]
I saw VoxelMorph model for **affine** transformation mentioned in #156 , #164 and some [other issues](https://github.com/voxelmorph/voxelmorph/issues/61#issuecomment-500231180), but haven't found it in the code. Is it available somewhere?
Thanks!

**Comment by adalca** [comment]
@Noodles-321 , we have an implementation in the [redesign](https://github.com/voxelmorph/voxelmorph/tree/redesign/voxelmorph) branch

**Comment by Noodles-321** [comment]
Awesome! Thanks a lot! I am closing this issue and will try it out.

**Comment by leandrogomide** [comment]
Since redesign branch is no longer available, what are the current steps fro training an affine transformation model?
