### ISSUE TITLE
which version of Keras?

### ISSUE THREAD

**Issue by ivttch** [voxelmorph/voxelmorph#192]
Hi, I run code on Tensorflow 2.0, but many packages in keras didn't work. Could you please tell me which Keras version you used ? And when will you release the code for Tensorflow 2.0? Thank you.

**Comment by adalca** [comment]
The original code was written for `tf 1.14` and `keras 2.2.4`. However, the updated voxelmorph, especially the one in the `redesign` branch, should work with `tf 2.0`. @ahoopes is this correct?

Let us know of bugs you have.

**Comment by ivttch** [comment]
Thank  you for replying.  I tried the redesign branch with tf 2.2 , but it always got this bug in networks.py:

> Traceback (most recent call last):
>   File "/Users/PycharmProjects/voxelmorph/voxelmorph/tf/networks.py", line 9, in <module>
>     from .. import default_unet_features
> ValueError: attempted relative import beyond top-level package

**Comment by ivttch** [comment]
Thank you for replying. I tried the redesign branch with tf 2.2 , but it always got this bug in networks.py:

> Traceback (most recent call last):
> File "/Users/PycharmProjects/voxelmorph/voxelmorph/tf/networks.py", line 9, in
> from .. import default_unet_features
> ValueError: attempted relative import beyond top-level package

**Comment by adalca** [comment]
Hi @ivttch  sorry for the delay on this, we've been hard at work on the new version. Can you take a look at the master branch now and see if that works?
