### ISSUE TITLE
How to plot deformation field in a grid way?

### ISSUE THREAD

**Issue by yangglebin** [voxelmorph/voxelmorph#194]
Hi,
    I've seen deformation field in a grid way in voxelmorph paper, but I don't know how to plot it, could you give some information or tips about that? thx.

**Comment by adalca** [comment]
Can you point me to an example image you are talking about?

You are **probably** referring to doing this:
- create a black and white grid volume image using `pynd.ndutils.bw_grid()`  
- warp this with your warp field, for example using a transfer model (see our test.py)  
- display the result

**Comment by yangglebin** [comment]
> Can you point me to an example image you are talking about?
> 
> You are **probably** referring to doing this:
> 
> * create a black and white grid volume image using `pynd.ndutils.bw_grid()`
> * warp this with your warp field, for example using a transfer model (see our test.py)
> * display the result

Thank you,I've got the idea, but it seems that util.warp_seg function must be used, can you point where the function is?

**Comment by adalca** [comment]
we actually recommend you use the SpatialTransformer, something like:

```
def trf(vol_size, indexing='xy'):
    """
    Simple transform model for nearest-neighbor based transformation
    Note: this is essentially a wrapper for the neuron.utils.transform(..., interp_method='nearest')
    """
    ndims = len(vol_size)

    # nn warp model
    subj_input = Input((*vol_size, 1), name='subj_input')
    trf_input = Input((*vol_size, ndims) , name='trf_input')

    # note the nearest neighbour interpolation method
    # note xy indexing because Guha's original code switched x and y dimensions
    output = nrn_layers.SpatialTransformer(indexing=indexing)
    spatial_output = output([subj_input, trf_input])
    return keras.models.Model([subj_input, trf_input], spatial_output)
```

Then make a model and do `model.predict()` to warp

**Comment by yangglebin** [comment]
> we actually recommend you use the SpatialTransformer, something like:
> 
> ```
> def trf(vol_size, indexing='xy'):
>     """
>     Simple transform model
>     """
>     ndims = len(vol_size)
> 
>     # nn warp model
>     subj_input = Input((*vol_size, 1), name='subj_input')
>     trf_input = Input((*vol_size, ndims) , name='trf_input')
> 
>     # note the nearest neighbour interpolation method
>     # note xy indexing because Guha's original code switched x and y dimensions
>     output = nrn_layers.SpatialTransformer(indexing=indexing)
>     spatial_output = output([subj_input, trf_input])
>     return keras.models.Model([subj_input, trf_input], spatial_output)
> ```
> 
> Then make a model and do `model.predict()` to warp

Thanks.
