### ISSUE TITLE
the different between the deformation field  and warp field

### ISSUE THREAD

**Issue by luckyxiaoqi** [voxelmorph/voxelmorph#195]
in  #84 , you said the different between the deformation field  and warp field, but I can't understand.I can get a deformation field from network, but where I can get warp field. And what is the mean of wrap field.

**Comment by adalca** [comment]
@luckyxiaoqi  can you start by letting us know which model version you're talking about? CVPR2018?

If CVPR2018, the entity that is returned is a displacement field -- at each voxel it tells you where to grab the voxel in the other image to move to this location.
