### ISSUE TITLE
What are the differences between different versions of atals_norm?

### ISSUE THREAD

**Issue by Shiraishi-Hikari** [voxelmorph/voxelmorph#198]
I have two versions of atlas_norm file. One of them was updated at 01-29-2019, sized 6960KB. And the latest updated one is sized 53783KB. It seems that the data of first dimension(160) is inverted.

**Comment by adalca** [comment]
@Shiraishi-Hikari sorry for the delay -- could you tell us where you got it from? Could you share the two files with me? I can't quite understand where they came from.
