### ISSUE TITLE
data loaded error

### ISSUE THREAD

**Issue by rongrongxiangxin** [voxelmorph/voxelmorph#2]
I used the data provided. When I run train.py,  the code X = np.load(vol_names[idx])['vol_data'] in datagenerators.py raise the KeyError: 'vol_data is not a file in the archive'.

**Comment by adalca** [comment]
Hi @rongrongxiangxin , our apologies for missing this -- can you please let us know if you are still having this issue?

**Comment by Alison-brie** [comment]
I am still having this issue. And i am really want to know the sovlution, please !

**Comment by Alison-brie** [comment]
Hi @rongrongxiangxin, I am still having this issue
Duplicate of 2#'
I used the data provided. When I run train.py, the code X = np.load(vol_names[idx])['vol_data'] in datagenerators.py raise the KeyError: 'vol_data is not a file in the archive'.

**Comment by meggiezhou** [comment]
hello，sir  
I used the data provided ,when I run train.py(cvpr2018 version) ,raise TypeError:Expected binary or unicode string, got -1
Can you tell me what ‘s wrong, how can I change it?
Thank you ！

**Comment by adalca** [comment]
can you tell us which python line gives you this issue (copy and paste the entire output)?
thank you

**Comment by meggiezhou** [comment]
Thank you for your reply！
/data/zhoumeiqi/voxelmorph-master(1)/data
2018-11-09 09:46:03.473395: I tensorflow/core/common_runtime/gpu/gpu_device.cc:940] Found device 0 with properties:
name: GeForce GTX TITAN X
major: 5 minor: 2 memoryClockRate (GHz) 1.076
pciBusID 0000:01:00.0
Total memory: 11.92GiB
Free memory: 397.69MiB
2018-11-09 09:46:03.473417: I tensorflow/core/common_runtime/gpu/gpu_device.cc:961] DMA: 0
2018-11-09 09:46:03.473421: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   Y
2018-11-09 09:46:03.473431: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:01:00.0)
Traceback (most recent call last):
  File "/home/zhoumeiqi/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/tensor_util.py", line 458, in make_tensor_proto
    str_values = [compat.as_bytes(x) for x in proto_values]
  File "/home/zhoumeiqi/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/tensor_util.py", line 458, in <listcomp>
    str_values = [compat.as_bytes(x) for x in proto_values]
  File "/home/zhoumeiqi/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/util/compat.py", line 65, in as_bytes
    (bytes_or_text,))
TypeError: Expected binary or unicode string, got -1

**Comment by adalca** [comment]
hm, I'm not sure. Looking online, I find that people were finding similar issues with some older tensorflow distributions (in other models). What tf/keras/py versions do you have?

**Comment by meggiezhou** [comment]
I have tensorflow_gpu-1.0.1,py3.5,keras2.1.2  and cuda 8.0 ls that enough？

**Comment by adalca** [comment]
unfortunately, tensorflow 1.0.1 is nearly 18 months old, and with tensorflow changing so fast it seems that some things changed that affect your bug (at least according to other complaints) -- would you mind upgrading tensorflow and letting us know if this is still an issue?

**Comment by HaiwenYang2010** [comment]
I used the data provided. When I run train_miccai2018.py, the code X = np.load(vol_names[idx])['vol_data'] in datagenerators.py raise the KeyError: 'vol_data is not a file in the archive'.

**Comment by HaiwenYang2010** [comment]
Hi, sir: 
I used the data provided. When I run train_miccai2018.py, the code X = next(train_example_gen)[0]-->X = np.load(vol_names[idx])['vol_data'] in datagenerators.py raise the KeyError: 'vol_data is not a file in the archive'. Can you tell me what's the reason caused this problem? 
Thank you very much.

**Comment by adalca** [comment]
Can you please give the command and parameters you ran? `train_example_gen` tries to read files from a particular datapath you passed in -- what sort of datafiles do you use?

**Comment by jlherraiz** [comment]
I had the same problem.  It is caused by the file /data/atlas_norm.npz located in the same folder as the other npz file. When reading *.npz images in the /data folder, it also tries to read the atlas (which instead of the variable 'vol_data' has 'vol'). Relocating the /data files, and updating the train.py file with the new location of the atlas_norm.npz file, solves this issue.

**Comment by adalca** [comment]
Thanks! We didn't intent for the `data` folder to be passed in to the training, but rather as a folder where we put examples of all the data we used in this project. However, this is clearly misleading -- in the next update we'll try to organize the `data` folder better.

**Comment by ZQYzqyZ** [comment]
When I run the program, the program does not work properly. The reason for the error is as follows
Can you tell me why? Thank you.

Using TensorFlow backend.
usage: train.py [-h] [--atlas_file ATLAS_FILE] [--model {vm1,vm2,vm2double}]
                [--model_dir MODEL_DIR] [--gpu GPU_ID] [--lr LR]
                [--epochs NB_EPOCHS] [--lambda REG_PARAM]
                [--steps_per_epoch STEPS_PER_EPOCH] [--batch_size BATCH_SIZE]
                [--load_model_file LOAD_MODEL_FILE] [--data_loss DATA_LOSS]
                data_dir
train.py: error: the following arguments are required: data_dir

Process finished with exit code 2

**Comment by adalca** [comment]
Based on that error, it sounds like you didn't pass a data directory to the voxelmorph training.
train.py requires a folder full of data to train from.

**Comment by petrovana** [comment]
Hi, 
I am trying to run train_unsupervised_segmentation.py and I keep getting 
X = np.load(datafile)[np_var] (datagenerators.py)
KeyError: 'vol_data is not a file in the archive' 
I've relocated prob_atlas_41_class.npz, and updated my train_unsupervised_segmentation.py with it's new location.
Any idea what I did wrong and how can I solve this?
Thanks!

**Comment by ccpppppp** [comment]
@jlherraiz
 Hello.
I had the same problem.'vol_data is not a file in the archive'.  I created a separate folder（ data1） under voxelmorph-master and put the atlas_norm.npz file in it. Then updating the train.py file with the new location of the atlas_norm.npz file (../data1/atlas_norm.npz). This problem still exists when I run train.py (python train.py ../data  --gpu 0 --model_dir ../models). Running another few times will cause another problem：FileNotFoundError: [Errno 2] No such file or directory: '../data1/atlas_file.npz'

Is there anything wrong with it?
look forward to your reply.Thanks.

**Comment by adalca** [comment]
@ccpppppp can you let me know if this is still an issue?

**Comment by song-cc** [comment]
When I use LPBA40 dataset for training,it show me that "F .\tensorflow/core/util/mkl_util.h:607] Check failed: dims == sizes.size() (5 vs. 4)" . Why it is make this error and how can I solve this problem
