### ISSUE TITLE
Deformation field and determinant of the Jacobian

### ISSUE THREAD

**Issue by fconstance** [voxelmorph/voxelmorph#205]
Hello !

Thank you very much for the great work, it's really nice.
I'm working on PET image registration using the CVPR version on PyTorch.

In output of the network, I get the wrapped images and the corresponding displacement fields. 
Is there any way to also get the deformation field and to compute the determinant of the Jacobian from these deformation fields?

Thank you for your help :)

**Comment by adalca** [comment]
@fconstance 

Sure, but first let me make sure what you mean by 'deformation field' -- Do you mean Id + displacement?

**Comment by fconstance** [comment]
Yes exactly, thanks. If I don't mix up everything, like φ in your paper "VoxelMorph: A Learning Framework for Deformable Medical Image Registration".

**Comment by adalca** [comment]
Can you see if the code at [this comment](https://github.com/voxelmorph/voxelmorph/issues/82#issuecomment-523447568) works?

**Comment by fconstance** [comment]
I'll try soon, thank you for the fast answer !

I also have another subsidiary question. Following what you answered in the other comment, if I want to avoid folding voxels, I should adapt the integration layer from "nrn_layers.VecInt" to Pytorch and add it at the end of the model right?

**Comment by adalca** [comment]
@fconstance yes! I think this is implemented in https://github.com/voxelmorph/voxelmorph/blob/redesign/voxelmorph/torch/layers.py

**Comment by fconstance** [comment]
Sorry I only saw your answer now. I can't read your link, I don't know why.

Concerning my question about the determinant of the Jacobian, it's working perfectly, thank you !

**Comment by adalca** [comment]
@fconstance glad the jacobian is working

Here's the new link:
https://github.com/voxelmorph/voxelmorph/blob/master/voxelmorph/torch/layers.py
(we just did a major refactoring push over the weekend)

**Comment by fconstance** [comment]
I'll try that, thanks
