### ISSUE TITLE
new_locs = new_locs[..., [2,1,0]]

### ISSUE THREAD

**Issue by oldriver-wang** [voxelmorph/voxelmorph#213]
In the implementation of pytorch, 

        if len(shape) == 2:
            new_locs = new_locs.permute(0, 2, 3, 1) 
            new_locs = new_locs[..., [1,0]]
        elif len(shape) == 3:
            new_locs = new_locs.permute(0, 2, 3, 4, 1) 
            new_locs = new_locs[..., [2,1,0]]

Why change the coordinate of the grid?
            _new_locs = new_locs[..., [2,1,0]]_
vol likes B x 1 x D x H x W and new_locs likes B x D x H x W x 3, 
it seems that change the last dim : [z, y, x] to [x, y, z], but I am not sure.
can someone explain this to me?

**Comment by adalca** [comment]
@oldriver-wang  I believe your intuition is right, it's to set the dimensions transform right, but perhaps @balakg or @ahoopes can verify.

**Comment by ahoopes** [comment]
Right, the grid channel order is reversed by that line. I don't really understand the reasoning behind it, but this ordering is the required convention for pytorch's `grid_sample` function (see https://discuss.pytorch.org/t/surprising-convention-for-grid-sample-coordinates/79997).

**Comment by oldriver-wang** [comment]
> Right, the grid channel order is reversed by that line. I don't really understand the reasoning behind it, but this ordering is the required convention for pytorch's grid_sample function (see https://discuss.pytorch.org/t/surprising-convention-for-grid-sample-coordinates/79997).

I got it, thanks!
