### ISSUE TITLE
How to get Jacobian Determinant

### ISSUE THREAD

**Issue by SZUHvern** [voxelmorph/voxelmorph#217]
Hi, adalca,

Thanks for your work!
I want to know how to calculate the jacobian determinant from the spatial transform layer(B,H,W,2)?
I have searched some of your answers, but the link you mentioned seems invalid now:https://www.gitmemory.com/issue/voxelmorph/voxelmorph/205/656473404 .

by the way, I work in tf version.

**Comment by adalca** [comment]
Hi @SZUHvern 

I've pushed some useful code in the new `master` branch in `py/utils.py`. Look for `jacobian_determinant`

Please also see discussions [here](https://github.com/voxelmorph/voxelmorph/issues/82#issuecomment-523447568) .

thanks
