### ISSUE TITLE
Meshgrid/sampling grid in STN 

### ISSUE THREAD

**Issue by Taariq78** [voxelmorph/voxelmorph#218]
Hello.  I'm a bit confused, regarding the need to create a _sampling grid_ that is applied to an image to morph/warp it.  Why is not possible to apply a geometric transform directly to an image; in other words, why go through the trouble of creating a sampling grid?

Any insight would be appreciated.  Thank you

**Comment by adalca** [comment]
@Taariq78 vxm only produces the displacement at every location, rather than a full `transform`. The easiest way we know how to apply this is by creating a meshgrid. If you'd have another easier/more efficient method, we're all ears :)

**Comment by Taariq78** [comment]
Okay I see.  Sorry, I simply wanted to know the reasoning behind it.  Am I correct in saying that the implementation of the meshgrid is what allows for the deformable registration?  If that is the case, would this not be required if you wished to perform registration on images whose source of misalignment are purely linear?

 I'm trying to figure out what exactly allows VM to be capable of deformable registration?

**Comment by Taariq78** [comment]
@adalca Hello again.  I've been reading an [article ](https://kevinzakka.github.io/2017/01/18/stn-part2/) by Kevin Zakka on STNs.  If I am understanding it correctly, the output of the localisation network should be in the shape that corresponds to the type of transform you are trying to account for (so for an 2D affine transform, the output must be in the shape: 2x3).  I have taken a look at his code and he does reshape his transformation to 2x3, which makes sense as he was trying to account for affine misalignment in images.

Now, for VM, in the `SpatialTransformer` layer, there are no signs of you reshaping the output of the localisation network.  Instead, you have the output of the localisation network as the same shape as the input image-pair.  Is this what enables VM to be capable of non-linear (deformable) transforms?

Could you please provide some insight on this, such that I may be better understand it? Thank you.

**Comment by adalca** [comment]
@Taariq78  sorry i missed this. I'm not sure I understand -- the `SpatialTransformer` does take affine matrices, or full fields, so it should work?
