### ISSUE TITLE
Blurring issue in registered images

### ISSUE THREAD

**Issue by TR1109** [voxelmorph/voxelmorph#219]
I'm trying to perform an affine+deformable registration with the voxelmorph network used in CVPR. I'm training the network with a randomly augmented dataset. I'm using 'NCC' loss. The network seems to work ok, however, there is a blurring effect in the registered image. I'm attaching a sample file. Is there any user-defined parameter that can be controlled to reduce the blurring?
![Sample File](https://user-images.githubusercontent.com/71854224/94207598-eabc1b80-fe95-11ea-8761-c0d920edec8b.png)

**Comment by adalca** [comment]
@TR1109 blurring is normal since warping an image is done with linear interpolation. If you'd like to avoid it, perhaps try to apply the warp (e.g. via a `vxm.networks.Transform` with a nearest neighbour interpolation)
