### ISSUE TITLE
How to import my own images for training and export models

### ISSUE THREAD

**Issue by JCFu** [voxelmorph/voxelmorph#22]
Dear author, I'm a beginner in medical image registration and Linux, so I have some questions about voxelmorph.
How could I use some public dataset to train my own model?
How could I use the .nii files to export .npz files?
Please forgive me for some low-level questions.

**Comment by adalca** [comment]
Hi @JCFu ,

It sounds like you have some nii files from a public dataset. For training your own model, we provide train.py and train_miccai.py, to which you will need to provide the path where all your files are. It would be optimal if your data is normalized to `[0, 1]`.

You don't have to transform `.nii` files to `.npz` files -- our datagenerators work with `.nii` as well (see `load_volfile` in `datagenerators.py`. You might need to make a small change in the training file where `train_vol_names` is set, but that should be it.

Good luck!

**Comment by meggiezhou** [comment]
Dear author , I want to know what  the number mean in the label.mat ? can I input pictures  into the network without  any label and without segment pictures

**Comment by adalca** [comment]
Hi @meggiezhou ,

The numbers in the label.mat are FreeSurfer labels that we used for testing. 
You absolutely do not need them for training -- at train time you can just use the original images.

In the future, can you please start a new issue, if the question is unrelated to the current question? Thanks!

**Comment by JCFu** [comment]
Hi @adalca ,

Thanks for your guide.

Now, there are some `.img` files and `.raw` files. I tried to transform these files to `.nii` files with MRIConvert and mricron, but unfortunately it fail.

Could you provide some fine methods to transform these data formats.

Thanks a lot!

**Comment by adalca** [comment]
Hi @JCFu 

We haven't worked with `.img` or `.raw` in a while. There are several tools you can try: 
[FreeSurefer's mri_convert](https://surfer.nmr.mgh.harvard.edu/fswiki/mri_convert) 
[nibabel](https://github.com/nipy/nibabel/issues/673) with a bit of help
[matlab](https://www.mathworks.com/matlabcentral/fileexchange/41594-medical-image-processing-toolbox) has a few packages

Also, manual tools like [3DSlicer](https://www.slicer.org/) should work without a problem.

Hope this helps

**Comment by JCFu** [comment]
Hi @adalca ,

I can do well in training and registering two 3D brain images with your guide.

1. Now, I would like to register two 2D brain images. There are 1000 pairs MR-T1 and T2  brain images in  `.png`  format, and I want to train new 2D model for it. What should I alter for the code files?

2. Further, I transform many ‘.png’ files to one '.npz' file, and put the ‘.npz’ file into folder named input, then I run  'python train.py ~/git/voxelmorph/input  --gpu 0 --model_dir ~/git/voxelmorph/models '. Please help me check whether the steps have mistake?

Thank you so much!

**Comment by adalca** [comment]
1. Since you trained 3D brain images, I'm confused why you would now want to register 2D brains? You should probably use the model to do full 3D brain registration.

2. What are you trying to do? I'm not sure I understand what it means to put 1000 T2 `png` to one `npz` -- what are those 1000 T2 `png` from? 1000 difference subjects?

How did you get the pngs in the first place? I would recommend using the original data, which was probably something like dicom or nii or mgz. It would make the most sense to work with those.

**Comment by JCFu** [comment]
1. I only have a small amount of 3D images, then I try to synthesize more new images. But the quality of synthesized 2D images  is better than 3D. So, I turn to register 2D images.
2.  I try to use these images as train files. The `.png` image are sliced from 3D images and some of them are synthesized. They can be considered different subjects.

Now, I convert every `png` to `nii` and put them into `data` folder which only has 1000 `nii` files, and alter `train_vol_names = glob.glob(os.path.join(data_dir,'*.nii'))` , run 'python train.py ~/git/voxelmorph/data --gpu 0 --model_dir ~/git/voxelmorph/models' . 

Then an error occurred 
> UnboundLocalError: local variable ‘nib’ referenced before assignment.

I think I have mistakes in steps and some operations are missing.

Thanks your patient answer.

**Comment by adalca** [comment]
@JCFu I'm not sure I follow, I would recommend working with just the data you have, as we observed voxelmorph works well even with few images. As to your error, `nib` is referring to the `nibabel` library.
