### ISSUE TITLE
Jacobian determinant 

### ISSUE THREAD

**Issue by Taariq78** [voxelmorph/voxelmorph#222]
Hello

I used the `jacobian_determinant` code you provided to calculate the Jacobian determinant of the flow field.  From my understanding of the Jacobian and its determinant, the output should be a single scalar value.  However, I'm getting an array out(of the size of the flow field).  I suspect it has to do with input shape of the flow field.

Could you provide assistance on where I'm going wrong in utilising this code, please?  Thank you.
![jacobian](https://user-images.githubusercontent.com/70844260/95603179-36ee8a80-0a56-11eb-8456-e90784bf72b5.PNG)

**Comment by adalca** [comment]
It's supposed to be number at each voxel capturing the regularity of the field!
This is why in the papers we show how many voxels have negative jacobian determinants, for example :)
