### ISSUE TITLE
Alternative network architecture

### ISSUE THREAD

**Issue by Taariq78** [voxelmorph/voxelmorph#223]
Hello, thank you for the swift reply, yesterday.

I would like to experiment using VM with other network architectures.  Based on how VM works (specifically how it goes about creating the displacement vector field), is it required that the output of the net must always be of the same dimensions of the original input?

**Comment by adalca** [comment]
@Taariq78 that's the *easiest* way, though I'm sure if your architecture has a different output size you can get it to the right output size of the deformation, either using something like `neurite.layers.Resize()` or a `keras.layers.Dense()` layer.
