### ISSUE TITLE
train.py errors

### ISSUE THREAD

**Issue by ixy40** [voxelmorph/voxelmorph#231]
I am trying to register and get deformation field of two different time points of the GBM cases without using any atlas

[please describe task here]

i am trying to run the train.py file on the data provided and keep getting the same errors. I am new to this field, so cannot comprehend easily.

these are the errors which keep coming back 

Traceback (most recent call last):
  File "train.py", line 104, in <module>
    trg_feats=nfeats
  File "/Users/ipsa/opt/anaconda3/lib/python3.7/site-packages/voxelmorph/tf/modelio.py", line 22, in wrapper
    retval = func(self, *args, **kwargs)
  File "/Users/ipsa/opt/anaconda3/lib/python3.7/site-packages/voxelmorph/tf/networks.py", line 93, in __init__
    half_res=unet_half_res
  File "/Users/ipsa/opt/anaconda3/lib/python3.7/site-packages/voxelmorph/tf/networks.py", line 836, in __init__
    last = _upsample_block(last, enc_layers.pop(), factor=max_pool[real_level], name=name)
  File "/Users/ipsa/opt/anaconda3/lib/python3.7/site-packages/voxelmorph/tf/networks.py", line 880, in _upsample_block
    upsampled = UpSampling(size=(factor,) * ndims, name=name)(x)
  File "/Users/ipsa/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/layers/convolutional.py", line 2464, in __init__
    self.size = int(size)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'tuple'

**Comment by adalca** [comment]
Can you please tell us the command you ran, and what tensorflow you are running?

**Comment by ixy40** [comment]
in my terminal i did **python3.7 train.py /data/path --atlas  --model-dir**
i also dont understand the errors i get for __init.py files
i am new to python so i might be missing out on some of the basics.

for example:    
 from . import utils
ImportError: attempted relative import with no known parent package

my idea is to use register.py file but before that i would use the train.py file to train the data and generate a model.
are these the correct steps?

**Comment by adalca** [comment]
calling `train.py` in that manner required arguments for the options you list (e.g. `--atlas` requires that you provide an atlas, and `--model-dir` requires that you provide a folder to which to dump model files). 

When you get errors in __init__ files, how do you get those errors, when running train.py? Also, is voxelmorph on your PYTHONPATH?

**Comment by ixy40** [comment]
version of tensorflow  - 2.3.1
i have given those input arguments for atlas and model dir
voxelmorph is in my python path
also the errors while using  train.py are as follows:

1. File "train.py", line 67, in <module>
    atlas = vxm.py.utils.load_volfile(args.atlas, np_var='vol', add_batch_axis=True, add_feat_axis=add_feat_axis)

 2. File "/Users/ipsa/opt/anaconda3/lib/python3.7/site-packages/voxelmorp**h/py/utils.py**", line 58, in load_volfile
    vol = next(iter(npz.values())) if len(npz.keys()) == 1 else npz[np_var]

 3. File "/Users/ipsa/opt/anaconda3/lib/python3.7/site-packages/numpy/lib/npyio.py", line 266, in __getitem__
    raise KeyError("%s is not a file in the archive" % key)
**KeyError: 'vol is not a file in the archive'**

**Comment by adalca** [comment]
Hello @ixy40 

if you provided those input arguments, then can you please provide the actual line you ran? Above you wrote:
```
python3.7 train.py /data/path --atlas --model-dir
```
which would certainly give an error

Can you tell us what type of volume files you have?

**Comment by ixy40** [comment]
i dont have volume files
this the command line argument:

python3.7 /Users/ipsa/Downloads/voxelmorph-master/ivy_gap_data --atlas /Users/ipsa/Downloads/voxelmorph-master/ivy_gap_data/baseline.npz --model-dir /Users/ipsa/Downloads/voxelmorph-master/first_model

**Comment by adalca** [comment]
by volume files I mean your data
What is in /Users/ipsa/Downloads/voxelmorph-master/ivy_gap_data/baseline.npz  ?
and what sort of files are present in /Users/ipsa/Downloads/voxelmorph-master/ivy_gap_data?

The error you're showing us in the last message has to do with the volumes being loaded

**Comment by ixy40** [comment]
oh got it , so these files are 3D MRI BRAIN scans containing Glioblastoma. i just have data for 3 patients right now.
my baseline scan is the atlas image or more like fixed image and my two timepoints are the ones i want to register to this baseline scan

**Comment by ixy40** [comment]
i had to convert these scans from .nii to .npz format, it would not take .nii format for me

**Comment by adalca** [comment]
nii should work but if you use npz, you need to make sure you put the volume in a `vol` variable:
```np.savez_compressed('filename.npz', vol=myvolume)```

**Comment by ixy40** [comment]
thank you for this, the 'vol' error got fixed.
Now my input image dimension is (126,256,256) and ndim for the same is 3 but the error which still persists is:

 File "/Users/ipsa/opt/anaconda3/lib/python3.7/site-packages/voxelmorph/tf/networks.py", line 76, in __init__
    assert ndims in [1, 2, 3], 'ndims should be one of 1, 2, or 3. found: %d' % ndims
AssertionError: ndims should be one of 1, 2, or 3. found: 0

**Comment by ixy40** [comment]
i actually overcame the above issue, but now as im using .nii files i have an error popping:

  **TypeError: Input 'y' of 'Sub' Op has type float32 that does not match type int16 of argument 'x'.**

**Comment by adalca** [comment]
Seems like your data is int16 -- you could change your files to store float16, or add a line casting it in our loader function here: https://github.com/voxelmorph/voxelmorph/blob/2ce0fc197174ef35debc373dcb6b111632441690/voxelmorph/py/utils.py#L31

e.g. `vol = vol.astype('float16')` or similar

**Comment by ixy40** [comment]
okay let me check this !
i also have a question regarding model files, when going through the tutorial I see brain_3d.h5 as the model file. Do we have these where I can directly use for my dataset, just to check if it works for it or will I have to train it on my system ?

**Comment by ixy40** [comment]
in subj1.npz file given in the tutorial, when i load it in spyder with type float64, it shows dimension (1,160,192,224,41,1)
can you tell what 41,1 stand for ?

**Comment by adalca** [comment]
where is this in the tutorial?
I just did 

```
# download MRI tutorial data
!wget https://surfer.nmr.mgh.harvard.edu/pub/data/voxelmorph/tutorial_data.tar.gz -O data.tar.gz
!tar -xzvf data.tar.gz
np.load('subj1.npz')['seg'].shape
```
and got  
`[160,192,224]`
