### ISSUE TITLE
Applying a saved transformation back onto an image 

### ISSUE THREAD

**Issue by rohandivate** [voxelmorph/voxelmorph#233]
I am using the voxelmorph legacy branch and I used the register.py script to register two images and save the deformation field found from the registration. For my use of voxelmorph, I need to apply some change to the deformation field and apply the deformation field back onto the moving image. I am having difficulty with applying the saved deformation field back onto an image. I tried looking at the registration code and using the `SpatialTransformer` to accomplish this. 
I have tried using this code:

`y = nrn_layers.SpatialTransformer(interp_method='linear', indexing='ij')([moving_img, warp])`

where `moving_img` and `warp` are numpy images corresponding to the moving image and the warp transformation found from the registration. 

However, this gives me an error saying:
All inputs to the layer should be tensors.

I have tried making both the `moving_img` and `warp` into tensors:

`y = nrn_layers.SpatialTransformer(interp_method='linear', indexing='ij')([tf.convert_to_tensor(moving, np.float32), tf.convert_to_tensor(warp, np.float32)])`

This gives me this error:
Exception: Offset flow field size expected: 1, found: 3

Is there a way I can apply the warp transformation from register.py back onto an image in voxelmorph?
Thanks

**Comment by adalca** [comment]
@rohandivate 

In general I would strongly recommend you use the `master` branch since it has cleaner code to do this, but until then please see the answer to this [similar question here](https://github.com/voxelmorph/voxelmorph/issues/194#issuecomment-633762042).
