### ISSUE TITLE
Just a small question

### ISSUE THREAD

**Issue by mariakesa** [voxelmorph/voxelmorph#234]
Hello:-)

I am planning to use voxelmorph to morph some cellular level zebrafish whole-brain imaging data. I was just wondering, is the PyTorch implementation ready for use? The main page said that parts of the pipeline are still in development.

All the best,
Maria

**Comment by adalca** [comment]
Hi @mariakesa 

Yes, I believe it's fully usable, it's just that we have less developed for the `pytorch` version simply because our initial development was focused heavily in `tf`. Please give it a try and let us know if you have issues!
