### ISSUE TITLE
Facing error when using training command

### ISSUE THREAD

**Issue by Rasoul20sh** [voxelmorph/voxelmorph#235]
Hi and thanks for sharing your work,
I am trying to get started with VoxelMorph and I am facing error for the training phase.
The utilized command is:
`./scripts/tf/train.py data --model-dir models/output --gpu 0.`

And the error is:
`OOM when allocating tensor with shape [1 160 192 224 48] and type float on /joblocalhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc`

details:
I examined both 1050Ti and 1060Ti, and the error raised for both configurations.
Furthermore, I do not know what exactly should be in the data folder. Maybe the data is in the wrong place.
So my questions are:
1- Is there any minimum GPU configuration for running a training command?
2_ What must be in the data folder for the training phase?

Regards,
Rasoul

**Comment by adalca** [comment]
Hi @Rasoul20sh 

It seems like you're running out of memory. The amount of memory required depends on a bunch of things -- your volume sizes, the model you choose, etc. For the model and volumes we worked with, we needed about 10Gb. You could try smaller images or a smaller model (fewer features per conv layer).

Right now the data has to in npz files in the training folder, but you can easily change this by basically changing the line in `train.py`: https://github.com/voxelmorph/voxelmorph/blob/2ce0fc197174ef35debc373dcb6b111632441690/scripts/tf/train.py#L58

I believe our data loaders work with npz files or nifti files or mgz files etc.
