### ISSUE TITLE
How to train 3D dataset?

### ISSUE THREAD

**Issue by yoonguusong** [voxelmorph/voxelmorph#237]
**Task** (what are you trying to do/register?)

In the tutorial, for 3d registration, there is a only pre-trained parameter.
I want to train the 3D model.
How could I make the dataset?

When I see your 2D registration on MNIST which is (28,28) size, you train with 5421 data.
so data size to go on the 3D model is (5428,28,28).

Through this, I expected to run the code 3D dataset into 4D array.
However, as I mentioned before, for the 3D registration, the only pre-trained parameter is given.
Therefore I wonder how to run the 3D registration code on voxelmorph.

Let say if I have 150 data with (100,200,300) size,
1) Should I make (150, 100, 200, 300) array and turn the code?

2) In addition, If I want to train the 3D registration, should I use 3D Unet instead of 2D Unet like architecture?
Could you please explain this?

Appreciate your passionate work.
Thank you.

**Comment by adalca** [comment]
@yoonguusong  you don't need to load them into memory. Have you looked at the instructions at https://github.com/voxelmorph/voxelmorph#training ?

**Comment by yoonguusong** [comment]
Oh, I just want to run the code with python Console, not in the terminal.
That's why I wonder how to run the 3D image using a tutorial-like code.

**Comment by adalca** [comment]
The code in https://github.com/voxelmorph/voxelmorph/blob/master/scripts/tf/train.py should help you

basically you have to set up a generator via `generator = vxm.generators.scan_to_scan`, instantiating the model, compile it and fit it. All the steps should be in that file, you can copy them to a console.

**Comment by yoonguusong** [comment]
Thank you
