### ISSUE TITLE
2D MI loss with batch dimension

### ISSUE THREAD

**Issue by lesterlitch** [voxelmorph/voxelmorph#239]
Hi there,

I wanted to use the local MI loss in the 2D scenario, but the class seems to expect 3D dimensions only. 

I adapted the class to 2D, and it seems to be working nicely, but I also needed to add a batch dimension, if I am understanding the experimental function correctly. 

Would it be helpful to integrate the batch dim, and the 2D MI scenario into voxelmorph as a pull request?

**Comment by adalca** [comment]
Hi @lesterlitch 

I appreciate the offer, but we've been coincidentally working on an overarching MI loss as part of our SynthMorph work (see the most recent version here if you want: https://github.com/adalca/neurite/blob/9379283241668005171388804bcafe9970d5fd7e/neurite/tf/metrics.py#L27, although this one doesn't have patches pushed). If your adaptation works for you, that's great, though! What are you registering?

**Comment by lesterlitch** [comment]
Ok nice, that looks like a cool project! I'm registering mammograms.

**Comment by konglingyu812** [comment]
> 好的，这看起来是个很酷的项目！我正在登记乳房 X 光照片。
Hello, I'm doing T1 and t2mri image registration of breast. Can I use the MI loss function of 2D image for reference? My email is konglingyu812@163.com

**Comment by adalca** [comment]
@konglingyu812 yes you should be able to use it. We're not emailing it out anymore, it's implemented in [neurite](https://github.com/adalca/neurite/blob/dev/neurite/tf/metrics.py) now
