### ISSUE TITLE
Questions about groundtruth mentioned in paper

### ISSUE THREAD

**Issue by Blcony** [voxelmorph/voxelmorph#24]
Thanks for your wonderful work and code!
You have implemented this method on many dataset, such as ADNI, OASIS, ABIDE and so on, and I know these dataset can be obtained in public websites. But I want to know if you have released the groundtruth(anatomical structure) about registration related to these dataset?
If I want to compare my method's results with yours, what should I do?
I wish that you can solve my questions, thank you very much!

**Comment by adalca** [comment]
Thank you for your interest in VoxelMorph! We measure the accuracy of our results using segmentations. 

Given that we can't release the data ourselves and we did , we didn't release segmentations from these processed data either (it didn't seem to make sense) -- except for one subject (see test_seg.npz) and the atlas, which should give you an ability to make sure the algorithms work reasonably. Beyond this, the best thing to do is use your data.

**Comment by hassaanmahmood** [comment]
Hi
   What can be the other methods to check the registration performance if we do not have labels to compute dice score? 
do you have any suggestions please.
thanks

**Comment by adalca** [comment]
- use some external segmentation tool to create labels for a few subjects (we used FreeSurfer)
- many researchers put small landmarks on a couple of subjects and compare how far away those landmarks are after registration
- visualize the deformed scan compared to the second scan, but you have to be very careful as a under-regularized deformation will look 'better aligned'. So you have to visualize both the warped scan **and the deformation** itself
