### ISSUE TITLE
We ran into some problems working with our own data sets using Freesurfer

### ISSUE THREAD

**Issue by luoyi1hao** [voxelmorph/voxelmorph#240]
We used the following command (mri_convert norm.mgz --apply_transform talairach.xfm norm_affine.nii.mgz)
But the size of the image was reduced to 172, 220, 156. And it's going to rotate.

**Comment by adalca** [comment]
@luoyi1hao I'm sorry, I'm not sure I understand the post, but it sounds like an issue for the https://github.com/freesurfer/freesurfer/issues

@ahoopes might be able to comment. Again, it would help us if we had more context

**Comment by luoyi1hao** [comment]
thanks for your reply. It seems that we encountered problems in data preprocessing, which made the affine dice coefficient we obtained particularly low. When I perform affine normalization to Talairach space for the obtained norm.mgz, the problem arises as we mentioned before. This seems to be the same as question 63. But I couldn't understand the final answer. I'd like to know the details with affine normalization to Talairach space.
![image](https://user-images.githubusercontent.com/49618455/100350260-8f88df80-3024-11eb-9991-9f1b64a71bf1.png)

**Comment by luoyi1hao** [comment]
This is the instruction that we used: 
mri_convert.bin --apply_transform ./OAS1_0001_MR1/mri/transforms/talairach.xfm./OAS1_0001_MR1/mri/norm.mgz ./OAS1_0001_MR1/mri/processed_norm.nii.gz

**Comment by ahoopes** [comment]
When using a subject's `xfm` for talairach affine alignment, use this command:

`mri_convert subj/mri/norm.mgz subj/mri/norm_talairach.mgz --apply_transform subj/mri/transforms/talairach.xfm --devolvexfm subj -ic 0 0 0`

This properly accounts for the case where the input volume does not have its coordinate center at (0, 0, 0).

**Comment by adalca** [comment]
@luoyi1hao I am closing this, let us know if @ahoopes 's answer didn't work.
