### ISSUE TITLE
About the boxplot in MIA paper.

### ISSUE THREAD

**Issue by OldDriverJinx** [voxelmorph/voxelmorph#251]
Hello,
     Your experiment is perfect in MIA papers,and the boxplot in your paper is very cool.Would you mind share me which toolkit can draw this boxplot ? Thanks~

**Comment by OldDriverJinx** [comment]
![image](https://user-images.githubusercontent.com/45961825/103458080-a9ae8f80-4d3f-11eb-8b91-ff533837c639.png)

**Comment by adalca** [comment]
Hi @OldDriverJinx 

Here are the utils we used, shared with previous permission by the awesome [@xamyshao](https://github.com/xamyzhao) https://gist.github.com/adalca/4ad9a02b6ca7325dcdfc519239ca71c8 .  I believe the idea is to use format_data_for_boxplot to get the data in the right shape, and then make_boxplot to actually plot it.

**Comment by OldDriverJinx** [comment]
> Hi @OldDriverJinx
> 
> Here are the utils we used, shared with previous permission by the awesome [@xamyshao](https://github.com/xamyzhao) https://gist.github.com/adalca/4ad9a02b6ca7325dcdfc519239ca71c8 . I believe the idea is to use format_data_for_boxplot to get the data in the right shape, and then make_boxplot to actually plot it.

**Comment by OldDriverJinx** [comment]
> Hi @OldDriverJinx
> 
> Here are the utils we used, shared with previous permission by the awesome [@xamyshao](https://github.com/xamyzhao) https://gist.github.com/adalca/4ad9a02b6ca7325dcdfc519239ca71c8 . I believe the idea is to use format_data_for_boxplot to get the data in the right shape, and then make_boxplot to actually plot it.

Thank you very much!I will try it!
