### ISSUE TITLE
What is the data splitting for train/val/test?

### ISSUE THREAD

**Issue by CaptainWilliam** [voxelmorph/voxelmorph#26]
Dear Author:

Could you please share the data splitting so I can re-implement the result in your paper? 

What are the 7329/250/250 images used for train/val/test?

**Comment by adalca** [comment]
Hi @CaptainWilliam,
I'm not 100% sure what you mean, but we split our dataset randomly by subject in that ratio -- that is we used 7000+ images to train, 250 to validate while we did model development, and 250 as the test set for the paper. I believe any way you do this splitting will lead to comparable results to what we have in the paper.
