### ISSUE TITLE
Applying flow to coordinates

### ISSUE THREAD

**Issue by mariakesa** [voxelmorph/voxelmorph#264]
Hello:-)

Is it possible to use VoxelMorph to find the new coordinates for keypoints in an image (for example pre-marked landmarks or cell coordinates in calcium imaging experiments) after morphing? AntsPy has this. 

If it's not possible, would you be interested in me trying to implement it? With just some tips and hints?

Thank you:-)
Maria

**Comment by adalca** [comment]
Hi @mariakesa 

Sorry for the delay.  Yes, it is possible (in fact we use it in the MedIA 2019 paper to warp surface points!
In short, you have to take the inverse of the deformation field, and apply this to the points.

Can you tell us which version of voxelmorph you are using? Once you tell us that, we'll be able to help.

The summary is this: If you run voxelmorph to warp moving image B to fixed image A, then you can just apply that warp field to warp any given coordinate in image A back to image B (note the flip in direction). We have some utilities written in the repository, but if you tell us a bit more of your problem we can help more specifically.

Thanks!

**Comment by mariakesa** [comment]
Thank you so much:-)

I'm working on larval zebrafish because they're translucent and you can do calcium imaging to record the neural activity patterns in the entire brain.

So I'm making a little app in Vispy to apply morphing to an experimental fish image stack and a 3D fish image stack from an atlas https://engertlab.fas.harvard.edu/Z-Brain/ The GUI allows you to mark corresponding landmarks in the experimental fish and atlas fish. I would like to have a button to run Voxelmorph, a visualization of the morphed image and displaying the warped landmarks.

Thanks again:-)

Maria

**Comment by adalca** [comment]
I see, cool!
did you plan to train voxlemoprh on those images to that atlas yourself? I would encourage you to train a standard voxelmorph model with diffeomorphism. This will enable you to get the warp in both directions, allowing you to warp these landmarks easily. 

We can create a simple script to warp some annotations with a given deformation field if you wish, but It might be useful to see some images and understand if you plan to train your own model?

**Comment by mariakesa** [comment]
Hey, sorry for the late reply. Stuff came up. Let me try to do the training and I will get back to you!

**Comment by adalca** [comment]
sounds good. let us know how it goes!

**Comment by adalca** [comment]
@mariakesa  in the meanwhile i wrote this quick colab to show how to work with annotations: 
https://colab.research.google.com/drive/1V0CutSIfmtgDJg1XIkEnGteJuw0u7qT-?usp=sharing

**Comment by jayurbain** [comment]
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-7-526b0a7ee379> in <module>()
     14 margin = 10
     15 nb_annotations = 5
---> 16 annotations = [np.random.uniform(margin, f - margin, nb_annotations) for f in x1.shape]
     17 annotations = np.stack(annotations, 1)

NameError: name 'x1' is not defined

**Comment by adalca** [comment]
@jayurbain 

Thanks. Should be fixed now!
