### ISSUE TITLE
Algorithm used to calculate non rigid deformation

### ISSUE THREAD

**Issue by prameshgautam** [voxelmorph/voxelmorph#267]
I was going through the paper of Voxelmorph and would like to know the non-rigid transformation used. I would like to know which algorithm is used to calculate the deformation field. I might be missing the details from the paper.

Thank you in advance

**Comment by adalca** [comment]
@prameshgautam 

I'm not sure I understand your question -- VoxelMorph itself is a method to output the deformation field for two images (an unsupervised neural network). Did you have a more specific question about part of the method?

**Comment by prameshgautam** [comment]
@adalca Thank you for the response. I think I was not clear in my question. I wanted to know the method used for image transformation and looks like Stationary velocity field is used for diffeomorphic transformation. Please correct me if I am wrong.

Also, I have a situation where the inverse transformation needs to be computed. Is this already available in voxelmorph? I am trying to use the PyTorch version.

**Comment by adalca** [comment]
Voxelmorph is a general purpose framework for learning to output deformations from data. This idea can be used with a varity of transformation types. Our library supposets a few, including standard deformation fields and diffeomorhisms through velocity fields. 

If you need inverses, you should definitely use diffeomorphisms. The pytorch implementation includes a `neg_flow` variable that maintains the inverse deformation field: https://github.com/voxelmorph/voxelmorph/blob/6a9522810455e8e6333beebf133398e2f1a2fbc8/voxelmorph/torch/networks.py#L199

**Comment by prameshgautam** [comment]
Thank you :). I have one more question regarding running the training script. The atlas.npz file contains only **vol** and **seg** parameters. **vol** seems to refer to moving image and **seg** to auxiliary information in case of semi-supervised learning. I couldn't figure out how the fixed image is passed during training.

**Comment by adalca** [comment]
@prameshgautam please see the instructions at https://github.com/voxelmorph/voxelmorph#training . Specifically, 

> you have a directory containing training data files in npz (numpy) format. It's assumed that each npz file in your data folder has a vol parameter, which points to the numpy image data to be registered, [...]. It's also assumed that the shape of all image data in a directory is consistent.

We actually support many more formats, @ahoopes  can comment on that, but essentially having a folder with npz files is the easiest way to start.

**Comment by ahoopes** [comment]
Right, at the moment npz is just the default format in the example `train.py` scripts, but the internal I/O utils also support npy, nifti, and mgh/mgz files. The loader assumes by default that the npz image data is stored under the 'vol' key, and the example training script just searches for any npz files in the `datadir` path provided on the command line. So, you could always customize your list of training files by modifying:

https://github.com/voxelmorph/voxelmorph/blob/6a9522810455e8e6333beebf133398e2f1a2fbc8/scripts/torch/train.py#L61

**Comment by prameshgautam** [comment]
@ahoopes my question was regarding the fixed image rather than the image format. Since **vol** refers to moving image and **seg** refers to information for semi-supervised learning, how is the moving image passed to training?

**Comment by adalca** [comment]
if you're registering scan to atlas, then our `train.py` sets the atlas as the fixed image and the scans in the `datadir` are treated as the moving images.

If your files are npz files with the volume stored in the `vol` variable, these will be read by the generator and passed to the model as moving images.

I'm not sure I understand your question beyond this?

**Comment by prameshgautam** [comment]
@adalca my use case is of scan to scan registration and I would like to pass two volumes(moving and fixed) to the network. I am able to figure out the moving image for scan to scan registration. My question is how to pass the scan for the fixed image. I can change the code of reading the image to read the moving and fixed image to pass to the network. But I wanted to understand the existing code for efficiency as it seems efficient than the loader I'm trying to implement. I hope I am able to clarify my question. Thank you for your help.

**Comment by adalca** [comment]
our code defaults to scan-to-scan if you don't supply an atlas. https://github.com/voxelmorph/voxelmorph/blob/master/scripts/tf/train.py#L65

**Comment by prameshgautam** [comment]
@adalca got it thank you. I tried running training code with just one image in datadir with **vol** parameter in npz file.
I run the script using command `python scripts/torch/train.py data-dir/`. Same image is passed as fixed and moving image to the model in [https://github.com/voxelmorph/voxelmorph/blob/master/scripts/torch/train.py#L158](https://github.com/voxelmorph/voxelmorph/blob/master/scripts/torch/train.py#L158).

My question is how to arrange fixed and moving image for scan-to-scan registration. What is the correct way to pass moving and fixed image pair for training? I cannot find that info in README.

**Comment by adalca** [comment]
The current setup will randomly grab images from the folder as fixed and moving at each iteration. If you'd like to be more specific than that, I think you need to modify the generators. @ahoopes can verify.

**Comment by ahoopes** [comment]
Yes, the default generators are configured to pick, at each training step, two random files (representing moving and fixed images) from the training files available in the datadir, so if there's only one file, the model will just be learning to register the same image to itself over and over again. If you want to get specific about what exactly will be used as moving and fixed images at each training iteration, you'll have to write your own data generator.

**Comment by prameshgautam** [comment]
got it thank you :)
