### ISSUE TITLE
Registration for colored images

### ISSUE THREAD

**Issue by saramsv** [voxelmorph/voxelmorph#269]
Hi, thank you so much for sharing your great work!
The tutorial is very useful to understand the process. I am interested in applying your registration techniques to my image dataset and was wondering if it is possible to make the registration work with images with 3 RGB channels. In the tutorial, the digits data are used as 2D images 32*32. 
Thank you!

**Comment by adalca** [comment]
@saramsv, I think you can just use voxelmorph with multiple features, so you can use the 3 channels as 3 features (see `src_feats` parameter to VxmDense).
