### ISSUE TITLE
about dataset

### ISSUE THREAD

**Issue by ahuczp** [voxelmorph/voxelmorph#27]
Hi,when I download the ADNI (1,2,3,go) dataset,there are more than 10000 MRI images.But in your paper there are total 7829 datas.So which ADNI dataset do you use?  And how to generator the Atlas image? Thank you very much.

**Comment by adalca** [comment]
Hello. We used a random subset of ADNI 1,2,go to train. See #3 and #28 for a processing discussion. The atlas image is available on the [data](https://github.com/voxelmorph/voxelmorph/tree/master/data) folder.
