### ISSUE TITLE
Pretrained model tf version available? 

### ISSUE THREAD

**Issue by XXZhou25** [voxelmorph/voxelmorph#271]
Hi,

Thanks for your awesome VoxelMorph work!
I was wondering if there is any pretrained model(tf version) could be provided for us to play with?

Thank you so much!

**Comment by adalca** [comment]
Hi @XXZhou25,

Sure, here is for example a model for T1 data processed as we did in the paper: https://surfer.nmr.mgh.harvard.edu/ftp/data/voxelmorph/models/vxm_dense_brain_T1_3D_mse.h5

We also have SynthMorph models that should work more broadly.

Can you tell us a bit about your data?

**Comment by XXZhou25** [comment]
> Hi @XXZhou25,
> 
> Sure, here is for example a model for T1 data processed as we did in the paper: https://surfer.nmr.mgh.harvard.edu/ftp/data/voxelmorph/models/vxm_dense_brain_T1_3D_mse.h5
> 
> We also have SynthMorph models that should work more broadly.
> 
> Can you tell us a bit about your data?

Hi @adalca ,
Thank you so much! It helps a lot.
I am a starter of VoxelMorph, and I want to do a small test on the pretrained model. 
I am going to use a pair of lung CT.

**Comment by adalca** [comment]
Sounds good. Obviously that model is trained on brains so it won't work directly on lung CT, but it might help you get started. 
See also the [tutorials](http://tutorial.voxelmorph.net/) if you need to learn how it all works.

**Comment by XXZhou25** [comment]
> Sounds good. Obviously that model is trained on brains so it won't work directly on lung CT, but it might help you get started.
> See also the [tutorials](http://tutorial.voxelmorph.net/) if you need to learn how it all works when playing with these models

Hi @adalca , thank you so much!! I will check it out!

**Comment by XXZhou25** [comment]
@adalca Hi I am so sorry, I 'closed' it by accident.
