### ISSUE TITLE
Issues when run train_cond_template.py

### ISSUE THREAD

**Issue by Fjr9516** [voxelmorph/voxelmorph#273]
**Task** (what are you trying to do/register?)
Hi! I am trying to train a conditional template vxm model on the MNIST dataset. I only have one attribute, namely, 0-9 classes. But the generated templates look very strange. As I understand, the trained model suppose to generate ten templates(0-9 digital images). 

**What have you tried**
First, I set:steps_per_epoch=100, since it is given in the demo. And the epoch is set to 1500. The loss weights are set to  γ = 0:01, λd = 0:001, λa = 0:01, and σ = 1, which is given in paper. When the model is trained, I first build the model by model = vxm.networks.ConditionalTemplateCreation(), then load weights by: model.load_weights('1500.h'). Then I extract the model between the input and atlas layer. I input 0~9 into this network and visualize the output. The output is very strange; since only 0 is correctly generated, all others just look like number 3(But there is a little difference between them).

Then I found that steps_per_epoch should be set to x_train.shape[0] // args.batch_size. So I retrain the model and use tensorboard to visualize the output of layer 'atlas', but the same problem exsits.

Could you tell me what I did wrong? I am so confused.

Here is the outputs of layers 'atlas_gen' and 'atlas' (from 0-9)
![image](https://user-images.githubusercontent.com/31833999/110079523-8036d200-7d89-11eb-88ec-728fa9c36502.png)

**Comment by adalca** [comment]
Hi @Fjr9516,

It seems like you're working with the MNIST dataset, so perhaps the best way to answer your question is with a demo on that. I've added a quick demo at the end of our atlas tutorial at: https://colab.research.google.com/drive/1SkQbrWTQHpQFrG4J2WoBgGZC9yAzUas2?usp=sharing

It should do what you want, and with that maybe help clarify any issues. Can you let me know if this helps?

**Comment by Fjr9516** [comment]
Hi!
It helps! Thank you very much for your help!
I used class labels instead of the one-hot format of labels as the attribute, which caused my bad results.

**Comment by adalca** [comment]
@Fjr9516 okay, glad it helped!
