### ISSUE TITLE
Request For Trained Model

### ISSUE THREAD

**Issue by LeeXW-code** [voxelmorph/voxelmorph#279]
I am a senior student from China,learning about image registration currently.
Short of experienced ability,I wanna use a trained model.
Could u plz share me a trained model?
Thank u,
sincerely

**Comment by adalca** [comment]
@LeeXW-code we have a varity of trained models. Can you let us know what you're registering?

**Comment by LeeXW-code** [comment]
> @LeeXW-code we have a variety of trained models. Can you let us know what you're registering?

I learned about Lung CT image registration（two dimensional）,sir.

**Comment by adalca** [comment]
do you have a dataset?

We don't have a pre-trained lung model. you could try a [pre-trained brain model](https://surfer.nmr.mgh.harvard.edu/ftp/data/voxelmorph/models/vxm_dense_brain_T1_3D_mse.h5) and fine-tune from that, but I'm not sure it would be that different compared to training from scratch.

**Comment by LeeXW-code** [comment]
> do you have a dataset?
> 
> We don't have a pre-trained lung model. you could try a [pre-trained brain model](https://surfer.nmr.mgh.harvard.edu/ftp/data/voxelmorph/models/vxm_dense_brain_T1_3D_mse.h5) and fine-tune from that, but I'm not sure it would be that different compared to training from scratch.

THANK YOU,sir!!! I'll try it now(I can't believe that u can reply to me so fast )

**Comment by adalca** [comment]
We do our best. I'm going to close the ticket but you can continue the conversation on it after you play with the models.
