### ISSUE TITLE
How to prepare the training data

### ISSUE THREAD

**Issue by songpeilun123** [voxelmorph/voxelmorph#28]
Hi，I have read your paper and want to run this code with my own data，so could you please tell me the general steps about how to prepare the training data，now I only have some nifti format T1-MRI data ，Do I need to follow the steps in paper strictly? such as resample,preprocess by freesurfer，crop to 160*192*224 etc.

**Comment by adalca** [comment]
Hello @songpeilun123 

See #3 for processing detail. Depending on your data, I don't believe all of these are necessary, especially if you use NCC as a cost function. I think the most important aspect is affine registration (see #3 for detail) and some intensity normalization. The crop is not even necessary -- we mostly use it to save memory.

**Comment by qiheihelan** [comment]
@songpeilun123
 Hello. 
How do you encounter the following two situations when you run the program? 1. run test_miccai2018.py,  error: no such file or directory:'...path/here//test_examples.txt'  
2. run test.py ,  error:  File"test.py",line83,in<module>     test(sys.argv[1], sys.argv[2])    list index out of range. Can you give me some advice?
Thanks.

**Comment by adalca** [comment]
@qiheihelan please see my answer to #80 that should help.
