### ISSUE TITLE
How much GPU memory needs to be used to train the conditional template model?

### ISSUE THREAD

**Issue by Fjr9516** [voxelmorph/voxelmorph#282]
**Task** (what are you trying to do/register?)
I'm trying to train a model based on your code "train_cond_template.py". I downloaded your dataset from here: https://github.com/adalca/medical-datasets/blob/master/neurite-oasis.md. 314 data were used for training and 100 data were used for testing. However, when I train the model, it always shows the ’Resource exhausted: OOM’ error.

**What have you tried**
First, I tried to reduce the batch size to 1, but OOM still exists. 
Then, I tried to use distributed training, using two GPUs for training. (Batch size should be a multiple of the number of GPUs, so I just set it to the number of GPUs). But OOM still exists.

I used two GPUs: GeForce GTX 1080 Ti, 11GB,  computeCapability: 6.1

Can you tell me what GPUs you used to successfully train the model? Or do you have any suggestions for me to train this model on my machine?

**Comment by Fjr9516** [comment]
Hi! Thanks for your reply. 
I used aligned images, size of 160*192*224. I set batch size as 1 to train the model, I wonder if you set the batch size to 1 when you train your model on 12Gb GPU?
I will try a smaller architecture, thx a lot!

**Comment by adalca** [comment]
Yup we had a batch size of 1

**Comment by Fjr9516** [comment]
Thx！
