### ISSUE TITLE
where can I find the code of hypermorph?

### ISSUE THREAD

**Issue by daxuemi** [voxelmorph/voxelmorph#290]
hello professor! thanks for your project of voxelmorph,its really works.I saw your tweet from twitter. It seems that you have opened up the code of your latest work hypermorph, but I havent found it in this project. Would you please tell me how to get the code of hypermorph? Thank you!

**Comment by adalca** [comment]
Hi @daxuemi, Thanks for your interest.

HyperMorph code is in the development branch [dev](https://github.com/voxelmorph/voxelmorph/tree/dev/) -- see the training script `train_hypermorph.py` and that should get you started

**Comment by daxuemi** [comment]
Thank you very much for your reply!
