### ISSUE TITLE
How to compute the points after deformation

### ISSUE THREAD

**Issue by prameshgautam** [voxelmorph/voxelmorph#291]
I have been using Voxelmorph to set up a registration project and have been able to run the training. I need to find the points to which the landmarks are transformed to after deformation. If the landmark is located at position _(x, y, z)_ in image **I** and the image is transformed to image **I'** after deformation, I need to compute the location in **I'** to which _(x, y,z)_ is mapped to. I guess **neg_flow** can be used but am not exactly sure how the location can be computed efficiently. Any help is highly appreciated. 

Thanks!

**Comment by adalca** [comment]
@prameshgautam 

We have a small [tutorial](https://colab.research.google.com/drive/1V0CutSIfmtgDJg1XIkEnGteJuw0u7qT-#scrollTo=h1KXYz-Nauwn) for this -- it's for affine transformations, but the idea should be the same. You're right, you can use the negative flow together with our tool `vxm.utils.point_spatial_transformer`.

Take a look and let me know if it makes sense.

**Comment by pmgautam** [comment]
Thanks @adalca. Will go through the code and let you know.

**Comment by adalca** [comment]
Great!

**Comment by prameshgautam** [comment]
@adalca There are tf dependencies in functions such as `affine_to_shift`(is it only for 2D affine transformation?) and neurite library. As I am experimenting in PyTorch, are there any alternatives that can be used in PyTorch?

**Comment by pmgautam** [comment]
@adalca I've tried the notebook you shared earlier. The image used is located [here](https://www.dropbox.com/s/xorkr168natwze4/Case1-FLAIR-resize_128.nii?dl=0). While comparing the coordinates before and after transformation they seem to point to a different location. Can you please help me with this? So far I've only tried affine transformation.

```
img_sitk = sitk.ReadImage("Case1-FLAIR-resize_128.nii")
img = sitk.GetArrayFromImage(img_sitk)

# volume test
aff_3d = np.eye(4)
aff_3d[:3, :3] += np.random.randn(3, 3) * 0.1
aff_3d[:3, 3] = np.random.uniform(-10, 10, (3, ))
aff_inv_3d = np.linalg.inv(aff_3d)

aff_sitk_3d = aff_3d[:3, :3]
aff_sitk_trns = aff_3d[:3, 3]

annotations_3d = np.array([[25.28, 27.42, 70.81],
                  [62.52, 34.42, 81.64],
                  [82.12, 29.38, 99.04],
                  [51.79, 27.42, 85.10],
                  [48.95, 67.44, 27.93]])

# transform to keras shape
im_keras_3d = img[np.newaxis, ..., np.newaxis]
aff_keras_3d = aff_3d[np.newaxis, :3, :]
annotations_keras_3d = annotations_3d[np.newaxis, ...]

# warp image
im_warped = vxm.layers.SpatialTransformer(add_identity=False)([im_keras_3d, aff_keras_3d])
im_warped = im_warped[0, ..., 0]

im_warped_sitk = sitk.GetImageFromArray(im_warped)
im_warped_sitk.CopyInformation(img_sitk)
sitk.WriteImage(im_warped_sitk, "warped_img.nii")

# get dense field of inverse affine
field_inv_3d = vxm.utils.affine_to_shift(aff_inv_3d, img.shape, shift_center=True)[np.newaxis, ...]

# warp annotations
data_3d = [tf.convert_to_tensor(f, dtype=tf.float32) for f in [annotations_keras_3d, field_inv_3d]]
annotations_warped_3d = vxm.utils.point_spatial_transformer(data_3d)[0, ...].numpy()

```
As shown in the image below, these points should have pointed to the same location before and after transformation. Am I missing anything here? Once this is figured out, I can move ahead with dense deformation.
![image](https://user-images.githubusercontent.com/28428143/114313203-4d64c400-9b15-11eb-9071-b1191c80a752.png)

**Comment by adalca** [comment]
@prameshgautam Just looking at this it seems ok, but I'm sure I'm missing something. 

(1) I see that you are visualizing the deformations in a different software -- just note that different software can incorporate the annotation coordinates in different ways. Can you just for evaluation visualize with python tools like in the tutorial? I realize this is 3D but you could try going to the right third slice for the first annotation, or just do the whole experiment on just one slice to start?

(2) Could you set this up in a quick google colab?

**Comment by pmgautam** [comment]
@adalca the issue is with indexing. The visualization tool that I used has XYZ indexing while in NumPy it is ZYX format. By inverting the indices and comparing the images, they point to the same location. Another question I had is about TensorFlow dependency. Is there any alternative in PyTorch that you are aware of which can be used for the same purpose. The main dependency is in `affine_to_shift` and neurite `interpolation`.

Thanks!
