### ISSUE TITLE
 Issue when illustrates the integration of the velocity field at different time points

### ISSUE THREAD

**Issue by Fjr9516** [voxelmorph/voxelmorph#294]
**Task**
I am currently working on the model of this article: ’Learning Conditional Deformable Templates with Convolutional Networks.’  I trained a model on the MNIST dataset. During the test, I tried to get the integration of the velocity field at different time points. I modified the scaling_and_squaring method to get it.  Core code here：
```
    if out\_time\_pt == 0:
        pass
    else:
        vec = vec // (2 ** nb_steps)
        for _ in range(out_time_pt): #here out\_time\_pt changes from 0~7
            vec += my\_transform(vec, vec)
```
Here are the results of pos\_flow: (test only on one task, digital 7 here)
![image](https://user-images.githubusercontent.com/31833999/113610549-93b9af00-964d-11eb-8264-cd9e1492ce6d.png)
I found that changing the variable out\_time\_pt  will not cause a big change of final pos\_flow, and there is already a relatively good registration field at the initial point t=0. To further prove, I visualized the output of the flow layer (the layer before the VecInt layer)：
![image](https://user-images.githubusercontent.com/31833999/113611391-bac4b080-964e-11eb-9a5e-d9273b47d5c5.png)
It seems that the model can learn a good registration field before the integration layer; the function of the integration layer is more like to ‘refine,’ resulting in a more refined registration result.

But according to my understanding, the results should be as shown in the picture in your another article: Unsupervised Learning
of Probabilistic Diffeomorphic Registration for Images and Surfaces
![image](https://user-images.githubusercontent.com/31833999/113611635-14c57600-964f-11eb-81c2-7ad2862e3349.png)
Can you give me some suggestions on how to get the results shown in the image above?
I would be grateful for your advice!

**Comment by adalca** [comment]
Hi @Fjr9516 did you manage to get this to work?

**Comment by Fjr9516** [comment]
Hi, thanks for your reply.
Yes, I got it to work. It seems that I cannot use pos_flow plotted here to represent the integration of the velocity field.
