### ISSUE TITLE
How to calculate the Dice using ANTs

### ISSUE THREAD

**Issue by YMBrianHung** [voxelmorph/voxelmorph#296]
1

**Comment by adalca** [comment]
Essentially, you want to apply your transforms to the moving segmentation map, and then once you have the moved segmentation map you can compare it with the fixed segmentation map via Dice.

ANTs seems to have renamed their files a few times so I'm not sure what tool warps images now, probably `antsApplyTransforms` ?

**Comment by YMBrianHung** [comment]
Do you mean that I can use the deformation filed file generated by ANTs to warp the moving segmentation map?

**Comment by adalca** [comment]
Yes, Affine.mat, InverseWarp.nii.gz, Warp.nii.gz, are all transforms. See https://github.com/ANTsX/ANTs/wiki/Forward-and-inverse-warps-for-warping-images,-pointsets-and-Jacobians, this should be a good introduction to those files.
