### ISSUE TITLE
model.h5  

### ISSUE THREAD

**Issue by yangkang24** [voxelmorph/voxelmorph#297]
Hello, I only need to register the image (run register.py), but I did not find the model.h5 file, how to get it？

**Comment by adalca** [comment]
@yangkang24  it might depend on what you are trying to register -- can you let us know what your data is?

**Comment by yangkang24** [comment]
Hello,
&nbsp; &nbsp; &nbsp; &nbsp;my data are thrmal and visual images,I want to do the fusion of thermal infrared image and corresponding visible image
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;But I can't find the model file I need to run the program.


Regards
YanKang
&nbsp; &nbsp; &nbsp;&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "voxelmorph/voxelmorph"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月23日(星期五) 上午9:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [voxelmorph/voxelmorph] model.h5   (#297)





 
@yangkang24  it might depend on what you are trying to register -- can you let us know what your data is?

**Comment by adalca** [comment]
If you want to use an h5 model, it means it should have been trained for your data, and I don't believe we have a model for thermal images. I would recommend you (1) train your own model, or (2) use an instance trainer like the one shown here: https://github.com/voxelmorph/voxelmorph/blob/master/scripts/tf/train_instance.py which doesn't require a trained model.

If you are still keen on using trained h5 models, we have an [like brain T1 images](https://surfer.nmr.mgh.harvard.edu/ftp/data/voxelmorph/models/)) or perhaps one of the synthmorph models if you want at https://surfer.nmr.mgh.harvard.edu/ftp/data/voxelmorph/synthmorph/
