### ISSUE TITLE
ValueError: Fill dimensions must be >= 0 for '{{node ones}} = Fill[T=DT_FLOAT, index_type=DT_INT32](tensor_cropping_idx_0/Const, ones/Const)' with input shapes: [5], [] and with input tensors computed as partial shapes: input[0] = [?,96,288,288,?].

### ISSUE THREAD

**Issue by BailiangJ** [voxelmorph/voxelmorph#304]
Hello,
I was using the synmorph code and my input_shape is (96,288,288).

In the voxelmorph.tf.synthseg.label_to_image_model.py line 118,
`patch_shape_tens = KL.Lambda(lambda x: tf.convert_to_tensor([-1] + crop_shape + [-1], dtype='int32'),
                                     name=f'tensor_cropping_idx_{id}')(means_input)`

I got the error
ValueError: Fill dimensions must be >= 0 for '{{node ones}} = Fill[T=DT_FLOAT, index_type=DT_INT32](tensor_cropping_idx_0/Const, ones/Const)' with input shapes: [5], [] and with input tensors computed as partial shapes: input[0] = [?,96,288,288,?].

when I change [-1]+crop_shape+[-1] to [1]+crop_shape+[1], the error disappear,

so is it just an error due to the deprecated function of tensorflow?

Thanks a lot.

**Comment by adalca** [comment]
@BailiangJ , thanks for your question. I would encourage you to look in the `dev` branch where we've updated the code, but in the meanwhile I'll ping @mu40, the author of synthmorph, who might comment on the master branch implementation that you are using.

**Comment by mu40** [comment]
Hi @BailiangJ! Please try the SynthMorph implementation of the `dev` branch as @adalca suggested. The code has undergone substantial changes and now supports the latest TensorFlow version. Using SynthMorph in `master` is not recommended; we just didn't get around to replacing it yet.

**Comment by BailiangJ** [comment]
Thank you for the information!
