### ISSUE TITLE
2D registration

### ISSUE THREAD

**Issue by JuliusWang-7** [voxelmorph/voxelmorph#311]
hi adalca,
First at all, thank u for sharing your works.
I am learning registration these days, and now I want to put your method into segmentation works.
I copy the codes from https://www.kaggle.com/adalca/learn2reg ,but I don't know how to edit the parameters to deform my segmentation(label). I hope u to give me some advice.

**Comment by adalca** [comment]
Hello,

I recommend you try http://tutorial.voxelmorph.edu for a nicely updated tutorial on how to use voxelmorph. For what you're asking, you can try:

`model.apply_transform(moving_image, fixed_image, moving_segmentation_image, interp_method='nearest')`, where these images have the usual keras shape for 2d: `[1, H, W, 1]`

**Comment by JuliusWang-7** [comment]
thank u very much!
I have solved my problem.
