### ISSUE TITLE
Some fundamental questions

### ISSUE THREAD

**Issue by 1299246210** [voxelmorph/voxelmorph#316]
I'm sorry to bother you again, these questions may seem silly!
1. I want to use two GPUs for training，and run `pythontrain.py /mnt/home/lqu/lx/vox1/input  --model-dir /mnt/home/lqu/lx/vox1/output --batch-size 2 --gpu  0,1 `  
I got an error`ValueError: invalid literal for int() with base 10: '0,1'`，I confirm that these two GPUs can be used separately. Looks like something went wrong with my commands，so what is the correct command？
2.  `transformer_loss` and `flow_resize_loss` How did they figure out？ What do they stand for？
Thanks a lot!

**Comment by adalca** [comment]
1. can you tell us which voxelmorph you're using exactly? is it from pip? master branch? dev branch?
Multi-gpu support like that may only have been added recently, right @ahoopes ?

2. I'm not sure I understand the question. The first loss is the similarity (achieved by applying a transformer to one image and comparing with the second). The second loss is the smoothness loss.

**Comment by 1299246210** [comment]
1. I use the master branch and tf=2.4.0 .  I got it through Git. And I installed vxm by pip. Does this branch support multiple GPUs？
2. I see, tkanks!

**Comment by adalca** [comment]
I thought it should support multiple GPUs. Can you post the entire error trace of 
`ValueError: invalid literal for int() with base 10: '0,1'` ?

**Comment by ahoopes** [comment]
There might be a multi-GPU bug in the master branch, can you try the dev branch instead?

**Comment by thomshaw92** [comment]
Hi,  we are having the same error even in the dev branch trying to use 2 GPUs.
using the command 
``` 
train_template.py --gpu '0,1'
```

**Comment by ahoopes** [comment]
Okay, multi-gpu support with tensorflow 2 should be working as expected now (fix: ce78f4d)

**Comment by WwwwJX** [comment]
> I'm sorry to bother you again, these questions may seem silly!
> 
> 1. I want to use two GPUs for training，and run `pythontrain.py /mnt/home/lqu/lx/vox1/input  --model-dir /mnt/home/lqu/lx/vox1/output --batch-size 2 --gpu  0,1 `
>    I got an error`ValueError: invalid literal for int() with base 10: '0,1'`，I confirm that these two GPUs can be used separately. Looks like something went wrong with my commands，so what is the correct command？
> 2. `transformer_loss` and `flow_resize_loss` How did they figure out？ What do they stand for？
>    Thanks a lot!

excuse me, can you tell me what in your input file???
