### ISSUE TITLE
issue with hypermorph

### ISSUE THREAD

**Issue by daxuemi** [voxelmorph/voxelmorph#317]
dear professor,
  Considering that you haven't provided **test_hypermorph.py** yet to calculate dice score, we try to implement this code ourselves under your guidance.([voxelmorph/voxelmorph/issues/293])
   Our implementation as follows:
```python
         for hyp_n, hyp_lambda in enumerate(np.linspace(0, 1, 20)):
              hyp = np.array([[hyp_lambda]], dtype='float32')
              # predict and apply transform
              warp = registration_model.predict([moving_vol, atlas_vol, hyp])[0]
              print("warp.shape = ", warp.shape)
              # warp_vol = nib.Nifti1Image(warp, fix.affine)
              # nib.save(warp_vol, "wrap1")
              warped_seg = transform_model.predict([moving_seg, warp]).squeeze()
              # compute volume overlap (dice)
              overlap = vxm.py.utils.dice(warped_seg, atlas_seg, labels=labels)
```
however, we got the error as follows:   

this line : `warped_seg = transform_model.predict([moving_seg, warp]).squeeze()`

 Model was constructed with shape (None, 160, 192, 224, 3) for input KerasTensor(type_spec=TensorSpec(shape=(None, 160, 192, 224, 3), dtype=tf.float32, name='trf_input'), name='trf_input', description="created by layer 'trf_input'"), but it was called on an input with incompatible shape (None, 160, 192, 224, 1).

 We dont know what happened since it seems that  there's nothing wrong with our process. so we need your help. We would be grateful if you could help us to analyze the possible causes. thank you professor！

We will share our  implement code to test hypermorph later if the problem is solved. 

 At the same time, we are looking forward to your release of the official version of  ` test_hypermorph.py ` so that we can use hypermorph more easily

**Comment by adalca** [comment]
Hi @daxuemi ,

what is `registration_model` in your code? I believe it is not outputting the right thing. 

We're working on a test/tutorial, balancing with upcoming conferences for `hypermorph`

**Comment by jackyko1991** [comment]
Work around:
``` python
warp_model = tf.keras.Model(inputs=registration_model.input, outputs=registration_model.get_layer("hyper_vxm_dense_diffflow").output)
warp = warp_model.predict([moving, fixed, hyp])
```
