### ISSUE TITLE
Run into a warning with vxm.layers.SpatialTransformer

### ISSUE THREAD

**Issue by XXZhou25** [voxelmorph/voxelmorph#319]
**Task** (what are you trying to do/register?)

3D CT registration 

**What have you tried**

using voxelmorph library functions to transform moving image with a deformation field. 

**Details of experiments**

Environment: 
tensorflow                2.0.0  
voxelmorph                0.1

I ran into this warning when I trained my model. I am not sure what it exactly means. Model can be trained, but I am worried if my moving image is not really transformed by a dense field, instead it is transformed by identity mapping. Should I worry about this? Have you met similar problem? Thanks!

`
2021-06-06 10:07:28.338801: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
WARNING:tensorflow:Entity <bound method TensorFlowOpLayer._defun_call of <tensorflow.python.eager.function.TfMethodTarget object at 0x7f84c00f7850>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: No module named 'tensorflow_core.estimator'
WARNING:tensorflow:Entity <bound method TensorFlowOpLayer._defun_call of <tensorflow.python.eager.function.TfMethodTarget object at 0x7f84c00751d0>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: No module named 'tensorflow_core.estimator'
WARNING:tensorflow:From /home/xiaoxiao.z/anaconda3/envs/voxelmorph/lib/python3.7/site-packages/tensorflow_core/python/ops/array_grad.py:502: _EagerTensorBase.cpu (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.identity instead.
`

**Comment by adalca** [comment]
@XXZhou25 , I don't believe this is an issue that affects the results of voxelmorph, but instead leads to some suboptimal tf usage.

Did you have issues with the resulting deformations looking like identity?

**Comment by XXZhou25** [comment]
> @XXZhou25 , I don't believe this is an issue that affects the results of voxelmorph, but instead leads to some suboptimal tf usage.
> 
> Did you have issues with the resulting deformations looking like identity?

Hi @adalca , Thank you so much for your quick reply! Actually the deformation didn't look like identity. I upgraded my tensorflow-estimator to match with my tensorflow version, then it is almost solved. 
Only one warning left: 
`2021-06-06 11:02:42.457526: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
WARNING:tensorflow:From /home/xiaoxiao.z/anaconda3/envs/voxelmorph/lib/python3.7/site-packages/tensorflow_core/python/ops/array_grad.py:502: _EagerTensorBase.cpu (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.identity instead.`

Good to know it won't affects results of voxelmorph! Thank you so much again:)

**Comment by adalca** [comment]
Glad to help!
