### ISSUE TITLE
no training configuration found ..... whwne running register.py

### ISSUE THREAD

**Issue by hassaanmahmood** [voxelmorph/voxelmorph#33]
I ma trying to use already trained model using 
'python register.py --gpu 0 /path/to/test_vol.nii.gz /path/to/atlas_norm.nii.gz --out_img /path/to/out.nii.gz --model_file ../models/cvpr2018_vm2_cc.h5 '

I am getting the following error

'envs/tensorflow3.6/lib/python3.6/site-packages/keras/engine/saving.py:269: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '

should I retrain the model or is there a way to test your trained model.

Thanks

**Comment by adalca** [comment]
The message you quotes is just a warning -- it's saying that the model is not compiled, which means you would not be able to train as is, but you can use it to predict (register) just fine. Are you noticing any other types of errors?

**Comment by hassaanmahmood** [comment]
thanks a lot for your reply. So does it mean that If I want to train , I have to start from scratch?
and Can do transfer learning here?
Regards

**Comment by adalca** [comment]
You don't have to start from scratch. In fact, train.py allows you to provide a file for initial weights via `load_model_file`!
