### ISSUE TITLE
Training scripts call example  

### ISSUE THREAD

**Issue by idhamari** [voxelmorph/voxelmorph#338]
It seems the description is not updated 

     ./scripts/tf/train.py /path/to/training/data --model-dir /path/to/models/output --gpu 0

The [script](https://github.com/voxelmorph/voxelmorph/blob/dev/scripts/torch/train.py) requires [img-list](https://github.com/voxelmorph/voxelmorph/blob/229a74781331c289b59efeacc79106278cc63eaa/scripts/torch/train.py#L52)

     parser.add_argument('--img-list', required=True, help='line-seperated list of training files')) 

which is not mentioned in the example script call above.

It would be nice to add an example for -img-list.

**Comment by kimtaeuk-AI** [comment]
Hi, I solved it using txt file. python semisupervise_seg.py --img-list /path/name.txt. You must do text and img-suffix, seg-suffix in the txt file.

**Comment by idhamari** [comment]
Thanks, can you show part of the txt file as an example.

**Comment by WwwwJX** [comment]
> Hi, I solved it using txt file. python semisupervise_seg.py --img-list /path/name.txt. You must do text and img-suffix, seg-suffix in the txt file.

excuse me, can you show me your txt files???

**Comment by adalca** [comment]
Our apologies for the late reply, for those of you still having issues, please take a look at #355
