### ISSUE TITLE
how to visualize deformation field?

### ISSUE THREAD

**Issue by norris9410** [voxelmorph/voxelmorph#35]
Hi,

I am reading the paper entitled "VoxelMorph: A Learning Framework for Deformable Medical Image Registration". in Fig. 6, columns 4-5 represent the deformation fields. I am wondering how you guys visualize the deformation field like that? Is it somewhere in the program capable of giving these figures?

Thanks for your work! Look forward to your response.

**Comment by adalca** [comment]
hi @norris9410,

Column 4 is an RGB image of the deformation field at a particular slice. A slice is 2D, and the deformation field at each voxel is a 3-D vector, hence the deformation field for a slice is a 2D image with 3 channels, which can easily be visualized as a standard RGB image (one color per direction). For example, you can use `matplotlib.pyplot.imshow` in python or `imshow` in matlab. You might need to normalize the values to be in [0,1]

Column 5 is simply done by creating a black and white grid (e.g. using `bw_grid` in [pynd](https://github.com/adalca/pytools-lib/blob/master/pynd/ndutils.py)) and warping it with the deformation field that came from `voxelmorph`.

Hope this helps!

**Comment by norris9410** [comment]
thanks for quick response. Ya i totally miss the bw_grid function and I am good with col 5.

I am still a bit confusing about column 4. Is there any physical meaning of those images in column 4? e.g. if the pixel looks green, does it imply anything (perhaps a larger value) in the deformation field?

**Comment by adalca** [comment]
The deformation (in this case, displacement) slice is HxWx3. The `3`  comes from the fact that the displacement is a 3D vector at each location. So, when shown as a RGB image, each of the primary colors (red, green, blue) will represent one of those directions. So (depending on how you normalize) a strongly green pixel will mean a significant shift in the second dimension, while likely small shifts in the first and third dimensions.

**Comment by norris9410** [comment]
Appreciate it! Thank you very much

**Comment by AnkitaJo** [comment]
When you say: "Column 5 is simply done by creating a black and white grid (e.g. using bw_grid in pynd) and warping it with the deformation field that came from voxelmorph."
What does "warping" mean? In the paper you use the SpatialTransformer layer to transform the source image using the flow. Or do you use any external library to do the warping?

**Comment by adalca** [comment]
@AnkitaJo yes, using the `SpatialTransformer` layers would be one way to do the warping!

**Comment by zerglog** [comment]
> @AnkitaJo yes, using the `SpatialTransformer` layers would be one way to do the warping!

If I want to use the matlab to do the warping,  Can I use the VolWarp code in matlab library?

**Comment by adalca** [comment]
Yes, I think that should work.
