### ISSUE TITLE
VoxelMorph pretrained weights are not available 

### ISSUE THREAD

**Issue by Hoda1394** [voxelmorph/voxelmorph#359]
I am trying to download the VoxelMorph pre-trained weights (vxm_T1_3D_mse.h5) through the link that is provided in the data folder, but no file is downloaded. seems the file is not available. 
how I can access the VoxelMorph pre-trained model?

**Comment by adalca** [comment]
Hmm, can you try again? I think the link was http instead of https, which sometimes acts weirdly.

**Comment by Hoda1394** [comment]
it works now.
Thanks
