### ISSUE TITLE
test progress of  ANTs

### ISSUE THREAD

**Issue by SY51826** [voxelmorph/voxelmorph#37]
Dear expert: Your paper has a dice score calculation for 29 anatomical structures of the brain. One of the comparison methods is ANTs. I would like to know the process used by ANTs which get experimental results (avg dice 0.749). I have used ANTs to do the registration and got the output after registration. How do I make a warp on the seg data to achieve the purpose of the test.

I got the following output with the syn algorithm：
![image](https://user-images.githubusercontent.com/46043268/56739639-c12f2a00-67a1-11e9-9e06-f8211c4a0f6a.png)

**Comment by adalca** [comment]
In general for specifics of using ANTs, I would recommend the [ANTs instructions file](https://sourceforge.net/p/advants/svn/5/tree/Documentation/ants.pdf?format=raw).

Assuming you have a segmentation file for your subject, you have to use ANTs' `WarpImageMultiTransform` with the `useNN` option to warp the atlas's segmentation file and compare with the subject's segmentation file. 

We used Dice to compare the two files, and there's many implementations of Dice -- e.g. in [our toolbox](https://github.com/adalca/pytools-lib/blob/master/medipy/metrics.py)
