### ISSUE TITLE
error register.py voxelmorph line 65

### ISSUE THREAD

**Issue by Robotronikpi** [voxelmorph/voxelmorph#385]
****
Hi,
I try to register images with voxelmorp using the command
%run register.py --moving temp.npz --fixed temp.npz --moved temp2.npz --model model_1.h5 --gpu 0
temp.npz (3D array between 0,1)
and model_1.h5 is :  https://surfer.nmr.mgh.harvard.edu/ftp/data/voxelmorph/synthmorph/shapes-dice-vel-3-res-8-16-32-256f.h5
and i get this error : 
***
``
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/opt/notebooks/voxelmorph-dev/scripts/tf/register.py in <module>
     63 with tf.device(device):
     64     # load model and predict
---> 65     warp = vxm.networks.VxmDense.load(args.model,input_model=None).register(moving, fixed)
     66     moved = vxm.networks.Transform(inshape, nb_feats=nb_feats).predict([moving, warp])
     67 

TypeError: load() got an unexpected keyword argument 'input_model'
``
-------------------------------------------------------------------------------------------
***
if i change line 65 by warp = vxm.networks.VxmDense.load(args.model).register(moving, fixed)
i get a new error: 
***
``
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/opt/notebooks/voxelmorph-dev/scripts/tf/register.py in <module>
     63 with tf.device(device):
     64     # load model and predict
---> 65     warp = vxm.networks.VxmDense.load(args.model).register(moving, fixed)
     66     moved = vxm.networks.Transform(inshape, nb_feats=nb_feats).predict([moving, warp])
     67 

/opt/conda/lib/python3.6/site-packages/voxelmorph/tf/modelio.py in load(cls, path, by_name)
    101             ]
    102 
--> 103         model = cls(**config)
    104         model.load_weights(path, by_name=by_name)
    105         return model

/opt/conda/lib/python3.6/site-packages/voxelmorph/tf/modelio.py in wrapper(self, *args, **kwargs)
     20         # run the constructor first to avoid any issues with
     21         # the keras Model class not being initialized yet
---> 22         retval = func(self, *args, **kwargs)
     23 
     24         params = {}

TypeError: __init__() got an unexpected keyword argument 'name'
------------------------------------------------------------------------------------------------
``
***
Anyone have any idea how to avoid these mistakes?
I have already reinstalled voxelmorph, neurite and pystrum and it doesn't change anything.
***

**Comment by adalca** [comment]
Hi @Robotronikpi , Can you tell us if you've gone through #378 where @ahoopes suggested a specific way to handle the versions?

**Comment by Robotronikpi** [comment]
Ok now it's working! , the error was as  @ahoopes said, I use dev code and I installed master branch of voxelmorph.
so to correct that I installed the dev code instead (pip install git+https://github.com/voxelmorph/voxelmorph.git@dev#egg=voxelmorph) and i get a new error because of my version of TensorFlow that i a find a solution here : https://github.com/tensorflow/models/issues/9700
(reinstall a another version of tensorflow)

**Comment by Robotronikpi** [comment]
> Hi @Robotronikpi , Can you tell us if you've gone through #378 where @ahoopes suggested a specific way to handle the versions?

Ok now it's working! , the error was as @ahoopes said, I use dev code and I installed master branch of voxelmorph.
so to correct that I installed the dev code instead (pip install git+https://github.com/voxelmorph/voxelmorph.git@dev#egg=voxelmorph) and i get a new error because of my version of TensorFlow that i a find a solution here : tensorflow/models#9700
(reinstall a another version of tensorflow)

**Comment by jondo** [comment]
Seems this issue can be closed.
