### ISSUE TITLE
Create a surgical atlas

### ISSUE THREAD

**Issue by codeenthusiast** [voxelmorph/voxelmorph#389]
Hi team, I am hoping to create a surgical atlas from approximately 30-50 CT head's and then develop a registration-segmentation pipeline. I had previously tried this in ANTs but was not getting the desired accuracy. Therefore, I was hoping to do it in Voxelmorph. So my questions are:

1) Can I create a surgical atlas? (is there a function or code I can use for this?)
2) For registration of the atlas (fixed) to moving image, I'd like to perform label propagation from the atlas to the new CT. What is the best recommended way to go about this?

Thanks so much!

**Comment by adalca** [comment]
Hi @codeenthusiast ,

I believe the answer is yes -- our template (atlas) building tools should apply to your dataset of 30-50 CTs. Just to be sure, what does surgical signify here? I suspect this script should help you: https://github.com/voxelmorph/voxelmorph/blob/dev/scripts/tf/train_template.py

We haven't built CT atlases, so it might be useful to know a bit about your data, how diverse they are, etc. 

Our atlas building tutorial might also help: https://colab.research.google.com/drive/1SkQbrWTQHpQFrG4J2WoBgGZC9yAzUas2?usp=sharing

**Comment by codeenthusiast** [comment]
Thanks Adrian for your reply! Sorry for the confusion, they are just fine-cut head CT's. Primarily, we are interested in registering small structures in the head such as inferior turbinate (image below).

We would like to build an atlas to serve as our population representation. From here, we were hoping to 1) develop SSM's to showcase the variability of a particular structure in the population and 2) segment the atlas, register a new image to the atlas, and then perform label propagation.

![](https://user-images.githubusercontent.com/6239462/148625510-870c23a3-3be9-4ad8-aa85-3e02c1c55b70.png)

**Comment by adalca** [comment]
Got it, makes sense. You should be able to do with with vxm.

I'd recommending going through the tutorial, it gives an idea of our atlas building frameworks with simplistic examples.

It would be optimal if your data was **roughly** affinely in the same space already. The most challenging part will be to tune the loss to match your dataset. I haven't worked with CT too much, but normalizing the data to be between [0-1] by some fixed hausdorff unit and using our standard script might be a way to start -- another one I might suggest is to just extract  the middle slice (just for quick experimentation) and building an atlas for that. It would enable you to quickly see what's possible and tune your loss.

**Comment by codeenthusiast** [comment]
Sounds great, thanks again Adrian. Will give that a try and post here again if any issues.

**Comment by codeenthusiast** [comment]
Hi Adrian, just following up on the suggested resources. I had a look at the train_template. From my understanding, I need to pass in a set of images to img_list and call the read_file_list function. Thereafter, the vxm.networks.TemplateCreation function would generate my template which would technically be the average of all my CT's. Do I have the correct understanding?

Two other questions:
1) I am working with 3D slicer. I know the accepted file types are NIFTI or .npz, but does it support .nrrd?
2) By unconditional template creation, I assume this means unlabelled images? 

Thanks!
