### ISSUE TITLE
Image 'Model' training Generation

### ISSUE THREAD

**Issue by codeenthusiast** [voxelmorph/voxelmorph#390]
I am working on creating a template for a series of 3D images by using the train.py (specifically the vxm.networks.VxmDense function). Unfortunately, my training images have unequal dimensions (e.g. img1 [512,512,230] img2[512,512,280]). As a result, before I go ahead, I need to resample my image. Does VXM have a function that I can use to resample my images? Thanks!

**Comment by adalca** [comment]
Hi @codeenthusiast 
I wouldn't recommend resizing, since that would affect the voxel dimensions. If you still wish to that, you could use scipy.ndimage.interpolation.zoom. However, I'd recommend padding up to 512^3 (and as a test reshape the 512^3 to 64^3 to see if you can learn that atlas first

**Comment by codeenthusiast** [comment]
Thanks for your reply Adrian. Just to clarify, in order to train my model, I have to make sure that all my images have the same dimensions correct?

With the Scipy function, we actually tried that and although the dimensions were equal across images, it made some look compressed/stretched. I assume that shouldn't happen?

**Comment by adalca** [comment]
yes, same size.

right, that's what i meant about not using scipy to resize from 280 to whatever -- you'll stretch/compress the image.

instead, you should pad with zeros (e.g. to 512). Then if you resize *all* dimensions to e.g. 64, it'll be changing all axes by the same factor, so it wont' be stretched

**Comment by codeenthusiast** [comment]
Great, I will try that. If I do pad however, when the images are overlaid on top of one another, I assume some will be larger than others? Is that okay when fed into he model?

**Comment by adalca** [comment]
Hm, im not sure i understand. I'm suggesting you pad them all to 512x512x512, so they would all be the same size.

**Comment by codeenthusiast** [comment]
Sorry, I meant once they are all padded to be 512x512x512, an image that has more padding would look smaller than an image with less padding. I am specifically referring to CT, in this case, the head.

**Comment by adalca** [comment]
right, some images will have more black. Is the head substantially cropped, or is it more neck that's being cropped? I'd have to see some images.

**Comment by codeenthusiast** [comment]
Yes, it is primarily the head but as you move the scan posteriorly, then the back of the neck may sometimes be included. Below is a sample from Google Images but that is essentially what the images look like.

![image](https://user-images.githubusercontent.com/6239462/152712135-8797bfd4-629b-4590-9d13-0e153001d2c4.png)
