### ISSUE TITLE
problems in multi modal registration

### ISSUE THREAD

**Issue by Charles-Hu** [voxelmorph/voxelmorph#398]
**Task** (what are you trying to do/register?)

PET and CT image of mouses(multi-modal)

**What have you tried**

Calculate Hu and SUV of each CT, PET image. Split each image to small patches. 0-1 norm for each patch. Use default parameters to train the model. Use NCC loss and lambda  = 1.

**Details of experiments**
The loss didn't decrease. I try to print the result, and find that the moving image doesn't change a lot at first and the loss stay at [-0.2, 0.15]. Then after a few epoch, moving image starts to distort, the loss start to increase. The the output will be a black image or white image.
![image](https://user-images.githubusercontent.com/52573031/155763043-415f8cfb-1e6f-4343-93f0-27310395de7c.png)
The first subplot is the output, the second subplot is the moving image, the final subplot is the target.
![image](https://user-images.githubusercontent.com/52573031/155763223-6abcbd1e-1b40-4b8a-acaa-3cfb2d67c685.png)

**Comment by adalca** [comment]
What are the images you're showing?
Can you try lowering the LR?

**Comment by Charles-Hu** [comment]
The image is the ct and pet of mouses. Below is one of the whole body images.
![image](https://user-images.githubusercontent.com/52573031/155765641-1a89aad7-94e2-417e-ba9e-7be975f9ef1a.png)
The first subplot is PET, the second is CT
The image I upload at the issue is the patches of whole body images.
I use lr= 1E-4

**Comment by adalca** [comment]
you uploaded 3 images, what is the first one?

**Comment by Charles-Hu** [comment]
![image](https://user-images.githubusercontent.com/52573031/155767002-aa7742dd-7264-4789-a115-b4f3ccd9468c.png)
This image is one of the whole body pet image.
![image](https://user-images.githubusercontent.com/52573031/155767053-5c84488e-02cd-432c-93a7-0664f604353d.png)
This image is one of the whole body ct image
![image](https://user-images.githubusercontent.com/52573031/155767119-9b250cb3-cb5b-4db7-b62d-090f608177af.png)
This image is one patch of the whole body ct image
![image](https://user-images.githubusercontent.com/52573031/155767219-96e54151-b899-49ce-ba51-4b7a9fbdb3ec.png)
This image is one patch of the whole body pet image
![image](https://user-images.githubusercontent.com/52573031/155767277-56916544-2b5f-448d-ad3b-095aa044998f.png)
This image is the output after a few epoch
![image](https://user-images.githubusercontent.com/52573031/155767378-e0632fc2-49d8-4c03-af4a-e2b08713c306.png)
This image is another output
![image](https://user-images.githubusercontent.com/52573031/155767448-68219c7d-95b3-45a6-b48f-2a60318edc6e.png)
This image is the final output

**Comment by Charles-Hu** [comment]
They are all 3D images

**Comment by adalca** [comment]
sorry what are 'another output' and 'final output'? You mean after different epochs?

are the images normalized to [0, 1]?

I would recommend normalizing the images to [0, 1] and making the regularization higher than it was by default.

**Comment by Charles-Hu** [comment]
another output and final output  are the output after different epochs. The mean of the images is 0 and the variance is 1. I will try to normalize the images to [0, 1] and make the regularization higher than it was by default.
