### ISSUE TITLE
How to visualize the .npz data easily?

### ISSUE THREAD

**Issue by Barnonewdm** [voxelmorph/voxelmorph#4]
I just wanna do some visualization of data. But cannot find a solution.

**Comment by adalca** [comment]
`.npz` is numpy's zipped `.npy` file format, you can read more about it here: https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.savez.html

you can thus use `numpy.load` to load such a file, which will give you a dictionary of the variables inside. We supply an example volume data, which will be a 3D numpy volume. You can then visualize this in your favorite way -- for example by taking out a slice and using matplotlib to visualize it.

**Comment by Barnonewdm** [comment]
@adalca 
> -- for example by taking out a slice and using matplotlib to visualize it.
Yes. But the volume data is 3D which will be easy to upload the data in 3D(.img/.hdr or .nii) format. I find it a little tedious to visually check the warped image. So could u share me your solution to compare the warped image and fixed image in 3D visualization? #

**Comment by adalca** [comment]
If I understand your question correctly, we usually try to look at the 3D volume slice by slice, since it's easier to visualize. So we take out the middle slice, for example, and look at the original images and the warped image (and maybe segmentations). We haven't really used 3D visualizations.

You might find the `slices` function in https://github.com/adalca/neuron/blob/master/neuron/plot.py helpful.

If you are using python, colleagues @jjgo have also used the bokeh python library to sweep through the slices.

**Comment by pinglang** [comment]
Hello, sir
the results is showing :TypeError: not all arguments converted during string formatting
how to deal with it?
my code : 
image = np.load("/Users/scspla/PycharmProjects/voxelMorph/voxelmorph-master/voxelmorph-master/data/test_vol.npz")
#image = np.load('test_vol.npz')
image = image(1)

plt.imshow(image[:,:,2])
plt.colorbar()
plt.plot()

**Comment by adalca** [comment]
what are you trying to do with `image = image(1)` ? This by itself should give you an error. 

The following should work:

```
npz_data = np.load("/Users/scspla/PycharmProjects/voxelMorph/voxelmorph-master/voxelmorph-master/data/test_vol.npz")
image = npz_data['vol_data']

plt.imshow(image[...,100])  # slide 100
plt.colorbar()
plt.plot()
```

**Comment by pinglang** [comment]
thanks,
but it does not work. No figure showing after running

**Comment by pinglang** [comment]
why 'image  = npz_data['vol_data']'?

**Comment by adalca** [comment]
npz is a numpy file format that stores data in named variables. We put the volume data in the `vol_data` variable.

I'm not sure why it doesn't work, but if there are no errors, then it's probably a problem with your plotting setup if a figure doesn't show up. (I just tested it to make sure and It worked fine for me)

**Comment by pinglang** [comment]
hello,Sir
 there are no errors, a figure doesn't show up .how to set up plotting setup ?

**Comment by pinglang** [comment]
how to uncompress the 'test_vol.npz' dataset? 
I want to downsample  this dataset, because this data is too large to my GPU memory.

Another question: the 'test_vol.npz' data is just an example that can verify your code could running?

**Comment by pinglang** [comment]
how to convert the 'test_vol.npz' to image? 
I want to downsample the test_vol data, because present data is too large for my GPU memory, so I cannot change the 'batch_size' and 'learning_rate'

**Comment by adalca** [comment]
`test_vol.npz` is a single example volume. 

The following code, which I shared above, will give you a `160x192x224` volume
```
npz_data = np.load("/Users/scspla/PycharmProjects/voxelMorph/voxelmorph-master/voxelmorph-master/data/test_vol.npz")
image = npz_data['vol_data']
```

**downsample**: If you'd like to downsample this image, I'd recommend simply taking every second pixel as the easiest operation, e.g. `img_down_2 = image[::2,::2,::2]`

**datasets**: If you want to download entire datasets, please see the list in our paper of datasets we used, or download an easily accessible dataset (see a list here: https://github.com/adalca/medical-datasets)

**plotting**: I think this is beyond the scope of the voxelmorph forum, please see documentation for https://matplotlib.org/

**Comment by pinglang** [comment]
Hi sir 
Thank you so much.
Now, the new problems is : 
I have just both downsample the 'test_vol' and 'atlas_norm['vol']'  into size [20,24,28], however, when I training 'train_miccai2018.py', the error is:
 'ValueError: A `Concatenate` layer requires inputs with matching shapes except for the concat axis. Got inputs shapes: [(None, 4, 4, 4, 32), (None, 3, 3, 4, 32)]'.
the reported original error is coming :the 'network.py' line 65 'x = concatenate([x, x_enc[-2]])'

how to solve this problem?

**Comment by adalca** [comment]
The network has 4 downsample/upsample operations, so the image sizes have to be a multiple of 16. You could either try to change the architecture (to have fewer downsample/upsample operations) or work with image sizes taht are multiple of 16.

**Comment by pinglang** [comment]
sorry sir, I cannot understand what you said. could you please give me an example? just for volume is [20,24,28]

another question:  are the datasets used in your paper could download for free, according to your paper's references?

**Comment by adalca** [comment]
Please look into the UNet architecture (https://lmb.informatik.uni-freiburg.de/people/ronneber/u-net/) to understand a bit more -- the image has to be downsampled and upsampled by 2 four times. Because of this, the input to the network has to be a multiple of 16 in each dimension to be able to recover the same image (e.g. [16, 16, 16]). If one dimension is of size 20, then if you divide it twice you get size 5, which is not divizible by 2 again, so the network will do funny things.

One solution: pad your image to [32, 32, 32].

Please see the [**notes on data**](https://github.com/voxelmorph/voxelmorph#notes-on-data) in the README

**Comment by pinglang** [comment]
thank you so much.
the default model is '.../models/', but the 'models' folder has many models, which model is my trained model when I running the 'train_miccal2018.py'?

**Comment by adalca** [comment]
during training, models are saved as `<number>.h5` -- for example `1.h5`, `123.h5`, etc
I recommend you don't save to `../models/`, but something like `../models/pinglang_miccai_model/` or something, so you have good naming for your model

**Comment by pinglang** [comment]
Thank you so much
