### ISSUE TITLE
Encounters an error during synthmorph tranning

### ISSUE THREAD

**Issue by kimtaeuk-AI** [voxelmorph/voxelmorph#406]
Hello,

I'm doing a lot of things with your codes.
However, an error  in  synthmorph tranning  occurs.

_ValueError
A `Concatenate` layer requires inputs with matching shapes except for the concat axis. Got inputs shapes: [(None, 2, 64), (None, 3, 64)]_

I'm doing 

arg.label_dir = ???
arg.out_labels='fs-labels.npy'

May I know what 'label_dir, out_labels' you used?

Thank you in advance.

**Comment by mu40** [comment]
It's great to hear that you find our code useful! Unfortunately, I can't help with the error you get without further information. You will want to find out which tensors these are, and why they differ in shape.

The `label_dir` argument should be a path pointing to your training label maps, while the `out_labels` argument defines the (numerical) labels whose overlap you want to maximize during training. This will obviously depend on the labels of your training data, but you can find an example of FreeSurfer-specific labels at: https://surfer.nmr.mgh.harvard.edu/ftp/data/voxelmorph/synthmorph/fs-labels.npy.

For a demo showcasing the steps of generating random label maps from noise distributions and using these to train a network, you may want to have a look at [synthmorph.voxelmorph.net](https://synthmorph.voxelmorph.net/).

**Comment by kimtaeuk-AI** [comment]
Hello! Thank you for your reply.

I was using Oasis Seg data.

Oh no... It was a problem because the code of "neurite uitls.py" was different.

Thanks to you, I am happy to know label_dir and out_label.

Thank you so much :)

**Comment by kimtaeuk-AI** [comment]
Hello.. I have a second problem. Synthmorph.  

I tried to learn by making the label_dir and out_label that you told me, but the learning didn't go well.

I put  in label_dir -
![Untitled](https://user-images.githubusercontent.com/83504682/159904852-1bf93f97-3437-40ce-883c-ddd6cb589b83.png)
, shape = 160,192,224, array = [0,1,2,3,4 ... 38,39]
     , in out_label -![image](https://user-images.githubusercontent.com/83504682/159905446-22f0290b-62f6-4b5f-9d33-91bc9daa3472.png), array=[0,12,3,4...38.39] ,

 and I learned. 
![image](https://user-images.githubusercontent.com/83504682/159905515-12a9bbc1-0bff-42ee-aa93-9c6806f0da81.png)

The moving image does not change during registration.

I don't know where it went wrong.

Can you help me..?

**Comment by kimtaeuk-AI** [comment]
Hello.. I have a second problem. Synthmorph.  

I tried to learn by making the label_dir and out_label that you told me, but the learning didn't go well.

I put  in label_dir -
![Untitled](https://user-images.githubusercontent.com/83504682/159904852-1bf93f97-3437-40ce-883c-ddd6cb589b83.png)
, shape = 160,192,224, array = [0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
     , in out_label -![image](https://user-images.githubusercontent.com/83504682/159905446-22f0290b-62f6-4b5f-9d33-91bc9daa3472.png), array=[0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15] ,

 and I learned. 
![image](https://user-images.githubusercontent.com/83504682/159905515-12a9bbc1-0bff-42ee-aa93-9c6806f0da81.png)

The moving image does not change during registration.

I don't know where it went wrong.

Your 'shapes-dice-vel-3-res-8-16-32-256f.h5' works well.

Can you help me..?

**Comment by mu40** [comment]
How many label maps did you generate? Your loss seems quite low to begin with; does it decrease during training? Does your trained model register training image pairs?

**Comment by kimtaeuk-AI** [comment]
Oh! Thank you. I put only one image. :) Have a good day
