### ISSUE TITLE
WARNING:tensorflow:Model was constructed with incompatible shape

### ISSUE THREAD

**Issue by Ehsan-data** [voxelmorph/voxelmorph#409]
**Task** (what are you trying to do/register?)

[](https://stackoverflow.com/posts/71634277/timeline)0

I'm trying to use a pre-trained model with my own MRI 3D data to register brain MRI images
**What have you tried**

I loaded my 3D data using nilearn
**Details of experiments**

f_img_1= nib.load('/Users/training/013/time01.nii.gz')
f_img_2= nib.load('/Users/training/013/time02.nii.gz')

img_data_1 = f_img_1.get_fdata()
img_data_2 = f_img_2.get_fdata()

Please carefully specify details about your experiments. If you are training, when what is the setup? What loss are you using? What does the convergence look like? If you are registering, please show example inputs and outputs. etc.

I came across the below error:

first Part of the error:

WARNING:tensorflow:Model was constructed with shape (None, 160, 192, 224, 1) for input Tensor("source_input_3:0", shape=(None, 160, 192, 224, 1), dtype=float32), but it was called on an input with incompatible shape (None, 365, 256, 256, 1). WARNING:tensorflow:Model was constructed with shape (None, 160, 192, 224, 1) for input Tensor("target_input_3:0", shape=(None, 160, 192, 224, 1), dtype=float32), but it was called on an input with incompatible shape (None, 365, 256, 256, 1).

final Part of the error:

ValueError: Dimension 1 in both shapes must be equal, but are 44 and 45. Shapes are [?,44,32,32] and [?,45,32,32]. for '{{node vxm_dense/unet_dec_upsample_3_concat/concat}} = ConcatV2[N=2, T=DT_FLOAT, Tidx=DT_INT32](vxm_dense/unet_dec_upsample_3/concat_2, vxm_dense/unet_enc_conv_3_0_activation/LeakyRelu, vxm_dense/unet_dec_upsample_3_concat/concat/axis)' with input shapes: [?,44,32,32,32], [?,45,32,32,32], [] and with computed input tensors: input[2] = <4>.
 CODE I am using:

   f_img_1= nib.load(time01.nii.gz')
   f_img_2= nib.load(time02.nii.gz')

   img_data_1 = f_img_1.get_fdata()
   img_data_2 = f_img_2.get_fdata()

   #vol_shape: (365, 256, 256)

# my data is with the above shape, but the pre-trained model throws many errors with shapes rather than 160 x 192 x 224

   vol_shape = (160, 192, 224)

   nb_features = [
       [16, 32, 32, 32],
       [32, 32, 32, 32, 32, 16, 16]
    ]

    vxm_model = vxm.networks.VxmDense(vol_shape, nb_features, int_steps=0);

    val_input = [
        img_data_1[np.newaxis, ..., np.newaxis],
        img_data_2[np.newaxis, ..., np.newaxis]
    ]

    vxm_model.load_weights('/brain_3d.h5')

    val_pred = vxm_model.predict(val_input);

**Comment by adalca** [comment]
The model is indeed trained with a different size. You can *try* to register your images, but you'll need to pad them to be of a size that is a multiple of 32, so maybe [384, 256, 256]

**Comment by Ehsan-data** [comment]
I changed the shape of my images and it did work, however, the registration results are not good. I am using 3d FLIR images, would you know if this could create any problems. As far as I know, the pre-trained model is trained for aT1 images.

Also, I am not sure if the image intensity has anything to do with it.

cheers,

**Comment by adalca** [comment]
ok, you should definitely try the synthmorph models or train your own model. We'll continue in #410
