### ISSUE TITLE
registering  3-D FLAIR  images using pre-trained models

### ISSUE THREAD

**Issue by Ehsan-data** [voxelmorph/voxelmorph#411]
### Discussed in https://github.com/voxelmorph/voxelmorph/discussions/410

<div type='discussions-op-text'>

<sup>Originally posted by **Ehsan-data** March 30, 2022</sup>
Hi there,

I wonder if using the pre-trained models would create any issue when registering  3-D FLAIR  images instead of T1 weighted images. I used the pre-trained model "brain_3d.h5" to register my MRI images, and the results were not good. 

Also, come to my mind if my image intensity needs to be within a particular range?

Cheers</div>

**Comment by adalca** [comment]
I've replied in #410  and will close this -- I think you can use synthmorph models to try this.
