### ISSUE TITLE
ModuleNotFoundError: No module named 'pystrum.pytools.patchlib'

### ISSUE THREAD

**Issue by Ehsan-data** [voxelmorph/voxelmorph#412]
Hi Guys,

For some reason, anytime I try to import Voxlemorph, Python throwes below error:

ModuleNotFoundError: No module named 'pystrum.pytools.patchlib'
 
It used to work perfectly but not quite sure what happened. I searched a lot and reinstalled pytools but error doe not seem to be solved. I was wondering If any of you have come across this? 

Cheers

**Comment by adalca** [comment]
I have not -- did you try just pulling new versions of vxm, neurite and pystrum, and then set the python paths right?

**Comment by codefwer** [comment]
i also meet the same problem, have you solved it?

**Comment by adalca** [comment]
@codefwer did you try just pulling new versions of vxm, neurite and pystrum, and then set the python paths right?
