### ISSUE TITLE
How to change the test file to test the hypermorph trained model？

### ISSUE THREAD

**Issue by eleplantttt** [voxelmorph/voxelmorph#417]
I use the oasis dataset,there is my file configuration
![image](https://user-images.githubusercontent.com/76862982/162219283-f125cd9f-66f0-4d36-879e-eb1e389e8296.png)

![image](https://user-images.githubusercontent.com/76862982/162219176-5108a27d-2381-40de-a3e4-4e9660dcc524.png)
This is my mistake
ValueError: Layer model_1 expects 3 input(s), but it received 2 input tensors. Inputs received: [<tf.Tensor 'IteratorGetNext:0' shape=(None, 160, 192, 224, 1) dtype=float32>, <tf.Tensor 'IteratorGetNext:1' shape=(None, 160, 192, 224, 1) dtype=float32>]
![image](https://user-images.githubusercontent.com/76862982/162218118-8b761425-bd6e-4a64-8c91-35c5d5c3e4c6.png)

**Comment by eleplantttt** [comment]
The other inputs is the hyp_input?[None,1]

**Comment by eleplantttt** [comment]
Is there any scripts to test hypermorph?      test_hypermorph.py?

**Comment by ahoopes** [comment]
> The other inputs is the hyp_input?[None,1]

Sorry for the delay, but yes, this is correct.

> Is there any scripts to test hypermorph? test_hypermorph.py?

No complete hypermorph test script at the moment, but the final lines in `train_hypermorph.py` are template code for custom evaluation. I am currently working on a few scripts for generically testing the hypermorph models
