### ISSUE TITLE
ValueError: Unknown loss function:recon_loss

### ISSUE THREAD

**Issue by white-hy** [voxelmorph/voxelmorph#42]
Dear author,I have trained my model with train_miccai2018.py and output a lot of files :
![image](https://user-images.githubusercontent.com/33248778/57193954-884a3e80-6f73-11e9-87cd-3e838e22406c.png)
I want to use my model to register a pair of images, so I run ```python register.py --gpu 0 ../data/test_vol.nii.gz ../data/atlas_norm.nii.gz --out_img ../data/out.nii.gz --model_file ../models/15.h5``` ,but I got an error: 
![image](https://user-images.githubusercontent.com/33248778/57194088-17a42180-6f75-11e9-8c3e-ee1c72b406dc.png)
Please forgive me for some low-level questions.

**Comment by adalca** [comment]
hi @white-hy , 

did you change anything in the training file?
Do you get the same error with the provided miccai model? Specifically, can you do 
```
python register.py --gpu 0 ../data/test_vol.nii.gz ../data/atlas_norm.nii.gz --out_img ../data/out.nii.gz --model_file ../models/miccai2018_10_02_init1.h5
```

**Comment by white-hy** [comment]
@adalca Thank you for your quick reply.
I did not change the training file.
I ran ```python register.py --gpu 0 ../data/test_vol.nii.gz ../data/atlas_norm.nii.gz --out_img ../data/out.nii.gz --model_file ../models/miccai2018_10_02_init1.h5``` without any error.
I changed ```register.py``` to this
![image](https://user-images.githubusercontent.com/33248778/57195934-60b2a080-6f8a-11e9-8280-316eec0f468f.png)
I ran ```python register.py --gpu 0 ../data/test_vol.nii.gz ../data/atlas_norm.nii.gz --out_img ../data/out.nii.gz --model_file ../models/15.h5``` and then I got  the correct result

**Comment by white-hy** [comment]
@adalca Thank you for your quick reply.
I did not change the training file.
I ran```python register.py --gpu 0 ../data/test_vol.nii.gz ../data/atlas_norm.nii.gz --out_img ../data/out.nii.gz --model_file ../models/miccai2018_10_02_init1.h5``` without any error.
I changed register.py to this:
![image](https://user-images.githubusercontent.com/33248778/57196030-665cb600-6f8b-11e9-98a5-c2390d7499c8.png)
I ran ```python register.py --gpu 0 ../data/test_vol.nii.gz ../data/atlas_norm.nii.gz --out_img ../data/out.nii.gz --model_file ../models/15.h5``` and then I got the correct result

**Comment by adalca** [comment]
@white-hy great, thanks for the update! We've also added these to our `register.py` now.

**Comment by DownStone** [comment]
@white-hy  the same problem occurs to me,can you tell me which version of tensorflow,keras and so on,you use?

**Comment by adalca** [comment]
@DownStone did you try adding the two custom entries to the `custom_layers` variable, as @white-hy recommends?

**Comment by DownStone** [comment]
@adalca I used the lastest code,but one error occured:
```
Traceback (most recent call last):
  File "/data/home/amaxcuda8/anaconda2/envs/afei_py35/lib/python3.5/site-packages/tensorflow/python/ops/array_ops.py", line 1757, in ones
    tensor_shape.TensorShape(shape))
  File "/data/home/amaxcuda8/anaconda2/envs/afei_py35/lib/python3.5/site-packages/tensorflow/python/framework/constant_op.py", line 256, in _tensor_shape_tensor_conversion_function
    "Cannot convert a partially known TensorShape to a Tensor: %s" % s)
ValueError: Cannot convert a partially known TensorShape to a Tensor: (1, ?, ?, ?, 3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "register.py", line 102, in <module>
    register(**vars(args))
  File "register.py", line 65, in register
    net = keras.models.load_model(model_file, custom_objects=custom_objects)
	...
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got None of type '_Message' instead.
```

I have searched the error above online, and someone notes that maybe a version error,so I want to know the environment about your code.

**Comment by white-hy** [comment]
@DownStone I'm really sorry for my late reply. My tensorflow-gpu version is 1.6.0,and kares version is 2.2.4.

**Comment by DownStone** [comment]
@white-hy Thanks for you reply. : )

**Comment by qiheihelan** [comment]
@white-hy I have also started to learn this framework recently. I want to register other parts, but there are too many programs. I don't know what to do first. Can you give me some advice? Or add a qq2834728654, want to learn together.

**Comment by adalca** [comment]
@qiheihelan, teaming up with others sounds great, bu also keep in mind that there is a readme that tells you how to get started -- for example, how to train the model if you have your own data, or how to register images if you want to use the pre-trained brain models.

**Comment by qiheihelan** [comment]
Thank you very much for your reply
What is the name of the self-reported article? Let me study.Thanks


------------------ 原始邮件 ------------------
发件人: "Adrian Dalca"<notifications@github.com>;
发送时间: 2019年7月12日(星期五) 晚上7:57
收件人: "voxelmorph/voxelmorph"<voxelmorph@noreply.github.com>;
抄送: "2834728654"<2834728654@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [voxelmorph/voxelmorph] ValueError: Unknown lossfunction:recon_loss (#42)




@qiheihelan, teaming up with others sounds great, bu also keep in mind that there is a readme that tells you how to get started -- for example, how to train the model if you have your own data, or how to register images if you want to use the pre-trained brain models.

**Comment by adalca** [comment]
https://github.com/voxelmorph/voxelmorph/blob/master/README.md

**Comment by JCFu** [comment]
Hi @DownStone ,
I have the same problem as you,  could you tell me how you solve it?
