### ISSUE TITLE
about npz

### ISSUE THREAD

**Issue by turnnext** [voxelmorph/voxelmorph#424]
Is there one nii or many nii files in the NPZ file？

**Comment by adalca** [comment]
can you provide more information? which npz file?

**Comment by ha5750** [comment]
For unsupervised registration, npz files are optional as the voxelmorph can handle other file formats as nii, nii.gz, etc. For semi-supervised, for each pair of volume and corresponding segmentation file,  you want to save them as a single npz file with two headers vol and seg. For better understanding, you might wanna take a look at the source code load_volfile() function in  /voxelmorph/py/utils.py, which is used almost always for data loading.

**Comment by turnnext** [comment]
Thank you，I understand.^^

**Comment by jondo** [comment]
I suggest closing this issue.
