### ISSUE TITLE
Conversion of H5 model to PyTorch (SynthMorph)

### ISSUE THREAD

**Issue by EvanBeal** [voxelmorph/voxelmorph#425]
Hello ! 
I have been working with the SynthMorph method for the past few months and it has allowed me to get really accurate registration results. So thank you very much for providing this innovative approach to registration and for making the code available.

## **Task** (what are you trying to do/register?)

Now, I have some models that I have trained with the TensorFlow implementation of the method and I would like to convert these models (.h5) into PyTorch models (.pt).

## **What have you tried**

So, I used the PyTorch architecture of the registration model available in this repository ([VxmDense](https://github.com/voxelmorph/voxelmorph/blob/dev/voxelmorph/torch/networks.py#L147)) to build the model and then assigned the trained weights layer by layer. 

This was done using the following code:
```
import os

# Import the Keras model and copy the weights
import voxelmorph as vxm
tf_model = vxm.networks.VxmDense.load('model/shapes-dice-vel-3-res-8-16-32-256f.h5', input_model=None)
weights = tf_model.get_weights()

# import VoxelMorph with pytorch backend
import importlib
import torch
os.environ['VXM_BACKEND'] = 'pytorch'
importlib.reload(vxm)

# ---- CONVERT THE KERAS/TENSORFLOW H5 MODEL TO PYTORCH ---- #

# Build a Torch model and set the weights from the Keras model
reg_args = dict(
    inshape=[160, 160, 192],
    int_steps=5,
    int_downsize=2,   # same as int_resolution=2, in keras model
    unet_half_res=True,  # same as svf_resolution=2, in keras model
    nb_unet_features=([256, 256, 256, 256], [256, 256, 256, 256, 256, 256])
)
# Create the PyTorch model
pt_model = vxm.networks.VxmDense(**reg_args)

# Load the weights onto the PyTorch model
i = 0
i_max = len(list(pt_model.named_parameters()))
torchparam = pt_model.state_dict()
for k, v in torchparam.items():
    if i < i_max:
        print("{:20s} {}".format(k, v.shape))
        if k.split('.')[-1] == 'weight':
            torchparam[k] = torch.tensor(weights[i].T)
        else:
            torchparam[k] = torch.tensor(weights[i])
        i += 1

pt_model.load_state_dict(torchparam)

# Save the PyTorch model
torch.save(pt_model, 'pt_smshapes.pt')
```

The problem I am facing is that the PyTorch registration model leads to poor registration results that differ from the accurate results obtained with the TensorFlow model. 

Therefore, I was wondering if you had any ideas on why the observed differences in the registration results of the two models might be created? And if you have tried to do such a conversion with your models? 

Thank you !

## **Details of experiments**

Here you can find the code I used to load and apply the PyTorch model and the TensorFlow model (in addition to the part used to do the conversion between the H5 and PT model). 

<details>
  <summary>Code</summary>
  
```
import os

# Import the Keras model and copy the weights
import voxelmorph as vxm
tf_model = vxm.networks.VxmDense.load('model/shapes-dice-vel-3-res-8-16-32-256f.h5', input_model=None)
weights = tf_model.get_weights()

# import VoxelMorph with pytorch backend
import importlib
import torch
os.environ['VXM_BACKEND'] = 'pytorch'
importlib.reload(vxm)

# ---- FIRST PART - CONVERT THE KERAS/TENSORFLOW H5 MODEL TO PYTORCH ---- #

# Build a Torch model and set the weights from the Keras model
reg_args = dict(
    inshape=[160, 160, 192],
    int_steps=5,
    int_downsize=2,   # same as int_resolution=2, in keras model
    unet_half_res=True,  # same as svf_resolution=2, in keras model
    nb_unet_features=([256, 256, 256, 256], [256, 256, 256, 256, 256, 256])
)
# Create the PyTorch model
pt_model = vxm.networks.VxmDense(**reg_args)

# Load the weights onto the PyTorch model
i = 0
i_max = len(list(pt_model.named_parameters()))
torchparam = pt_model.state_dict()
for k, v in torchparam.items():
    if i < i_max:
        print("{:20s} {}".format(k, v.shape))
        if k.split('.')[-1] == 'weight':
            torchparam[k] = torch.tensor(weights[i].T)
        else:
            torchparam[k] = torch.tensor(weights[i])
        i += 1

pt_model.load_state_dict(torchparam)

# Save the PyTorch model
torch.save(pt_model, 'pt_smshapes.pt')

# ---- SECOND PART - USE THE PYTORCH MODEL FOR REGISTRATION ---- #

import numpy as np
import nibabel as nib
from nilearn.image import resample_img

# Load preprocessed data (scaled between 0 and 1 and with the moving data in the space of the fixed one)
fixed = nib.load("data_processed_time_analysis/data2/sub-geneva06/anat/sub-geneva06_T1w.nii.gz")
moving = nib.load("data_processed_time_analysis/data2/sub-geneva06/anat/sub-geneva06_T2w.nii.gz")
# N.B.
# These data are in my local computer but any data could be used to perform the same analysis.
# It only needs to be scaled and set in a common space

# Load the PyTorch model and specify the device
device = 'cpu'
pt_model_inference = torch.load('pt_smshapes.pt')
pt_model_inference.eval()

# Prepare the data for inference
data_moving = np.expand_dims(moving.get_fdata()[:160, :160, :192].squeeze(), axis=(0, -1)).astype(np.float32)
data_fixed = np.expand_dims(fixed.get_fdata()[:160, :160, :192].squeeze(), axis=(0, -1)).astype(np.float32)
# Set up tensors and permute for inference
input_moving = torch.from_numpy(data_moving).to(device).float().permute(0, 4, 1, 2, 3)
input_fixed = torch.from_numpy(data_fixed).to(device).float().permute(0, 4, 1, 2, 3)

# Predict using PyTorch model
moved, _ = pt_model_inference(input_moving, input_fixed, registration=True)
moved_data = moved[0][0].detach().numpy()
moved_nifti = nib.Nifti1Image(moved_data, fixed.affine)
nib.save(moved_nifti, 'registered_data_pytorch.nii.gz')

# ---- THIRD PART - USE THE TENSORFLOW/KERAS MODEL FOR REGISTRATION ---- #

moved, _ = tf_model.predict([data_moving, data_fixed])
moved_data = moved.squeeze()
moved_nifti = nib.Nifti1Image(moved_data, fixed.affine)
nib.save(moved_nifti, 'registered_data_tensorflow.nii.gz')
```
</details>

And here is an example of registration results using either the TensorFlow model (accurate registration) or the PyTorch model (poor registration). In this example, the registration is done with the `sm-shapes` model available in this [repo](https://github.com/voxelmorph/voxelmorph/tree/dev/data#models) and using publicly available data from the [spine-generic dataset](https://github.com/spine-generic/data-multi-subject#spine-generic-public-database-multi-subject). 

<details>
  <summary>Example: multimodal intra subject spinal cord data registration</summary>
  
### Before registration
![ezgif com-gif-maker - 2022-05-10T144008 661](https://user-images.githubusercontent.com/32447627/167631766-7dec1ea5-8a1d-4b4b-979f-7caa8d267853.gif)

### TensorFlow model registration
![ezgif com-gif-maker - 2022-05-10T144316 992](https://user-images.githubusercontent.com/32447627/167631877-e00e94be-07a3-45b7-9e97-7260f45800f0.gif)

### PyTorch model registration
![ezgif com-gif-maker - 2022-05-10T144139 126](https://user-images.githubusercontent.com/32447627/167631945-1805ccfb-4251-42b6-9e3d-44d25d1d2037.gif)

</details>

**Comment by adalca** [comment]
Thanks for letting us know. Tagging @mu40 on this as he will know more!

**Comment by mu40** [comment]
This is great, we're glad to hear that SynthMorph is useful to you! You may not want to reverse the order of all dimensions of the kernel weights with `weights[i].T`, but instead try to only move the input/output dimensions with something like `torch.movedim(weights[i], (-1, -2), (0, 1))`.

**Comment by EvanBeal** [comment]
> try to only move the input/output dimensions with something like torch.movedim(weights[i], (-1, -2), (0, 1))

Amazing ! It works perfectly. You are right the issue was to reverse the order of all dimensions of the kernel weights and by modifying this part with your suggestion, it allows to obtain models producing the same registration results. 

Thank you very much @mu40  !
