### ISSUE TITLE
hypermorph  demo

### ISSUE THREAD

**Issue by eleplantttt** [voxelmorph/voxelmorph#427]
I tryed to run the demo you offered in colab(https://surfer.nmr.mgh.harvard.edu/ftp/docs/hypermorph/)

![image](https://user-images.githubusercontent.com/76862982/167992043-0842ef03-abac-4331-93f4-ff4061035685.png)

but there is a problem, I want to know how to solve it. Is this bug  my mistake or the reason of  my colab setting?

![image](https://user-images.githubusercontent.com/76862982/167991772-875afcf4-9041-40a1-8065-6e2d194a2eb5.png)

thans for your great work!

**Comment by ahoopes** [comment]
I'm getting the same error. Seems to be related to a h5py bug, and it probably came about once colab updated to python 3.7 internally. I'll look into fixing it

**Comment by ahoopes** [comment]
I take it back - this was my bad! The error was related to model configuration changes from a bit ago. I just updated the colab to use explicit versions of the github code.
