### ISSUE TITLE
pystrum, nibabel, neurite

### ISSUE THREAD

**Issue by codefwer** [voxelmorph/voxelmorph#429]
where are these three package  ,i dont exactly know that why the branch 'dev' dont have pystrum, nibabel, neurite files. so when i download the code zip to my local, and it will show no module named 'pystrum'

**Comment by adalca** [comment]
They are all on pip.

If you'd like to download latest versions, you can get them from here:
nibabel from pip
neurite: https://github.com/adalca/neurite/
pystrum: https://github.com/adalca/pystrum/
