### ISSUE TITLE
Update PyPI Release 

### ISSUE THREAD

**Issue by kousu** [voxelmorph/voxelmorph#432]
Hi there! @evanbeal has built a feature on your groundbreaking work for our [spinalcordtoolbox](https://github.com/spinalcordtoolbox/spinalcordtoolbox). We'd like to publish it as part of spinalcordtoolbox so our users can get better, but we've hit a [stumbling](https://github.com/voxelmorph/voxelmorph/issues/228#issuecomment-1128034462) [block](https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3760#issuecomment-1128045208), that the only version on PyPI is from 2 years ago:

[![pypi: voxelmorph](https://user-images.githubusercontent.com/987487/168907686-0f28b3f4-f715-4c74-b336-1bac8711c598.png)](https://pypi.org/project/voxelmorph/#history)

Would you be willing to take some time to publish an updated release to PyPI so that we can build on it? We'd be really excited to turn this research into practical medical tools for our users.

Evan was able to build on voxelmorph by installing from your GitHub, but our users don't have that kind of training, so we need them to be able to use a standard package with standard dependencies.

**Comment by ahoopes** [comment]
Hi @kousu, we have just released a new voxelmorph (0.2) version to pypi, which includes all changes in the development branch as of June 2nd. Hope this helps!

**Comment by kousu** [comment]
Wonderful, thank you!
