### ISSUE TITLE
Voxelmorph-diff(2019(for images and surfaces), 2018(Fast Probabilistic Diffeomorphic Registration) papers) Table 1

### ISSUE THREAD

**Issue by Joeycho** [voxelmorph/voxelmorph#436]
Dear authors,

First of all, thanks for the work. I've started to read Voxelmorph-related papers and I'm excited about the project.

I am not sure whether I find the right place to report something about papers, but I hope it will reach to you somehow.

Caption for Table 1, Voxelmorph-dff description comes with
"while also having nearly zero **non-negative** Jacobian locations". For me, zero **non-positive** Jacobian locations makes more sense and matches with the Table 1. Is it still true statement, "while also having nearly zero **non-negative** Jacobian locations"?

If it is, would you mind to explain it to me?

**Comment by adalca** [comment]
Hi @Joeycho 
Can you specify which paper PDF you're looking at?

In general, a jacobian determinant that is negative indicates a folding in deformations, which we don't want. Therefore we wish to have as few of these as possible.

**Comment by Joeycho** [comment]
https://arxiv.org/abs/1903.03545 : Unsupervised Learning of Probabilistic Diffeomorphic Registration for Images and Surfaces(Table 1, page 7)
https://arxiv.org/abs/1805.04605 : Unsupervised Learning for Fast Probabilistic Diffeomorphic Registration (table 1, page 6)

Thanks for quick reply!
Yes, that's how I understood, there I tried to report this inconsistency. It might be still consistent if I misunderstand the statement.

In both paper, there is Table 1 and it describes the summary of result across different methods.

"Only our presented method, VoxelMorph-diff, achieves both high accuracy and fast runtime while also having nearly **zero non-negative Jacobian locations**."

For me, "while also having nearly zero non-**positive** Jacobian locations" seems reasonable rather than the current statement.

**Comment by adalca** [comment]
Edit: oh, i think you're right! we probably meant nearly zero negative jacobian locations....

**Comment by Joeycho** [comment]
I see. @adalca Thanks for your clarification! :)
