### ISSUE TITLE
Can we train model on my data, and use atlas_norm.nii ,test_vol.nii and test_seg to test it.

### ISSUE THREAD

**Issue by hassaanmahmood** [voxelmorph/voxelmorph#44]
for doing that do I need to first register my data to the atlas?
what other steps should I follow please.
thanks

**Comment by adalca** [comment]
Hi @hassaanmahmood 

It depends on the data, but if your data is significantly different, you probably couldn't use the test_vol as a reliable test. If the data is very similar then you can, and I would recommend you affinely register the data to our atlas to start indeed. 

If you'd like to use our pre-trained models, you should carry out the pre-processing described in the paper. If you'd like to avoid doing this and would like to try your own preprocessing, then I would recommend you train your own model.

**Comment by hassaanmahmood** [comment]
Thanks a lot @adalca
Sorry for asking too basic question. in this image my image is white , and your atlas overlay is in red color. 
how can I get them in similar view? after getting them in same space I will do affine registration.

**Comment by hassaanmahmood** [comment]
may be there is problem with uploading the  image. Actually sagittal plane of my data is corresponding to coronal of your atlas. when I overlaid them in Mango software to view. What can I do solve this please.
thanks

**Comment by hassaanmahmood** [comment]
Thanks a lot. 
your atlas size is (160, 192, 224)
my subject size is (144, 192, 256)
Am I right in my steps to make my image like yours one.
1- orientation 
2- resize/resample
3- affine registration
How can I achieve these steps.
Also please , as you said in the paper "All scans were resampled to a 256x256x256
grid with 1mm isotropic voxels. .... and
crop the resulting images to 160 x 192 x 224."
does crop mean resampling?

**Comment by adalca** [comment]
seems right

for orientation i would use `numpy.transpose`
for affine registration you can use something like [ANTs registration](http://stnava.github.io/ANTs/). if you register to our provided atlas, you don't have to crop. See [*Notes on Data*](https://github.com/voxelmorph/voxelmorph#notes-on-data) for more details.

**Comment by hassaanmahmood** [comment]
Thanks for your comments. I have data without skull stripped. I am using free surfer, but getting inadequate stripping, some portion of eyes included in the mask and also some part of boundaries of brain has been removed by free surfer. 
1-should I use any other tool for skull striping?  Or I have to go through different parameters for watershed. 
2- it is taking more than 12 hours per volume even if I use  -autorecon1 option.
3- Also can you please guide me how to resize the volume.

**Comment by adalca** [comment]
1. What sort of data do you have? There are many skull strippers out there, and it depends on your data. If some of the images were well skull stripped with FreeSurfer, you could simpley train your own UNet to segment the brain

2. Yes, if you'd like to reproduce our exact pipeline *and* evaluate the data on segmentations, FreeSurfer takes a long time. Note that this is not completely necessary for VM. What you need for voxelmorph is affine registration and intensity normalization. Skull stripping is suegul, but 100% necessary.

3. I'm not sure I understand the question. if you are using your own atlas (or doing subject-to-subject) registraiton, your image sizes are fine. If you would like to resize an image, you can look at `scipy.ndimage.interplation.zoom` for python or `resize` in `https://github.com/adalca/neuron/blob/master/neuron/utils.py` for tensorflow.

**Comment by hassaanmahmood** [comment]
I will be using ADNI dataset.
Its a naive question, Just want to confirm from your experience. As far I learned from the issues,
 1- Freesurfer is not mandatory for training data pre-processing. 

 2- if yes, we can do it in any software by doing 
     a-intensity normalization  
     b- skull stripping
     c- affine registration to your atlas

3- if we use freesurfer , Can training data be prepared by only running Autorecon1 option in recon-all Or we have to run complete recon-all pipeline for training data preprocessing?

4- If we use other software for pre-processing of training data and freesurfer for Test data preparation( because we want segmentations), Is it good idea to do that? I only want segmentation to compare my results, for that I need to do it with freesurfer. 

5- If using different software for training and test data is ok, will difference in Intensity normalization and skull stripping create problem in performance. if yes how can we reduce it.

Can you please tell me where I am wrong in my understanding.
Looking forward for your guidance. 
thanks
Hassan

**Comment by adalca** [comment]
1. True
2. True -- in fact, I don't think all of that is always necessary, and I would say we're probably days away from releasing our own steps for 2a and 2c with voxelmorph.
3. I think this should be fine
4. Well I'm not sure of the resulting behaviour to be honest. It's best to have train/val/test all with the same processing -- so I think 5. is moot, then

**Comment by hassaanmahmood** [comment]
I tried with a sample MRI . run complete recon-all . and used brain.mgz and aseg.mgz as my test_vol and test_seg respectively. 
But I am getting very low dice score, I am sure doing something fishy here. Can you please have a look . 
What I am missing here please. I also attached the pdf version of my notebook.
[notebook.pdf](https://github.com/voxelmorph/voxelmorph/files/3506477/notebook.pdf)

`

# py imports
import os
import sys
import glob
from argparse import ArgumentParser

# third party
import tensorflow as tf
import numpy as np
import keras
from keras.backend.tensorflow_backend import set_session
import nibabel as nib
import scipy.io as sio
from scipy.interpolate import interpn
sys.path.append('../ext/medipy-lib')
import medipy
from medipy.metrics import dice
import datagenerators

# project
import networks
sys.path.append('../ext/neuron')
import neuron.layers as nrn_layers
import matplotlib.pyplot as plt

Using TensorFlow backend.

moving= '/home/hassan/Work/test5/mri/brain.mgz'  # from freesurfer recon-all
test_seg='/home/hassan/Work/test5/mri/aseg.mgz' # from freesurfer recon-all
model_file= '/home/hassan/Work/voxelmorph/models/cvpr2018_vm2_cc.h5'

labels = sio.loadmat('../data/labels.mat')['labels'][0]
atlas = np.load('../data/atlas_norm.npz')
atlas_vol = atlas['vol']
atlas_seg = atlas['seg']
atlas_vol = np.reshape(atlas_vol, (1,)+atlas_vol.shape+(1,))

mov_nii = nib.load(moving)  # from freesurfer recon-all
mov = mov_nii.get_data()
mov = mov/255                #normalizing
print(mov.shape)
mov = mov[48:-48,31:-33,3:-29]
print(mov.shape)
mov=mov[np.newaxis,..., np.newaxis]
plt.imshow(mov[0,100, :, :,0])
mov.shape
np.amax(mov)

(256, 256, 256)
(160, 192, 224)

0.7372549019607844

custom_layers = {'SpatialTransformer':nrn_layers.SpatialTransformer,
                 'VecInt':nrn_layers.VecInt,
                 'Sample':networks.Sample,
                 'Rescale':networks.RescaleDouble,
                 'Resize':networks.ResizeDouble,
                 'Negate':networks.Negate}

net = keras.models.load_model(model_file, custom_objects=custom_layers)

/home/hassan/anaconda3/envs/tf3.6/lib/python3.6/site-packages/keras/models.py:282: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '

pred = net.predict([mov, atlas_vol])

X_seg = nib.load(test_seg).get_data()   # from freesurfer recon-all
X_seg = X_seg[48:-48,31:-33,3:-29]
X_seg = X_seg[np.newaxis, ..., np.newaxis]
plt.imshow(X_seg[0,100, :, :,0])
np.amax(X_seg)

255

vol_size=(160,192,224)
nn_trf_model = networks.nn_trf(vol_size, indexing='ij')
warp_seg = nn_trf_model.predict([X_seg, pred[1]])[0,...,0]
vals, _ = dice(warp_seg, atlas_seg, labels=labels, nargout=2)#
print(np.mean(vals), np.std(vals))

0.3480438429552605 0.24704607653702573

 

`

**Comment by adalca** [comment]
- you should try using norm.mgz since that's what we used, just to compare directly.
- can you visualize `atlas_seg` and `X_seg` and `warp_seg` in subplots? or using `neuron.plot.slices` ?

**Comment by hassaanmahmood** [comment]
Thanks a lot for your response. Would there be any wrong with my preprocessing in this notebook. in freesurfer , I ran complete recon-all. we are using sample from adni.

This time I tried with norm.mgz of the same subject.
Using neuron.plot.slices, there are plots at the end of the attached document.
[notebook_6.pdf](https://github.com/voxelmorph/voxelmorph/files/3509698/notebook_6.pdf)

**Comment by adalca** [comment]
@hassaanmahmood almost there, can you add colorbars and the moving *image*?

I think the low Dice might just be an issue of different labels in the different files, somehow...

**Comment by hassaanmahmood** [comment]
@adalca  Hi, are you asking me to do something like this in the figure below?  I also added the moving image.
Thanks
![image](https://user-images.githubusercontent.com/20740538/63232824-254c9100-c25e-11e9-9ce8-e9593f605552.png)

**Comment by adalca** [comment]
Sorry, I guess I meant the `moved` image.
So have something like:

```
moving_img | fixed_img | moved_img
moving_seg | fixed_seg | moved_seg
```
with the top cmaps being grayscale
and the bottom all being the same (e.g. inferno)

Basically, I'm not sure I understand what's going on with the labels -- they don't seem bad at all after warp, so I'm trying to understand if there's just simply an issue with some inconsistent labels being used.

**Comment by hassaanmahmood** [comment]
Thanks for your time. 
1-  Just confirming my understanding. there is difference of sharpness in getting moved image from `warp_mov = nn_trf_model.predict([mov, pred[1]])[0,...,0]` 
![image](https://user-images.githubusercontent.com/20740538/63317732-8fd8fc00-c346-11e9-8341-ecd63c294b84.png)

and getting it using directly  `[moved, warp] = net.predict([mov, atlas_vol])` . 
![image](https://user-images.githubusercontent.com/20740538/63317722-88195780-c346-11e9-8b3f-a192fcdea5a4.png)
Is this difference meant to be there?

2- here I am getting moved_img by `[moved, warp] = net.predict([mov, atlas_vol]) `  
`moving_img| fixed_img | moved_img `
                 `moving_seg | fixed_seg | moved_seg`
![image](https://user-images.githubusercontent.com/20740538/63317858-f6f6b080-c346-11e9-9a8a-46b20778fa92.png)

3- So Sorry for my previous comment.. This data is sample from IXI Dataset . But I am getting similar result on ADNI too. Preprocessing is done by complete recon-all . 
4- When I overlayed images in MRIcron...... my moving brain is translated and not aligned with `atlas_norm`. where as from matplotlib we can not see this difference,
gray is my input sample
red is norm.mgz from fress surfer
blue is your atlas_norm.

![image](https://user-images.githubusercontent.com/20740538/63319978-ab480500-c34e-11e9-814f-f9176d1bd700.png)

thanks for your time and looking into this problem.

**Comment by adalca** [comment]
Hi @hassaanmahmood ,
1. Yes, you would lose sharpness with a moved image, since the warp uses linear interpolation (you could also use NN interpolation, but I don't recommend that for warping images.

2. I think this is an issue with extracting the right labels -- it seems that your warped segmentations is using the freesurfer label IDs and your fixed is in [0, 31]. Can you make sure that for your warped segmentation, you re-mapped the labels according to `labels.mat`? 

4. Looks like a header issue -- how did you save the `nii` of the warped image and which `nii` are you using for the atlas?

**Comment by hassaanmahmood** [comment]
@adalca Thanks
Do you mean swapping of label IDs which I get from freesurfer in aseg?
2. How can I  remap the labels according to  labels.mat .  
3. I am using `atlas_norm.nii.gz` as atlas and I am saving  warped image as 
`img = nib.Nifti1Image(moved[0,...,0], mov_nii.affine)`
`nib.save(img,out_img)`

**Comment by adalca** [comment]
*I actually don't think you should remap* If you wanted to remap, labels.mat will contains a list of 30 labels, giving you the remap E.g. if the list is [0, 7, 9] then label 7 becomes label 1, label 9 becomes label 2, etc. But actually you shouldn't need to do this.

in the code above you make it look like the fixed image is the atlas. However, the atlas provided with voxelmorph does not have segmentations in the range [0, 30] as your colorbar shows, but actually goes all the way up to 85 (it's the same as the aseg). So I think you've done something weird here, perhaps over-written the atlas segmentation or using the wrong file or something? I believe this will fix your issue.

3. I'm afraid i'm not sure about this, it's a header issue and I'm not familiar with how your viewer works.

**Comment by hassaanmahmood** [comment]
Thanks @adalca for the input.
 1-Can you please guide me how can I achieve this, if I want to do it =>
" re-mapped the labels according to labels.mat"
2-I have attached pdf version of my notebook, the slices showing different ranges from different views. I am using freshly downloaded `atlas_norm.npz` for atlas_vol and atlas_seg as fixed image. And using ADNI sample as moving , preprocessed with recon-all. I have displayed all three views. 
3- I displayed slice # 50 from each direction. It seems there is an offset difference between fixed and moving brain. e.g. like axial slice no. 50 of moving image is not visually corresponding to axial slice no. 50 of fixed image(atlas_vol from atlas_norm.npz). Can that be the issue?
[notebook_6_1.pdf.pdf](https://github.com/voxelmorph/voxelmorph/files/3532640/notebook_6_1.pdf.pdf)
4- I am investigating may be there is other issue which I am neglecting.

**Comment by adalca** [comment]
@hassaanmahmood 
1. Please see `_relabel` function in https://github.com/adalca/neuron/blob/master/neuron/generators.py and try to work through it 
2-4 -- I'm not sure what is happening either, but it does seem like there might be (1) an affine shift, and (2) an issue with the labels. Regarding the affine shift I think you could register the images to the atlas affinely using something like ANTs (we also have a tool in voxelmorph for this, but it won't be released for another couple of weeks). You could alternatively build your own atlas from the current dataset using our new tool: https://github.com/voxelmorph/voxelmorph/blob/master/src/train_img_template.py . This will basically train a voxelmorph as well as lean an atlas at the same time. Here's the paper: https://arxiv.org/abs/1908.02738

Unfortunately it seems like in this case voxelmorph is doing well but there's some issues with affine and labels, and we're not able to help at this level of detail as we're preparing for the next big release in a few weeks. I encourage you to explore the ideas above.

**Comment by adalca** [comment]
see also #78 by the way, they might be related.

**Comment by xyzxzj** [comment]
Hi:
  @hassaanmahmood , I have the similiar problem [#78 ](url) with you. I want to communicate with you about this problem, you can also see [#78 ](url) to know my problem.Now, I also use my data to test the model cvpr2018_vm2_cc.h5, I use freesurfer to do the preprocessing:
recon-all -i sub-A00000159/mprage.nii.gz -subjid sub-A00000159 -autorecon1
recon-all -subjid sub-A00000159 -autorecon2
then I extract norm.mgz and aseg.mgz and follow your preprocess steps describe in your paper.
1-intensity normalize to [0-1] for norm.mgz
2-crop for norm.mgz and aseg.mgz
3-affine transformation using FSL flirt for norm.mgz and aseg.mgz
when I use the preprocessed img to test the model,  I have the low dice, 
![image](https://user-images.githubusercontent.com/43518644/63603303-faff2880-c5fb-11e9-8bb0-e775135f40fd.png)
and I suspect that it is a problem with the labels . The follwing is the 
moving_img| fixed_img | moved_img 
moving_seg | fixed_seg | moved_seg
![image](https://user-images.githubusercontent.com/43518644/63603017-4c5ae800-c5fb-11e9-8cbe-b2812b9e7018.png)
and obviously the labels in the seg and in the atlas_seg is different.I want to know if you solved your problem. If it is, it is convenient to tell me how you solved it.

**Comment by xyzxzj** [comment]
Hi:
![image](https://user-images.githubusercontent.com/43518644/63635424-fdfa2780-c694-11e9-947f-3863ddc85bba.png)
 In order to study the position of the image transformation after affine transformation, I added a mark to the origin image. The yellow color in the figure is the mark. The position of mark in the  origin_norm and the position of mark in the origin_norm  are far from the same.  As can been see from atlas_aseg and origin_aseg, the positions of same labels is similiar, but after affine transform, the positions of same labels are different. so maybe this reason make the dice low, could you please help me to solve this problem.

**Comment by hassaanmahmood** [comment]
@xyzxzj  thanks. I am also following your thread. I am still stuck. I am not doing any affine transformation right now as I think it is already doing[ talairach transformation](https://surfer.nmr.mgh.harvard.edu/fswiki/ReconAllTableStableV6.0) to norm and aseg . if I am wrong in this please let me know. 
I am directly using norm and aseg from freesurfer recon-all output. You can also see in my `notebook_6_1.pdf.pdf`  in previous post.
I am using ADNI and IXI sample. preprocess it with freesurfer. and just fed norm and aseg into the model. 
1- to which volume you are doing affine transformation of norm and aseg?
2- In my case When I view saved registered  volume, they are showed as translated and rotated if I view atlas volume and registered volume in MANGO or MRIcron! Do you know what can be the problem?
3- Which freesurfer have you used. I am using 6.0. May be we should try with older one.

Thanks.

**Comment by hassaanmahmood** [comment]
@adalca @xyzxzj After trying some tweaks, The problem was very basic.... Although I was using OASIS data for now... the preprocessed version with freesurfer... I need to affinely register the cropped norm.mgz and cropped aseg.mgz to Atlas. And problem solved.
But I do not know that as freesurfer is doing talairach transform on norm.mgz and Atlas was created using freesurfer processed volumes, Why do we need to affinely register...
but anyhow affine registration after croping,  solved the problem.
thanks a lot for your different insights @adalca . it helped me to better understand the system.

**Comment by adalca** [comment]
@hassaanmahmood 
Thanks for the update
By default, FreeSurfer will compute the transform to talairach, but won't actually warp the norm.mgz. Anyway, I am glad it worked out for you!

**Comment by hassaanmahmood** [comment]
@adalca  
 hi , thanks a lot for your guidance. Pardon as I do not know whether I should start a new thread. But its related to my question in title.
I am training cvpr version using train.py and during training I am getting 3.71MB size of saved model after each epoch.  where as your model is of 1.28 MB size.
Am I doing some mistake here?
thanks.

**Comment by adalca** [comment]
which model version (vm1, vm2, vm2double) are you running?

**Comment by hassaanmahmood** [comment]
I am running train.py with vm2.

**Comment by adalca** [comment]
I guess one more question: are you saving using `save_model` or `save_weights`?

**Comment by hassaanmahmood** [comment]
1-I am calling this as in the code "save_callback = ModelCheckpoint(save_file_name)", saving model for each epoch.  Oh... my bad... So it is saving model.... not only weights ? Did I get it right.

2-How can I load it to test. right now I am getting this error with `net1 = keras.models.load_model(model_file_with_pre, custom_objects=custom_layers)` 
ValueError: Unknown loss function:loss

3- I tried for now only with OASIS. I got this result for 500 epoch with using pre-trained weights and without it... am I using too much epoch ? what number of epoch you recommend.
Epoch 2/500  without pretrained
100/100 [==============================] - 118s 1s/step - loss: 0.0040 - spatial_transformer_1_loss: 0.0039 - flow_loss: 1.4045e-04

Epoch 500/500 without pretrained
100/100 [==============================] - 126s 1s/step - loss: 0.0037 - spatial_transformer_1_loss: 0.0033 - flow_loss: 4.3052e-04

---------------------------------------------------------------------

Epoch 2/500 with pre-trained /models/cvpr2018_vm2_l2.h5
100/100 [==============================] - 119s 1s/step - loss: 0.0040 - spatial_transformer_1_loss: 0.0038 - flow_loss: 2.2197e-04

Epoch 500/500 with pre-trained /models/cvpr2018_vm2_l2.h5
100/100 [==============================] - 118s 1s/step - loss: 0.0037 - spatial_transformer_1_loss: 0.0033 - flow_loss: 4.3482e-04

Thanks

**Comment by adalca** [comment]
1. It sounds like you're saving the whole model. I'm not sure why the sizes might be different between our files -- perhaps we only saved weights and you're saving the model, although I thought we saved the entire model.

2. to see how to load models, please see see our register.py, there's a good example. An alternative is to build the model you want, and use `model.save_weights()` (see `train.py`, which does this in case you want to give initial weights)

3. We didn't find a need to have a "minimal epoch" -- we usually just let the models run to 1500 epochs, although they do most of the work in the first few (maybe 500) epochs, and from there on out it's just very small fine tuning. Instead of looking at the loss, I would recommend looking at the Dice score (if you have segmentations) over a few validation subjects (e.g. 10)
