### ISSUE TITLE
Do one-hot before computing Dice?

### ISSUE THREAD

**Issue by AXu0511** [voxelmorph/voxelmorph#443]
Is Dice calculated after doing one-hot operation for fixed-segmentation and moved-segmentation?
Looking forward to your reply.
Thanks again for your outstanding work.

**Comment by adalca** [comment]
@AXu0511 please provide more information of what your scenario is
You can compute soft dice on one-hot operation, or hard dice segmentation maps. It depends what you want to do. Both hard and soft dice are available in neurite.metrics
