### ISSUE TITLE
Support for RGB images

### ISSUE THREAD

**Issue by dfvr1994** [voxelmorph/voxelmorph#453]
Similar to https://github.com/voxelmorph/voxelmorph/issues/441

I'm getting an error like `ValueError: Negative dimension size caused by subtracting 2 from 1 for 'vxm_dense_unet_enc_pooling_2/MaxPool3D' (op: 'MaxPool3D') with input shapes: [?,64,64,1,32]`

Mind generating a tutorial for training using RGB images? Or point me to its link?

Thanks

**Comment by adalca** [comment]
are you using tf? If so, you can set the  src_feats and trg_feats to 3, and input images of the size [BS, H, W, 3], and it should work.
I suspect your input images were [BS, H, W, 1, 3] or something like that which caused the error above.

**Comment by dfvr1994** [comment]
So I've loaded my dataset and looks like this: 

`shape of x_train: (80, 512, 512, 3), y_train: (80, 512, 512, 3)` and each image has values between 0 and 1

I'm trying 

```
inshape = x_train.shape[1:]
vxm_model = vxm.networks.VxmDense(inshape, nb_features, int_steps=0,src_feats=3,trg_feats=3)
```
And the error I'm getting is: 

```
ValueError: Exception encountered when calling layer "vxm_dense_unet_enc_pooling_1" (type MaxPooling3D).

Negative dimension size caused by subtracting 2 from 1 for '{{node vxm_dense_unet_enc_pooling_1/MaxPool3D}} = MaxPool3D[T=DT_FLOAT, data_format="NDHWC", ksize=[1, 2, 2, 2, 1], padding="VALID", strides=[1, 2, 2, 2, 1]](Placeholder)' with input shapes: [?,256,256,1,32].

Call arguments received:
  • inputs=tf.Tensor(shape=(None, 256, 256, 1, 32), dtype=float32)
```

Is the nb_features ok? 

```
nb_features = [
    [32, 32, 32, 32],         # encoder features
    [32, 32, 32, 32, 32, 16]  # decoder features
]
```

**Comment by adalca** [comment]
can you try inshape = x_train.shape[1:-1]

inshape has to be the inherent spatial size of your volume, here the 3 
is really a sort of 'number of features', not a spatial dimensions.

**Comment by dfvr1994** [comment]
The model compiled ok. Now I'm getting these when trying to train: 

Warning:
```
Epoch 1/10
WARNING:tensorflow:Model was constructed with shape (None, 512, 512, 3) for input KerasTensor(type_spec=TensorSpec(shape=(None, 512, 512, 3), dtype=tf.float32, name='vxm_dense_source_input'), name='vxm_dense_source_input', description="created by layer 'vxm_dense_source_input'"), but it was called on an input with incompatible shape (None, None, None, None, None).
WARNING:tensorflow:Model was constructed with shape (None, 512, 512, 3) for input KerasTensor(type_spec=TensorSpec(shape=(None, 512, 512, 3), dtype=tf.float32, name='vxm_dense_target_input'), name='vxm_dense_target_input', description="created by layer 'vxm_dense_target_input'"), but it was called on an input with incompatible shape (None, None, None, None, None).
```

Error:
```
ValueError: Exception encountered when calling layer "vxm_dense" (type VxmDense).
    
    Input 0 of layer "vxm_dense_unet_enc_pooling_0" is incompatible with the layer: expected ndim=4, found ndim=5. Full shape received: (None, None, None, None, 32)
    
    Call arguments received:
      • inputs=('tf.Tensor(shape=(None, None, None, None, None), dtype=float32)', 'tf.Tensor(shape=(None, None, None, None, None), dtype=float32)')
      • training=True
      • mask=None
```
What am I missing? 

Thanks for your time

**Comment by adalca** [comment]
what's the exact size of the data going in?

it has to be [B, H, W, 3]

the erros seem to indicate you have an extra dimension

**Comment by dfvr1994** [comment]
On the tutorial the MNIST returns: 

`shape of x_train: (5421, 28, 28), y_train: (5421,)` because `y_train` is a list of 5s.

Mine is returning `shape of x_train: (80, 512, 512, 3), y_train: (80, 512, 512, 3)` because `y_train` is a list of images, could that be causing an error with `vxm_data_generator` ? 

`print(inshape, x_train.shape)` returns: 

`(512, 512) (80, 512, 512, 3)`

```
print('input shape: ', ', '.join([str(t.shape) for t in vxm_model.inputs]))
print('output shape:', ', '.join([str(t.shape) for t in vxm_model.outputs]))
```
returns: 
```
input shape:  (None, 512, 512, 3), (None, 512, 512, 3)
output shape: (None, 512, 512, 3), (None, 512, 512, 2)
```

When doing: 
```
train_generator = vxm_data_generator(x_train)
in_sample, out_sample = next(train_generator)

print(np.array(in_sample).shape)
print(np.array(np.squeeze(out_sample)).shape)
```

I get: 
```
(2, 32, 512, 512, 3, 1)
ValueError: could not broadcast input array from shape (32,512,512,3,1) into shape (32,512,512,3)
```

**Comment by adalca** [comment]
your x_train has an extra dimension than what's in the tutorial, because of the color images. 
If what you did is use the `vxm_data_generator` from the tutorial, then remove the last `np.newaxis` in the `moving_images=...` and `fixed_images=...`. This should dolve it, I believe.
Bottom line, the images going into vxm should be [B, H, W, 3]

**Comment by dfvr1994** [comment]
It gave me this error: `ValueError: Creating variables on a non-first call to a function decorated with tf.function.`

Which I'm not quite sure if it was safe to solve by adding: `tf.config.run_functions_eagerly(True)` 

Training succeeded. Thanks
