### ISSUE TITLE
voxelmorph with affine

### ISSUE THREAD

**Issue by d5423197** [voxelmorph/voxelmorph#471]
Hello author,

Thanks for your contribution. I have read the tutorial. But it does not have affine transformation involved. Is there a VoxelMorph with affine transformation tutorial or how to train VoxelMorph with affine transformation?

Thanks,

ZD

**Comment by adalca** [comment]
You're right we don't have a ton of affine support -- something @mu40 is changing in a publication very soon, and will support it in the code.

**Comment by d5423197** [comment]
Hello there,

Thanks for your reply. I just break into this area. The two images that I want to regist are on a different scale and have some rotation. In my personal innocent opinion, I think this is not rigid registration. This is affine registration. Do you have any suggestions that any paper I can look into? 

best,

ZD

**Comment by adalca** [comment]
Sure, there are a ton of affine registraiton papers. Here's a recent one from @cwmok : https://openaccess.thecvf.com/content/CVPR2022/papers/Mok_Affine_Medical_Image_Registration_With_Coarse-To-Fine_Vision_Transformer_CVPR_2022_paper.pdf

Also, as I mentioned we're about to come out with some analysis by @mu40

**Comment by d5423197** [comment]
Thanks again! Will definitely look into the future work from voxelmorph.
