### ISSUE TITLE
problem training my own model

### ISSUE THREAD

**Issue by X-ma** [voxelmorph/voxelmorph#48]
hi,

I'm trying to train my own model on Mac. 

**First, I used test_vol.npz and atlas_norm.npz to test but I got the error below.**

_Failed to run optimizer ArithmeticOptimizer, stage RemoveStackStridedSliceSameAxis node diffflow/map/while/strided_slice. Error: Pack node (diffflow/map/while/stack_3) axis attribute is out of bounds: 3
 F ./tensorflow/core/util/mkl_util.h:607] Check failed: dims == sizes.size() (5 vs. 4)_

and there is also two warnings,
 
_I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
I tensorflow/core/common_runtime/process_util.cc:71] Creating new thread pool with default inter op setting: 8. Tune using inter_op_parallelism_threads for best performance._

**Then, I also tried to use my own data,** 

_python train_miccai2018.py /Users/xiao/Desktop/lab/software/voxelmorph-master/train  --atlas_file /Users/xiao/Desktop/lab/software/voxelmorph-master/data/atlas.npz --gpu 0 --model_dir /Users/xiao/Desktop/lab/software/voxelmorph-master/mymodel_ 

both atlas.npz and moving.npz are (58, 62, 54) MRI image.

but I got this error,

ValueError: A `Concatenate` layer requires inputs with matching shapes except for the concat axis. Got inputs shapes: [(None, 8, 8, 8, 32), (None, 8, 8, 7, 32)]

Is my problem due to environment?

Could you please help me out? 

Thank you!

**Comment by adalca** [comment]
I haven't seen the previous error and don't really have an intuition for it. Can you tell us exactly what command you ran?

For the second part -- your data size has to be a multiple of 16, since the UNet has 4 downsampling and 4 upsampling levels.  You could, for example, pad your images to the next multiple of 16.

**Comment by X-ma** [comment]
I used this command

_python train_miccai2018.py /Users/xiao/Desktop/lab/software/voxelmorph-master/train --gpu 0 --model_dir /Users/xiao/Desktop/lab/software/voxelmorph-master/mymodel_

in  _/Users/xiao/Desktop/lab/software/voxelmorph-master/train_ there is **test_vol.npz**

**Comment by adalca** [comment]
which gave you the first or the second error?

**Comment by X-ma** [comment]
It gave me the first error. Sorry for the confusion.

**Comment by adalca** [comment]
This setup trains well for me (just tried it). Perhaps you have a very old version of tensorflow? I would recommend looking online, as this seems to be a [tensorflow issue](https://github.com/tensorflow/tensorflow/issues/26769) beyond voxelmorph?

**Comment by X-ma** [comment]
Thank you very much for your help!

**Comment by RitikaAg** [comment]
@X-ma how did you solve this issue

**Comment by DownStone** [comment]
@X-ma How do you get `test_example.txt` and `labels.mat` in `test_miccai_2018.py` or `test.py`? Please give an example. Thanks.

**Comment by adalca** [comment]
@DownStone `labels.mat` is included in the `data` folder, and `test_examples.txt` should simply include lines like:
`/fulll/path/to/test_example_1.nii, /full/path/to/test_example_1_seg.nii`
