### ISSUE TITLE
no function called vxm.utils.affine_to_shift

### ISSUE THREAD

**Issue by MaybeRichard** [voxelmorph/voxelmorph#484]
Hello, I'm trying to learn VoxelMorph by following the VoxelMorphAffineAnnotationWarp in Colab, but when I run `field_inv = vxm.utils.affine_to_shift(aff_inv, im.shape, shift_center=True)[np.newaxis, ...]`, something is wrong. I searched some old issue and found out that affine_to_shift function have changed to affine_to_dense_shift. But after changing the function, new error comes out:ValueError: Affine matrix must be of shape (2, 3) or (3, 4), got (3, 3).

**Comment by adalca** [comment]
pinging @ahoopes  and @mu40 who have quite a bit of experience on this. it's possible, though, that `affine_to_shift` was removed.

**Comment by mu40** [comment]
Yes, the function is `vxm.utils.affine_to_dense_shift` now. This function currently only supports transformation matrices with the last row removed, which should be `(0, 0, 1)` in your case. Instead of `aff_inv`, you may want to try passing `aff_inv[:-1, :]`. We should look into updating the Colab!

**Comment by MaybeRichard** [comment]
> aff_inv[:-1, :]

Thanks a lot. It works!
