### ISSUE TITLE
Potential minor bug in `assert` of torch version of  `train.py` 

### ISSUE THREAD

**Issue by dyhan316** [voxelmorph/voxelmorph#488]
I believe there is a minor bug, in the torch version of  `train.py`, 

```python
# device handling
gpus = args.gpu.split(',')
nb_gpus = len(gpus)
device = 'cuda'
os.environ['CUDA_VISIBLE_DEVICES'] = args.gpu
assert np.mod(args.batch_size, nb_gpus) == 0, \
    'Batch size (%d) should be a multiple of the nr of gpus (%d)' % (args.batch_size, nb_devices)
```
In the above `assert` statement, `nb_devices` was used, which was not defined before, I believe that it should be changed to `nb_gpus`?? Thank you!

**Comment by adalca** [comment]
Good point, do you mind pushing a PR? :)

**Comment by dyhan316** [comment]
OK! I'd be delighted to! :)

**Comment by adalca** [comment]
Thanks!
