### ISSUE TITLE
 Register the lung volume

### ISSUE THREAD

**Issue by white-hy** [voxelmorph/voxelmorph#49]
Dear author. I am reading your paper published in CVPR and MICCAI. My task is to register  the lung volume,and I want to use voxelmorph to do it.I have the a lot of data now.I want to train my model.What should I do next?Can you tell me the next step?
Looking forward to your answer. Thank you.

**Comment by adalca** [comment]
I would recommend starting by making sure the data is the same size (pad if necessary) and a multiple of 16, normalizing to `[0-1]` and then trying to feed it to the voxelmorph training (e.g. `train.py) to see what happens. If you don't have an atlas, I would choose a reasonable looking subject. Obviously this is just to get started, but should give interesting results.

**Comment by qiheihelan** [comment]
Dear author. I am also reading your paper ' An Unsupervised Learning Model for Deformable Medical Image Registration'. My task is to register the lung 4D CT by unsupervised model. I want to use voxelmorph to do it. I have the a lot of data now and size is 256*256*94. I want to train my model. What should I do next? Here are the steps I guessed, I hope you give more detailed steps.
1.making sure the data is the same size (pad if necessary) and a multiple of 16, 
（e.g 256*256*94——>256*256*256）normalizing to [0-1].
2.The format of the CT is dicm, which needs to be given as npz. Or change the npz in the code to DICM.
3.run train.py.
What else do you need before the third? What is the order in which the programs in these files （data,ext,models,src and unified_seg） are run?
Looking forward to your answer. Thank you.

**Comment by qiheihelan** [comment]
@adalca @white-hy Dear author. I am also reading your paper ' An Unsupervised Learning Model for Deformable Medical Image Registration'. My task is to register the lung 4D CT by unsupervised model. I want to use voxelmorph to do it. I have the a lot of data now and size is 25625694. I want to train my model. What should I do next? Here are the steps I guessed, I hope you give more detailed steps.
1.making sure the data is the same size (pad if necessary) and a multiple of 16,
（e.g 25625694——>256256256）normalizing to [0-1].
2.The format of the CT is dicm, which needs to be given as npz. Or change the npz in the code to DICM.
3.run train.py.
What else do you need before the third? What is the order in which the programs in these files （data,ext,models,src and unified_seg） are run?
Looking forward to your answer. Thank you.

**Comment by qiheihelan** [comment]
@adalca  Dear author. I am also reading your paper ' An Unsupervised Learning Model for Deformable Medical Image Registration'. My task is to register the lung 4D CT by unsupervised model. I want to use voxelmorph to do it. I have the a lot of data now and size is 25625694. I want to train my model. What should I do next? Here are the steps I guessed, I hope you give more detailed steps.
1.making sure the data is the same size (pad if necessary) and a multiple of 16,
（e.g 25625694——>256256256）normalizing to [0-1].
2.The format of the CT is dicm, which needs to be given as npz. Or change the npz in the code to DICM.
3.run train.py.
What else do you need before the third? What is the order in which the programs in these files （data,ext,models,src and unified_seg） are run?
Looking forward to your answer. Thank you.

**Comment by qiheihelan** [comment]
@white-hy hello,I saw that you also studied the registration of the lungs. I just started to learn this model. The specific steps are not very well understood. Could you help me? Or you can add a qq2834728654

**Comment by white-hy** [comment]
@qiheihelan Hi！
I am not sure if you are just starting to study image registration and deep learning soon. If I were you, I would try to run train.py and test.py using the data provided by the author. And I'm going to try to combine the paper and the code to figure out how voxelmorph works.
Then start preprocessing your own data. In addition to what the author said (making sure the data is the same size and a multiple of 16, normalizing to [0-1]), you also need to ensure that your data is isotropic. When your data is preprocessed, you can train your own model.

**Comment by qiheihelan** [comment]
@white-hy Thank you very much for your reply, I just started learning deep learning. I don't know how to train my model.  first step is image preprocessing, then import tain.py. I know the author's work, but I don't know which program is the beginning, what function does that program correspond to? Do all the programs given by the author run? What is the order of the program running? 
Looking forward to your answer. Thank you.

**Comment by adalca** [comment]
@qiheihelan 

After you do your image processing as you described, to train a new model you can use `train.py`. 
Simply call it with the folder in which your data is in.
Then use `register.py` to register images.

**Comment by qiheihelan** [comment]
Thank you very much for your reply. If there is any problem in the future implementation, you may also contact you, thank you again.


------------------ 原始邮件 ------------------
发件人: "Adrian Dalca"<notifications@github.com>;
发送时间: 2019年7月12日(星期五) 晚上8:40
收件人: "voxelmorph/voxelmorph"<voxelmorph@noreply.github.com>;
抄送: "2834728654"<2834728654@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [voxelmorph/voxelmorph]  Register the lung volume (#49)




@qiheihelan
 
After you do your image processing as you described, to train a new model you can use train.py.
 Simply call it with the folder in which your data is in.
 Then use register.py to register images.

**Comment by white-hy** [comment]
@qiheihelan Hi！
In the author's work.There are three `.py` files that can be run separately: `register.py` ` train.py` and `test.py`. 
`register.py` is responsible for registering two images; `train.py `is responsible for the training model; `test.py` is responsible for testing the model(the overlap of different anatomical structures in two images can be calculated, and the Dice score is the measurement index). Check out the author's `README.md` for details.
Firstly, you can try to run `register.py` to register  two images(atlas_norm.nii.gz/test_vol.nii.gz) provided by the author and you will get an interesting result, which is helpful to understand the image registration.
It is worth mentioning that the author's papers has helped me a lot and I hope you can also benefit from reading it again and again.

**Comment by qiheihelan** [comment]
Thank you very much for your help. I will study the author's paper carefully and  try to run register.py to register two images(atlas_norm.nii.gz/test_vol.nii.gz) provided by the author .Further process my own data and train own models.Thank you again for your detailed reply.

**Comment by qiheihelan** [comment]
@white-hy Thank you very much for your help. I will study the author's paper carefully and try to run register.py to register two images(atlas_norm.nii.gz/test_vol.nii.gz) provided by the author .Further process my own data and train own models.Thank you again for your detailed reply.

**Comment by qiheihelan** [comment]
@adalca @white-hy Hello, My system is LINUX 64. I executed pip install medipy and the results showed no matching versions. I executed pip install neuron and the result shows: command "python setup.py egg_info" failed with error code 1 in /tmp/pip-__610omc/neuron/
I found some methods but I could not solve them, so I am bothering you again. Do you have any similar questions when installing third-party tools, can you give some suggestions?

**Comment by qiheihelan** [comment]
@adalca @white-hy 
Hello! 
For medipy, neuron, pynd and pytools, I don't need pip install, just set the path？Sorry, I just started using python, and some basic questions don't understand. The computer I want to use is shared by several students. I am afraid that the computer will be affected by my uncertain operation. So I am more cautious, and every step is determined before I dare to operate. 
I hope that I will not bother you, I look forward to your guidance.Thanks.

**Comment by white-hy** [comment]
@qiheihelan Hi!
The libraries you said are completely provided by the author and don‘t’ need to be installed using `pip`. When you need a module, you must add its path to the system's environment variable and then import it in the location that you need.

**Comment by qiheihelan** [comment]
@white-hy Thank you very much for your reply. I have some other things recently, so I didn’t express my gratitude in time. I will learn to preprocess the image in the next step. I hope we can all learn smoothly.
