### ISSUE TITLE
Voxelmorph plotting l2 and NCC losses

### ISSUE THREAD

**Issue by zozo19999** [voxelmorph/voxelmorph#499]
Hi,
I'm currently working on my project using voxelmorph and I'm running a neural network (Unet) and I want to plot regression loss(l2) and NCC loss separately for each epoch.
Voxel morph offers the following losses:
loss, flow loss, transformer loss.
How can I import or calculate the losses I want from the losses that voxelmorph presents?

**Comment by adalca** [comment]
I believe in what you list, `loss` is the weighted loss of the flow (image mathing) loss and (spatial) transformer loss. This is weighted by the weights you chose for the loss terms. Sorry for the bad naming (we found it hard to control this in the original tf/torch interfaces).
