### ISSUE TITLE
about the jacobian determinant

### ISSUE THREAD

**Issue by Barnonewdm** [voxelmorph/voxelmorph#50]
The miccai model is based on the integration of static velocity. The obtained deformation field is expected to be diffeomorphic. However, the paper result or good jacobian determinant pefromance can not be reproduced by the supplied code. I just want to know is the code supplied consistent with paper? Could suggest the potential bugs for the failure reproduction? I mean we can obtain higer dice ratio but with many negtive jacobian determinant points.

**Comment by adalca** [comment]
Hi @Barnonewdm,

Yes, we used the code for the MICCAI paper on our data, which gave us the very well behaved results we presented. Obviously there might be a dependancy on the data and  Can you tell us which part does not work for you? 

The obvious things to pay attention to are what data are you using, and how is it normalized (the noise parameter will affect this, which will indirectly control the regularity of the field)? What were the loss parameters you used, and how many velocity integration steps?

The velocity field integration will lead to diffeomorphism up to numerical issues. You can see a numerical analysis of our integration code in this paper (end of experiments): https://arxiv.org/abs/1903.03545 . It's not always perfect, but usually quite good with enough integration steps and the right parameters.

**Comment by Barnonewdm** [comment]
Thanks @adalca
Figure 12 in the [paper](https://arxiv.org/abs/1903.03545) shows the warped grid. Why the grid seems so fuzzy? The warped grid should have a clear structure, as it is graph data (consists of nodes and edges).
![WeChatcc503e6092a935f364094398ac67c6c0](https://user-images.githubusercontent.com/22175925/57936981-06231980-7893-11e9-9c52-24333c0f0121.png)

**Comment by adalca** [comment]
Hi @Barnonewdm -- This effect happens because the BW grid is done 3D. 

Before the warp, perpendicular to the shown plane there will occasionally be an all-white "slice" (a coronal slice that is all white). Once warped, this slice sometimes comes close to the visualized view, creating that effect.

We could take out these planes, and make the grid only in the visualized plane, and this effect would go away.
