### ISSUE TITLE
invalid stored block lengths

### ISSUE THREAD

**Issue by bhatrana** [voxelmorph/voxelmorph#500]
CT and MRI registration, 

Hi I am using Voxelmorph to register CT and MRI with some code changes. My setup was okay before and the experiments were running fine before. But recently these days I am having this issue; What could be the problem ? Thank you 

![image](https://user-images.githubusercontent.com/79718549/214390943-502ae191-29d7-4720-8daf-14111764bdf5.png)

**Comment by adalca** [comment]
Looking at the trace, it seems like an issue with nibabel reading some of your data files.

**Comment by bhatrana** [comment]
Thank you. The problem was solved. I had some error during preprocessing of data.
