### ISSUE TITLE
Compute gpu timing in 3d voxelmorph 

### ISSUE THREAD

**Issue by Paluck1Arora2** [voxelmorph/voxelmorph#501]
Hi, Can anyone tell me how to compute gpu time and check the result on different values of lambda in 3d voxelmorph
https://www.kaggle.com/code/kmader/voxelmorph-demo/notebook

**Comment by adalca** [comment]
that kaggle notebook is not ours so we can't address those questions. To compute gpu time you can use the `time` python library, ot `%timeit` jupyter magic, or `time` unix program, etc.
