### ISSUE TITLE
List index out of range in test.py

### ISSUE THREAD

**Issue by Paluck1Arora2** [voxelmorph/voxelmorph#502]
Hi, 
Can anyone please guide there is an error in test.py "https://github.com/ahoopes/voxelmorph"
This is the link of the code "https://colab.research.google.com/drive/1-p9yzo0bvg_vgdz7MvQYB0T8M0L8AXSM#scrollTo=hcS3f5x19uLt"

**Comment by adalca** [comment]
https://github.com/ahoopes/voxelmorph is @ahoopes 's fork of voxelmorph, which I assume is quite old and unsupported?

**Comment by Paluck1Arora2** [comment]
I thought this is the updated version of this code "https://github.com/balakg/voxelmorph".

**Comment by Paluck1Arora2** [comment]
I thought this is the updated version of this code "https://github.com/balakg/voxelmorph".

**Comment by ahoopes** [comment]
Yes, that fork is super old. Just use the main [voxelmorph/voxelmorph](github.com/voxelmorph/voxelmorph) github repo

**Comment by Paluck1Arora2** [comment]
Hi sir,
can you please generate these weights cvpr2018_vm2_l2.h5 in
voxelmorph/voxelmorph link

**Comment by Paluck1Arora2** [comment]
Hi ,
Can you please tell how to generate the weight cvpr2018_vm2_l2.h5 in
voxelmorph/voxelmorph

**Comment by adalca** [comment]
please see answer in #505
