### ISSUE TITLE
How to generate pre trained weight in voxelmorph tutorial like "brain_3d.h5"

### ISSUE THREAD

**Issue by Paluck1Arora2** [voxelmorph/voxelmorph#505]

**Comment by adalca** [comment]
I wrote [this tutorial](https://colab.research.google.com/drive/1ZefmWXBupRNsnIbBbGquhVDsk-7R7L1S?usp=sharing) to show to to quickly train in 2d. You can train in 3D similarly, just download our 3d data from https://github.com/adalca/medical-datasets/blob/master/neurite-oasis.md

**Comment by Paluck1Arora2** [comment]
Yes sir, Can you please describe how to generate pre trained model weight in .h5 format

**Comment by adalca** [comment]
The save_callback in train.py does this automatically. if you turned this off, you can use  `model.save` as shown here https://www.tensorflow.org/api_docs/python/tf/keras/models/save_model

This is really a keras question
