### ISSUE TITLE
How to generate the model UNet in vxm.networks. Please provide the relevant answer.

### ISSUE THREAD

**Issue by Paluck1Arora2** [voxelmorph/voxelmorph#506]
Hi,
Can anyone please provide the solution. 
This is the voxelmorph tutorial "https://colab.research.google.com/drive/1WiqyF7dCdnNBIANEY80Pxw_mVz4fyV-S?usp=sharing#scrollTo=lZw3dTg4PXNW" where we bulid the model , but in the networks.py file , there is no any function of unet. Can you please describe it.
build model 
unet = vxm.networks.Unet(inshape=inshape, nb_features=nb_features)

**Comment by adalca** [comment]
I've answered in your other post, I think #505 
please see keras model saving.
https://www.tensorflow.org/guide/keras/save_and_serialize
