### ISSUE TITLE
What is VxmDense . If we create unet model then where we define the unet model?? 

### ISSUE THREAD

**Issue by Paluck1Arora2** [voxelmorph/voxelmorph#507]
Please provide the relevant answer.
# unet
vxm_model = vxm.networks.VxmDense(vol_shape, nb_features, int_steps=0)

**Comment by adalca** [comment]
the VxmDense model calls the Unet model. See https://github.com/voxelmorph/voxelmorph/blob/531f8d91ef0a71154cf089a38b3d853e591b6604/voxelmorph/tf/networks.py#L136

unfortunately, we really can't answer each question like this, we simply don't have the bandwith. Please read the vxm documentation and code and the keras documentation for these questions, most can be answered by following that.
