### ISSUE TITLE
module 'voxelmorph.tf.networks' has no attribute 'unet_core'

### ISSUE THREAD

**Issue by Paluck1Arora2** [voxelmorph/voxelmorph#508]
vxm_model = vxm.networks.unet_core(vol_shape, nb_features, int_steps=0)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-32-9298f376d4c6>](https://localhost:8080/#) in <module>
      1 # first, let's get a unet (before the final layer)
----> 2 unet = vxm.networks.unet_core(vol_shape, nb_enc_features, nb_dec_features);
      3 unet.summary()

AttributeError: module 'voxelmorph.tf.networks' has no attribute 'unet_core'

This is my file ... I executed this kaggle notebook "https://www.kaggle.com/code/adalca/learn2reg/notebook"
https://colab.research.google.com/drive/1NDzMm18Im7w0WKiz43wXcCDUn36GfK9_?usp=sharing

**Comment by adalca** [comment]
As the top of that kaggle tutorial says, please use tutorial.voxelmorph.net.

the voxelmorph codebase has changed a couple of years ago. We have the Unet class in https://github.com/voxelmorph/voxelmorph/blob/531f8d91ef0a71154cf089a38b3d853e591b6604/voxelmorph/tf/networks.py#L1037
