### ISSUE TITLE
How to compute average dice in voxelmorph tutorial.

### ISSUE THREAD

**Issue by Paluck1Arora2** [voxelmorph/voxelmorph#509]

**Comment by adalca** [comment]
please see our test scripts: https://github.com/voxelmorph/voxelmorph/blob/531f8d91ef0a71154cf089a38b3d853e591b6604/scripts/tf/test.py#L109

You essentially grab the deformation field from doing the registration, warp the 'moving' segmentations, and then compute dice.

**Comment by Paluck1Arora2** [comment]
Can you please tell me how to compute average dice in the
voxelmorph tutorial with the help of this link  "
https://github.com/voxelmorph/voxelmorph/blob/531f8d91ef0a71154cf089a38b3d853e591b6604/scripts/tf/test.py#L109
"
