### ISSUE TITLE
# MORE CONFUSING # How it is exceuted in unet_core in kaggle. When i run the same in my colab notebook then it will shows error. 

### ISSUE THREAD

**Issue by Paluck1Arora2** [voxelmorph/voxelmorph#510]
unet = vxm.networks.unet_core(vol_shape, nb_enc_features, nb_dec_features);

This is executed in this kaggle notebook "https://www.kaggle.com/code/adalca/learn2reg/notebook" . It will take the data from kaggle like voxelmorph.

**Comment by adalca** [comment]
Please see the other thread you started on this: #508
