### ISSUE TITLE
nibabel.deprecator.ExpiredDeprecationError: get_data() is deprecated in favor of get_fdata()

### ISSUE THREAD

**Issue by mk12306** [voxelmorph/voxelmorph#516]
When I am using the voxelmorph module, the following error occurs：

nibabel.deprecator.ExpiredDeprecationError: get_data() is deprecated in favor of get_fdata(), which has a more predictable return type. To obtain get_data() behavior going forward, use numpy.asanyarray(img.dataobj).

![image](https://user-images.githubusercontent.com/50614823/224650397-10a53bfd-f61b-4d36-af7d-ebdb82cec193.png)

**Comment by Rex-sys-hk** [comment]
In my case, downgrade nibabel to version 5.0 can solve this problem.

**Comment by adalca** [comment]
@mu40 had pushed a PR that I had missed that fixes this. It should be fixed now in the code -- https://github.com/voxelmorph/voxelmorph/pull/520
