### ISSUE TITLE
flow_loss increase

### ISSUE THREAD

**Issue by zoujinger** [voxelmorph/voxelmorph#52]
Dear author,
I am training the cvpr2018_net with lung volume.
During training, loss and spatial_transformer_1_loss decreased,  but flow_loss increased.
and I think all the values are large.
Is there anything wrong?
![image](https://user-images.githubusercontent.com/27009979/58011837-b740e280-7b25-11e9-8aef-74246183987e.png)

Here is my train command:
python3 "/content/drive/My Drive/Colab Notebooks/voxelmorph/src/train.py" "/content/drive/My Drive/Colab Notebooks/voxelmorph/data/rigid_train0" \
--atlas_file "/content/drive/My Drive/Colab Notebooks/voxelmorph/data/rigid_case1_00.nii" --model_dir "/content/drive/My Drive/Colab Notebooks/voxelmorph/model0" \
--epochs 60 --steps_per_epoch 50 \
#--load_model_file ""

and the data was rigidly registered and normalized to [0 , 1], all resized to 256x256x96

**Comment by adalca** [comment]
hi @zoujinger 

There's no issues with one of the losses increasing, as long as the total loss goes down (which it seems to). However, two things are of note:
1. the vol size `256x256x96` makes me think that your data is not isotropic. I would recommend checking this, and making sure it is isotropic, and if not, upsampling it to isotropic before registering
2. Are you certain the data was normalized to `[0,1`]? That first loss, which is the data loss I believe, seems incredibly high for the usual losses we use. Or did you change the data loss?

**Comment by adalca** [comment]
This was done as part of the `FreeSurfer` runs, but you can do it with anything, really. 

To check, simply load the data (e.g. with nibabel in python), and look at the pixel sizes (please see nibabel documentation for this). You can then change the data to isotropic by interpolation. Here's a matlab script to do it: https://github.com/adalca/matlib/blob/master/matlib/medimg/toIsotropic.m
but you can code this up in python as well.

**Comment by Alison-brie** [comment]
Hi, adalca.
This is the header information of my nii data 
![image](https://user-images.githubusercontent.com/29921392/58600953-3a4a0180-82b9-11e9-8e10-be1e391642c3.png)
And this is an example data
[example.nii.gz](https://github.com/voxelmorph/voxelmorph/files/3235014/example.nii.gz)

**Comment by zoujinger** [comment]
> hi @zoujinger
> 
> There's no issues with one of the losses increasing, as long as the total loss goes down (which it seems to). However, two things are of note:
> 
> 1. the vol size `256x256x96` makes me think that your data is not isotropic. I would recommend checking this, and making sure it is isotropic, and if not, upsampling it to isotropic before registering
> 2. Are you certain the data was normalized to `[0,1`]? That first loss, which is the data loss I believe, seems incredibly high for the usual losses we use. Or did you change the data loss?

Thanks a lot!
I am wondering why the image need to be isotropic?
Does it  improve the accuracy or speed the process?

**Comment by zoujinger** [comment]
@adalca

**Comment by adalca** [comment]
You can do it with anisotropic images, but correspondences in such a space make less sense.

**Comment by elfprincess3** [comment]
Hello @adalca,
What are the definitions of 'isotropic images' and 'anisotropic images' here? 
And why interpolation can change  'anisotropic images' into 'isotropic images' ?
Thanks!

**Comment by adalca** [comment]
@elfprincess3 these definitions refer to the size of the voxels. isotropic means that each voxel in the image represents the same dimension (e.g. 1mm^3). so if a 256^3 image is taken and captures ~(256 mm)^3 area, you would get isotropic voxels.

anisotropic means that the dimensions are not the same. Often, we see a voxel that is 1x1x2mm or something like that due to acquisition procedures. So the same field would give a 256x256x128 image. Interpolating this to 256x256x256 makes the voxels isotropic (1mm^3), although interpolated.

**Comment by elfprincess3** [comment]
@adalca Thanks! I am not familiar with 3D images registration.
