### ISSUE TITLE
Warping labelmap in Hypermorph

### ISSUE THREAD

**Issue by annareithmeir** [voxelmorph/voxelmorph#526]
**Task** (what are you trying to do/register?)

I am trying to compute the Dice score for evaluation with Hypermorph. To this end, in the test step, I want to warp a one-hot label map with the predicted warp.

I have a hard time understanding how to access the spatial transformer of the network and using that to warp the one-hot label maps. Could you give me an example?

**Comment by adalca** [comment]
Sure. Under the tutorial.voxelmorph.net colab, in the '3D MRI Brain' --> 'validation data' section, there are a few cells where we warp segmentation maps:

<img width="647" alt="image" src="https://github.com/voxelmorph/voxelmorph/assets/3219675/dcdf659f-f0e6-4602-aa87-c9fd1d2c9402">

**Comment by annareithmeir** [comment]
Ah of course, thanks a lot!
