### ISSUE TITLE
fetch_build_eggs is deprecated, fatal installation error

### ISSUE THREAD

**Issue by rueberger** [voxelmorph/voxelmorph#530]
not an issue on master, but dev still uses `fetch_build_eggs` to determine version number. this causes a fatal error when `pip installing` with

pip        23.1.2
setuptools 49.2.1

easily resolved by hardcoding `version` and `packages`

**Comment by adalca** [comment]
Thank you @rueberger for pointing this out.

**Comment by rueberger** [comment]
addendum: don't hardcode `version` i was mistaken, `find_packages` is not deprecated

**Comment by ahoopes** [comment]
fixed by 314eada - no need to use the packaging tools anyway
