### ISSUE TITLE
Trying to recreate the voxelmorph tutorial in Pytorch 

### ISSUE THREAD

**Issue by CaffineAddic** [voxelmorph/voxelmorph#534]
**Task** (what are you trying to do/register?)

We were trying to create the tutorial of voxelmoph in pytorch

Plagued by the the error 
return torch.max_pool3d(input, kernel_size, stride, padding, dilation, ceil_mode)

RuntimeError: Given input size: (32x80x80x1). Calculated output size: (32x40x40x0). Output size is too small.

**What have you tried**

We have tried to use the Oasis tutorial data in 2d format and 3d format as well

**Comment by CaffineAddic** [comment]
https://github.com/CaffineAddic/HybridMorph_pytorch-redesign/blob/main/VoxelMorph_Tutorial_torch.ipynb

**Comment by CaffineAddic** [comment]
Here is the code if anyone can take a look

**Comment by adalca** [comment]
You're right, we don't have a zoom function in pytorch. You can likely use `F.interpolate` instead, with just a few lines of code. 

We're working on a pytorch tutorial, but it's been going slow :(

**Comment by CaffineAddic** [comment]
Thanks a lot for your reply
