### ISSUE TITLE
Dataset list required

### ISSUE THREAD

**Issue by GYDDHPY** [voxelmorph/voxelmorph#538]
**Task** (what are you trying to do/register?)
I want to train VoxelMorph using data mentioned in the paper.

**What have you tried**
Currently I'm collecting dataset.

**Details of experiments**
I try to download the public dataset used by VoxelMorph. I notice that the offical public dataset seems contain more samples than which is used in the paper.  Does VoxelMorph use dataset filtered by specific conditions? Could you please provide the datalist used by VoxelMorph?

**Comment by GYDDHPY** [comment]
For example, ABIDE dataset contains ABIDE 1 and ABIDE 2 dataset. Each of them contains more than 1000 samples. ABIDE 1 includes 539 scans from individuals with ASD and 573 scans from typical controls. Does VoxelMorph use both ABIDE 1 and ABIDE 2? Does VoxelMorph use both ASD samples and controls samples?

**Comment by adalca** [comment]
In the original paper we used a lot of datasets we cannot share, and we randomly sampled train/val/test split. I don't recall which ABIDE we used, I think 1.

I recommend using https://github.com/adalca/medical-datasets/blob/master/neurite-oasis.md to work with

**Comment by GYDDHPY** [comment]
Thanks a lot.
