### ISSUE TITLE
blurred warped image

### ISSUE THREAD

**Issue by zzx332** [voxelmorph/voxelmorph#54]
Hi,
I use the MICCAI model for liver registration in my own data,but i got blurred warped image.
The work i am doing is sub-to-sub registration.Before registration,i did normalization and affine alignment.
Although there is convergence, the loss does not converge to very low.
I see other people have the same problem in Issues.
Hope to receive your reply!

**Comment by adalca** [comment]
@zzx332, can you please provide more details about how you did normalization, what parameters you used, and illustrate an example image of what you mean by blurred? Otherwise, it's hard to us to help.
