### ISSUE TITLE
Classic optimization based registration in VoxelMorph

### ISSUE THREAD

**Issue by clane9** [voxelmorph/voxelmorph#546]
Hi, thanks for this awesome project! I really like the learning-based approach taken in VoxelMorph. But I'm also interested in whether one can make *classic* optimization-based registration faster just by leveraging GPUs. Is this something you've thought about? Is it possible within VoxelMorph? Thanks!

**Comment by adalca** [comment]
yup! in our TMI paper we tested initializing a field with vxm, but then essentially optimizing the field for that pair -- essentially with a standard iterative strategy. 

You can make this fancier and fancier.

**Comment by clane9** [comment]
Thanks for the quick reply! I found the section you were referring to in the paper, very cool. I'll see if I can sort out how to use this per image pair fine-tuning.
