### ISSUE TITLE
Question about input image and 2D image training

### ISSUE THREAD

**Issue by HANK538** [voxelmorph/voxelmorph#55]
Hi Adalca 

It's awesome paper. I am new to this field.
I have some low-level questions as below that I could not find any answer on the internet.

1. When training, input image pair is the same person of the same brain MRI pair ?
What I mean and am confused is that 
(fix one person brain, moving the same person brain) >>> next (fix one person brain, moving the same person brain)
or
(fix one person brain, moving the same person brain) >>> next (fix one person brain, moving the same person brain but different image and same scan machine)
or
(fix one person brain, moving the same person brain) >>> next (fix one person brain, moving the same person brain but different image via different scan machine)
or
(fix one person brain, moving the same person brain) >>> next (fix one person brain, moving the another person brain with/without the same scan machine)
 

2. Now I have 2D color image need to do image registration.
How should I do ?
Should I just input single 2D color for training.
Or preprocess 2D color to gray color ? Or compact all color or gray image to volume size for training?

Any idea and suggestion would be appreciated.

**Comment by adalca** [comment]
hi @HANK538,

1. You can do anything you want. We've tried registering an *atlas* (you can think of this as a "centroid" subject if you haven't worked with atlases) to each subject, subject to subject (that is, fixed and moving are *different subjects*), as well as different scans of the same subject. Obviously in the latter case, the deformations are a lot smaller.

2. You can use RGB images just fine. You'll need to modify the networks so that the input and output take 3 channels instead of 1, but this is easy to do (e.g. within `cvpr2018_net` you can modify the `unet_core` code to use `src_feats=3` and `tgt_feats=3`. If you choose to work with grayscale (using some sort of `rgb2gray` conversion) then you can simply use the existing code.

Good luck,
- Adrian

**Comment by HANK538** [comment]
Hi Adalca

Thanks for your update!
But unfortunately, it still not work as following settings.
    src_feats = 3
    tgt_feats = 3

My input color image 2D shape and vol_size is (176, 1152, 3)

Error log:
\src\networks.py", line 75, in unet_core
x = concatenate([x, x_enc[-2]])
ValueError: A `Concatenate` layer requires inputs with matching shapes except for the concat axis. Got inputs shapes: [(None, 22, 144, 2, 32), (None, 22, 144, 1, 32)]

I tried different combination of parameters with no luck.
Any idea?

**Comment by balakg** [comment]
Are you sure the inputs that are fed to the network have 3 dimensions instead of 4?

**Comment by HANK538** [comment]
Hi balakg

Which input shape is correct ?
 [(None, 176, 1152, 3, 1)] or  [(None, 176, 1152, 3)] or  [(None, 176, 1152, 1, 3)] ?
For color 2D image, ndims should be 2 or 3 ?

Thanks
Hank

**Comment by balakg** [comment]
For 2d images of size height x width x chan, the input should be (None, height, width, chan), where the first dimension is your batch size.

**Comment by HANK538** [comment]
Hi balakg

If I used ndims = 2, src and tgt = (None, 176, 1152, 3)

I will encounter
losses.py", line 64, in ncc
    J_sum = conv_fn(J, sum_filt, strides, padding)
ValueError: Dimensions must be equal, but are 3 and 1 for 'loss/spatial_transformer_1_loss/Conv2D_1' (op: 'Conv2D') with input shapes: [?,176,1152,3], [9,9,1,1].

Any idea?

Thanks
Hank

**Comment by HANK538** [comment]
Hi balakg

I took some effort that set loss function to mse and modify input data generator as the same shape.
Finally, it works now.
However, Thanks for your help!

Thanks
Hank

**Comment by HANK538** [comment]
Hi balakg

I try and back to 2D color image training for cc loss.

J_sum = conv_fn(J, sum_filt, strides, padding)
ValueError: Dimensions must be equal, but are 3 and 1 for 'loss/spatial_transformer_1_loss/Conv2D_1' (op: 'Conv2D') with input shapes: [?,176,1152,3], [9,9,1,1].

J shape is [None, 176,1152,3]
How should I set sum_filt value so that make training work ?
Any suggestion ?

Thanks

**Comment by balakg** [comment]
The problem is that the filter is set for one channel images. You have a few options for modifying the CC loss function for your needs: 

1. Before running the filter, collapse your images to one channel (grayscale it)

2. Run the filter on each channel of your image separately, and then take an average over the channels

3. modify the filter itself into a [9, 9, 3, 3] shape, but make sure you construct it correctly so that the channels are processed separately.

**Comment by davidz123** [comment]
@HANK538  hi, I'm going to do registration on RGB image and see your issue, could you release your implement on RGB images or share the configuration you set for this project.

**Comment by adalca** [comment]
@davidz123 here's our implementation -- just replace `NCC().ncc` with:

```
    def ncc(self, I, J):
        # get dimension of volume
        # assumes I, J are sized [batch_size, *vol_shape, nb_feats]
        ndims = len(I.get_shape().as_list()) - 2
        assert ndims in [1, 2, 3], "volumes should be 1 to 3 dimensions. found: %d" % ndims

        # set window size
        if self.win is None:
            self.win = [9] * ndims

        # get convolution function
        conv_fn = getattr(tf.nn, 'conv%dd' % ndims)

        # compute CC squares
        I2 = I*I
        J2 = J*J
        IJ = I*J

        # compute filters
        in_ch = J.get_shape().as_list()[-1]
        sum_filt = tf.ones([*self.win, in_ch, 1])
        if ndims > 1:
            strides = [1] * (ndims + 2)
        else:
            strides = 1
        padding = 'SAME'

        # compute local sums via convolution
        I_sum = conv_fn(I, sum_filt, strides, padding)
        J_sum = conv_fn(J, sum_filt, strides, padding)
        I2_sum = conv_fn(I2, sum_filt, strides, padding)
        J2_sum = conv_fn(J2, sum_filt, strides, padding)
        IJ_sum = conv_fn(IJ, sum_filt, strides, padding)

        # compute cross correlation
        win_size = np.prod(self.win) * in_ch
        u_I = I_sum/win_size
        u_J = J_sum/win_size

        cross = IJ_sum - u_J*I_sum - u_I*J_sum + u_I*u_J*win_size
        I_var = I2_sum - 2 * u_I * I_sum + u_I*u_I*win_size
        J_var = J2_sum - 2 * u_J * J_sum + u_J*u_J*win_size

        cc = cross*cross / (I_var*J_var + self.eps)

        # return negative cc.
        return tf.reduce_mean(cc)

    def loss(self, I, J):
        return - self.ncc(I, J)
```
