### ISSUE TITLE
Optimization in pytorch with a fixed number of iterations in inner loop rather than using steps=len(dataset)/batch_size

### ISSUE THREAD

**Issue by Voldemort108X** [voxelmorph/voxelmorph#551]
Hi,

Thanks for your code. I am wondering why the optimization process in pytorch implementation has a fixed number of iterations like:
```
for epoch in range(num_epoch):
     for step in range(steps_per_epoch):
          input_data = next(generator)
          ...
```
instead of 
```
for epoch in range(num_epoch):
     for (input, label) in data_loader:
          ...
```
which iterates through the entire dataset with steps = len(dataset)/batch_size. 

Best,

**Comment by adalca** [comment]
I think it's just a legacy aspect -- an effect of how we did things in tf (first vxm implementation) back in the day, and how tf/torch frameworks were back then. Feel free to loop as desired! :D

**Comment by Voldemort108X** [comment]
Thanks very much for the quick reply. I was just thinking about the efficiency and the way of doing mini-batch sampling using generator.py does not necessarily guarantee the entire dataset will be visited, which might cause the oscillation in the training curve when facing challenging datasets.
```
# how generators.py load input at each step in inner loop
indices = np.random.randint(len(vol_names), size=batch_size)
```
From the above implementation, the generator loads a random mini-batch from the dataset with steps_per_epoch (default 100) times inside 1 epoch. I haven't investigated the performance difference but just want to point this out.

**Comment by adalca** [comment]
In my experience, it shouldn't matter much that you hit every element at every epoch -- maybe others have studied this more carefully, but in most of our models we apply some random augmentations at the start anyway, which further adds 'randomness' to the whole thing. I honestly doubt making sure you go through the whole set once per epoch will make a big difference. I am happy to be proven wrong!

**Comment by Voldemort108X** [comment]
Thanks. Yeah I kind of agree with the intuition that it should not make too much of a difference since mini-batch is also just an approximation anyway. Studying this super carefully is also difficult as it might vary with different datasets/setups.
