### ISSUE TITLE
number of dims don't match in permute

### ISSUE THREAD

**Issue by PonyPinkPie** [voxelmorph/voxelmorph#556]
**training** (what are you trying to do/register?)

**What have you tried**

My dataset is `neurite-oasis.2d.v1.0 (24.9MB)`. `tensorflow version code` is ok, but `torch version code` has an error which is `number of dims don't match in permute` in line 203. `d.shape` is (1, 160, 192, 1) with 4 dimensions, but `permute(0, 4, 1, 2, 3)` operate 5  dimensions.

**Comment by adalca** [comment]
I answered your query in #555, did that address your concern?
