### ISSUE TITLE
How to get the file "test_example.txt" corresponding to "labels.mat"?

### ISSUE THREAD

**Issue by DownStone** [voxelmorph/voxelmorph#56]
I try the file ,`test_example.txt` 
>C:\Users\AFEI\Desktop\linux_server\voxelmorph\data\data_test\test_vol.npz,C:\Users\AFEI\Desktop\linux_server\voxelmorph\data\data_test\test_seg.npz

and `labels.mat` in you github.But the result is `(0 0.000 0.000)`.
I want to know how to get the file `test_example.txt` corresponding to `labels.mat`.

**Comment by balakg** [comment]
test_example.txt just contains one volume file and segmentation file per line, separated by a comma. 
In your case, you could just have one line with the location of the test_vol.npz and test_seg.npz files.

**Comment by DownStone** [comment]
@balakg Thanks a lot.I only have `test_vol.npz`  and  `test_seg.npz` .How to get more `.npz`  files?

**Comment by balakg** [comment]
The datasets cited in our paper can be downloaded for free. We can't distribute them ourselves, however.

**Comment by DownStone** [comment]
@balakg  Thanks. : )
