### ISSUE TITLE
Registration on large FOV difference cases:

### ISSUE THREAD

**Issue by aa1234241** [voxelmorph/voxelmorph#586]
**Task** (what are you trying to do/register?)
CT-MRI intra person registration with large FOV difference.
[please describe task here]
<img width="1713" alt="Screen Shot 2024-02-01 at 10 12 27 AM" src="https://github.com/voxelmorph/voxelmorph/assets/24704252/4431408d-a930-4220-983f-09a97ca77d7b">

I want to register CT and MRI image for a single person. The CT scan has a large FOV while the MRI image has a small FOV.
Like showed in the image, the green color represents the MRI image which is overlayed on the CT image (they are manually affine registered). Is it possible to get result like this by vxm on the original image?
**What have you tried**
Directly run the SynthMorph for affine registration but the result not good.
Please describe specifics of your approach // use of `vxm`

**Details of experiments**

Please carefully specify details about your experiments. If you are training, when what is the setup? What loss are you using? What does the convergence look like? If you are registering, please show example inputs and outputs. etc.

**Comment by adalca** [comment]
pinging @mu40

**Comment by mu40** [comment]
This is certainly a challenging case for the affine SynthMorph model, which (1) hasn’t seen the FOV extend so much below the neck at training and (2) has been trained primarily on full brains. Your best bet would be retraining with CT-derived label maps that extend as far down as the CT scan you provided.

Barring that, you can try downloading and passing the experimental affine weights from [w3id.org/synthmorph](https://w3id.org/synthmorph) to the latest SynthMorph using the `-w` flag. While this model has been trained on randomly cropped brains, I suspect your example is still at (or beyond) the limit of what that model can do.

Things that may help the experimental model include cropping the CT scan around the head to a region of similar size as the MRI (updating the voxel-to-world matrix appropriately) and clipping the CT intensities to something like [0, 80] in Hounsfield units.

**Comment by aa1234241** [comment]
I see. Thank you very much!
