### ISSUE TITLE
Can Dice Score be used to evaluate CT image registration results?

### ISSUE THREAD

**Issue by white-hy** [voxelmorph/voxelmorph#59]
Dear author. Thanks for your wonderful work and code! It help me a lot.
I noticed that Dice Sorce was used as the evaluation index of your MRI image registration results. My image is a CT image of the lung. Can Dice Score be used to evaluate CT image registration results?

**Comment by balakg** [comment]
You can use dice score when you have segmentation labels for your application. If not, you'll need another means of evaluating the registration field, e.g. some other annotations like sparse anatomical landmarks.

**Comment by white-hy** [comment]
@balakg Thank you for your answer.
I have the mask for the whole lung. Would you tell me the advantages and disadvantages of Dice Score in CT and MRI as evaluation indexes respectively?

**Comment by white-hy** [comment]
@balakg Thank you for your answer.
I have the mask for the whole lung. Would you like to tell me the advantages and disadvantages of Dice Score in CT and MRI as evaluation indexes respectively?

**Comment by white-hy** [comment]
@balakg Thank you for your answer.
I have the mask for the whole lung.Can you tell me the advantages and disadvantages of Dice Score and landmarks as evaluation indexes respectively in CT ?

**Comment by white-hy** [comment]
@balakg Thank you for your answer.
I have the mask for the whole lung.Would you like to tell me the advantages and disadvantages of Dice Score and landmarks as evaluation indexes respectively in CT ?

**Comment by balakg** [comment]
I'm not quite sure about what is the best evaluation metric for CT. Perhaps @adalca would know more about that.

**Comment by white-hy** [comment]
I am very sorry for my late reply..Thank you very much for your answer, @balakg

**Comment by adalca** [comment]
Dice and Landmarks measure different things, and both are useful. 

Dice measures volume overlap, so it would tell you overall how well the lungs are aligned, if you have those segmentations. However, since lungs tend to occupy a lot of voxels, this won't be a great measure of how well the surfaces of the lungs align. Landmarks, depending on where you have them, and how many, will tell you how well you align near those landmarks. 

So both are useful, and if you have both segmentations and landmarks, I would use both to measure results.

**Comment by white-hy** [comment]
> Dice and Landmarks measure different things, and both are useful.
> 
> Dice measures volume overlap, so it would tell you overall how well the lungs are aligned, if you have those segmentations. However, since lungs tend to occupy a lot of voxels, this won't be a great measure of how well the surfaces of the lungs align. Landmarks, depending on where you have them, and how many, will tell you how well you align near those landmarks.
> 
> So both are useful, and if you have both segmentations and landmarks, I would use both to measure results.

Thank you very much for your help
