### ISSUE TITLE
How to apply the affine matrix from SynthMorph

### ISSUE THREAD

**Issue by Ireneyou33** [voxelmorph/voxelmorph#597]
Hi SynthMorph developers, 

Thank you for the fantastic job you've been doing. SynthMorph is seriously impressive, I've been playing with it a bit and everything went smooth when I'm applying the `affine.txt` and the `transvoxel.npz` generated by SynthMorph **forward**, but failed to apply them **backward**.

Say I have a `moving` image oriented in LIA, a `fixed` image oriented in RAS, and corresponding outputs (`affine.txt` and `transvoxel.npz`). What I’m trying to do is register an original `bold` to the `fixed` image with a **single** interpolation, where the `moving` image serves as an intermediary. That is 

1. generating a meshgrid in `fixed.shape` 
2. add the local shift from `transvoxel.npz` 
3. map the native fixed vox space to the world space (RAS) by multiplying with the `fixed.affine` 
4. multiply the `affine.txt` which operates in the world space, going from the `fixed` to the `moving`. 

**This is where I get stuck,** if I can resolve this, I can continue to apply a series of transformations, map the coords to the native `bold` vox space, and finally perform a single interpolation using the original `bold` values, and save it with `nib.Nifti1Image(interp_values, affine=fixed.affine)`. 

To be specific, I attatched my code here:
```python
# load moving and fixed images
moving_file = 'moving.nii.gz' # oriented in LIA
moving = nib.load(moving_file)
fixed_file = 'fixed.nii.gz' # oriented in RAS
fixed = nib.load(fixed_file)

# generate a meshgrid in fixed.shape
i = np.linspace(0, fixed.shape[0] - 1, fixed.shape[0])
j = np.linspace(0, fixed.shape[1] - 1, fixed.shape[1])
k = np.linspace(0, fixed.shape[2] - 1, fixed.shape[2])
mesh = np.meshgrid(i, j, k, indexing='ij')

# add the non-linear local shift to obtain the warped meshgrid in the native fixed vox space
nonlinear_file = 'transvoxel.npz'     
data = np.load(nonlinear_file)
warp_matrix = data[data.files[0]]
warped_mesh = [mesh[d].astype(np.float32) + warp_matrix[..., d] for d in range(3)]  
warped_mesh = np.asarray(warped_mesh, dtype=np.float32)
```

  I paused here to visualize and check if this step is correct. The output shows
```python
# interpolate with the moving values
output = np.zeros(
                list(fixed.shape),
                order='F',
                dtype=np.float64
              )
result = ndi.map_coordinates(
              moving.get_fdata(),
              warped_mesh,
              output=output,
              order=3,
              mode='constant',
              cval=0.0,
              prefilter=True,
            )
nib.save(nib.Nifti1Image(result, affine=fixed.affine), output_path)
```
![image](https://github.com/voxelmorph/voxelmorph/assets/55998411/f7ff3d43-f391-4b67-8566-ddf319cf1f94)

Looks good! I assume what I’ve done so far is correct.

Then I continued from where I paused.
```python
# map the native fixed vox space to the world space (RAS)
warped_mesh = warped_mesh.reshape(3, -1)
fixed_vox2ras_rot = fixed.affine[:3, :3]
fixed_vox2ras_trans = fixed.affine[:3, -1:]
warped_mesh = fixed_vox2ras_trans + fixed_vox2ras_rot @ warped_mesh

# load the affine matrix
# based on my understanding, the affine matrix works on the world space, and maps from the fixed to the moving.
ras2ras_file = 'affine.txt'
ras2ras= np.loadtxt(ras2ras_file, delimiter=' ')

# goes from the world space to the native moving vox space by multiplying the inverse of the moving.affine matrix
ras2vox = np.linalg.inv(moving.affine) @ ras2ras 
A = ras2vox[:3, :3]
b = ras2vox[:3, -1:]
warped_mesh = A @ warped_mesh + b
warped_mesh = warped_mesh.reshape(3,*fixed.shape)

# interpolate with the moving values
output = np.zeros(
                list(fixed.shape),
                order='F',
                dtype=np.float64
            )
result = ndi.map_coordinates(
              moving.get_fdata(),
              warped_mesh,
              output=output,
              order=3,
              mode='constant',
              cval=0.0,
              prefilter=True,
          )
nib.save(nib.Nifti1Image(result, affine=fixed.affine), output_path)
```
But this output seems to have the wrong orientation, swapped axes (A-P and S-I), and a shifted center (maybe wrong translation).
![image](https://github.com/voxelmorph/voxelmorph/assets/55998411/3970731e-40dc-4bd5-8f1f-d1a5b2fda4ed)

I’m aware that there is a zero-based and zero-centered conversion during registration. Based on my knowledge, the final output `affine.txt` operates in the zero-based indices, which can be applied directly to the warped mesh (transvoxel.npz + meshgrid), as this mesh also employs zero-based indices.

I think I messed up the affine matrix somewhere, but couldn’t figure it out. Any help would be appreciated!

**Comment by adalca** [comment]
pinging @mu40  who is our resident synthmorph expert :)

**Comment by mu40** [comment]
Hi Irene, with what version and SynthMorph commands did you obtain the transforms? I’m asking because I don't remember a version that saves a warp field in voxel space.

I suspect the moving image or warp field are not what you think they are. If the warp goes from fixed voxel coordinates to after-affine-moving voxel coordinates, then the first step should *not* produce an image that aligns with the fixed image, because no affine registration and LIA-to-RAS conversion has happened yet.

If the moved image does align with the fixed image after step 1, then either the warp field includes the affine transform and goes all the way to the original LIA space or the moving image is the result of a previous affine registration step.

**Comment by Ireneyou33** [comment]
Thanks to @adalca for getting us some expert @mu40 help! 

Good news: we realized the SynthMorph version we were using was outdated, so we've switched to the latest one, `freesurfer/synthmorph:2`. Bummer, though—the old Docker image got taken down, and I couldn't track down its version number, so I've attached the Python file and command here mri_bold_synthmorph.py.  
[mri_bold_synthmorph.txt](https://github.com/voxelmorph/voxelmorph/files/15109227/mri_bold_synthmorph.txt)

```python
# affine
mri_synthmorph.py -m affine -t affine.txt -o moved.nii.gz moving.nii.gz fixed.nii.gz
# non-linear
mri_synthmorph.py -i affine.txt -o moved.nii.gz moving.nii.gz fixed.nii.gz
```
Bad news: Despite the update, I'm still facing the same problem. 


## Based on the old version
### Q1.
According to @mu40, 

> If the warp goes from fixed voxel coordinates to after-affine-moving voxel coordinates, then the first step should not produce an image that aligns with the fixed image, because no affine registration and LIA-to-RAS conversion has happened yet.

I assume the warp works in the native fixed voxel space because the `transvoxel.npz` stores `trans_vox` values, and that's the only situation that gives me a result that somewhat makes sense (as the first fig in the last post shows). Unfortunately, the result aligns with the fixed image, not the moving image. The Fig1 here gives a better visualisation.
![mesh+nonlinear fixed moving](https://github.com/voxelmorph/voxelmorph/assets/55998411/f5e67321-af7d-4402-a33d-608eeac2b0bf)
Fig1. The brain in red is the transvoxel.npz (vox space) + meshgrid, which aligns with the fixed image (left), not the moving image (right).


### Q2.
If I assume it works in world space, that’s the Fig2
```python

# 1) load moving and fixed images
fixed_file = 'fixed.nii.gz' # oriented in RAS
fixed = nib.load(fixed_file)
ras2vox = np.linalg.inv(fixed.affine)
fixed_ras2vox_rot = ras2vox[:3, :3]
fixed_ras2vox_trans = ras2vox[:3, -1:]

# 2) generate a meshgrid in fixed.shape
i = np.linspace(0, fixed.shape[0] - 1, fixed.shape[0])
j = np.linspace(0, fixed.shape[1] - 1, fixed.shape[1])
k = np.linspace(0, fixed.shape[2] - 1, fixed.shape[2])
mesh = np.meshgrid(i, j, k, indexing='ij')

# 3) Assume the non-linear local shift works in the world space, 
# no affine, no LIA-to-RAS conversion.
nonlinear_file = 'transvoxel.npz'     
data = np.load(nonlinear_file)
warp_matrix = data[data.files[0]]
warped_mesh = [mesh[d].astype(np.float32) + warp_matrix[..., d] for d in range(3)]  
warped_mesh = np.asarray(warped_mesh, dtype=np.float32)
warped_mesh = warped_mesh.reshape(3, -1)
# goes from the world space to the native fixed vox space
warped_mesh = fixed_ras2vox_trans + fixed_ras2vox_rot @ warped_mesh


# 4) As no LIA-to-RAS conversion has taken place yet, the moving file should be oriented in RAS. 
# So I convert the moving.nii.gz to moving_RAS.nii.gz, and interp with its values.
moving_file = 'moving_RAS.nii.gz' # oriented in RAS
moving = nib.load(moving_file)

# 5) reshape and interp as usual
warped_mesh = warped_mesh.reshape(3,*fixed.shape)
    # interp values
    output = np.zeros(
        list(fixed.shape),
        order='F',
        dtype=np.float64
    )
    result = ndi.map_coordinates(
        moving.get_fdata(),
        warped_mesh,
        output=output,
        order=3,
        mode='constant',
        cval=0.0,
        prefilter=True,
    )
nib.save(nib.Nifti1Image(result, affine=fixed.affine), output_path)
```
![image](https://github.com/voxelmorph/voxelmorph/assets/55998411/7cd7b877-f9fd-464e-a81e-e065517a8592)
Fig2. Assuming `transvoxel.npz` works in the world space, no affine, no LIA-to-RAS conversion.


### Q3.
According to @mu40, I guess the conclusions drawn from the last paragraph stem from the assumption made in the second one. So, 

> If the warp goes from fixed voxel coordinates to after-affine-moving voxel coordinates...... the moved image does align with the fixed image after step 1, then a) either the warp field includes the affine transform and goes all the way to the original LIA space b) or the moving image is the result of a previous affine registration step.

a) sounds like step 2 in the previous post is not necessary, and I’m good to move on. Am I on the right track? b) the `moving` is clearly not an after-affine-moving image, as shown in Fig1. 

Stuck again, but didn’t give up!

## Move on to the latest version.
Pulled the latest docker `freesurfer/synthmorph:2`
`mri_synthmorph.py`
``` python
moving.nii.gz
fixed.nii.gz
-o moved.nii.gz
-t joint/trans.nii.gz
-T joint/inverse.nii.gz
```

### Q4.
This time, I clearly noticed that the `trans.nii.gz` operates in the world space, jointly performed affine and warp, which goes from fixed-to-moving, RAS-to-LIA. Hence,
```python 
# 1) same moving and fixed images
moving_file = 'moving.nii.gz' # oriented in LIA
moving = nib.load(moving_file)
fixed_file = 'fixed.nii.gz' # oriented in RAS
fixed = nib.load(fixed_file)

# 2) same meshgrid in fixed.shape
i = np.linspace(0, fixed.shape[0] - 1, fixed.shape[0])
j = np.linspace(0, fixed.shape[1] - 1, fixed.shape[1])
k = np.linspace(0, fixed.shape[2] - 1, fixed.shape[2])
mesh = np.meshgrid(i, j, k, indexing='ij')

# 3) NEW warp field from trans.nii.gz, worldspace-to-worldspace, RAS-to-LIA, fixed-to-moving
nonlinear_file = ' trans.nii.gz'     
warp_matrix = nib.load(nonlinear_file).get_fdata()
warped_mesh = [mesh[d].astype(np.float32) + warp_matrix[..., d] for d in range(3)]  
warped_mesh = np.asarray(warped_mesh, dtype=np.float32)
warped_mesh = warped_mesh.reshape(3, -1)

# 4) maps the coords from the world space to the native moving vox space by multiplying the inverse of moving.affine.
ras2vox = np.linalg.inv(t1.affine)
A = ras2vox[:3, :3]
b = ras2vox[:3, -1:]
warped_mesh = A @ warped_mesh + b

# 5) reshape and interp as usual
......
```
![Picture1](https://github.com/voxelmorph/voxelmorph/assets/55998411/6e241088-ad35-43b8-b495-39035679cbc8)
Fig3. `(trans.nii.gz + meshgrid) @ inv(moving.affine).`

I ran out of ideas! I'd really appreciate some insight on this one! :D

**Comment by mu40** [comment]
Never give up!

1. We still have image [tags 1 and 2 on the Docker Hub](https://hub.docker.com/r/freesurfer/synthmorph/tags) and links to the [relevant commits under Overview](https://hub.docker.com/r/freesurfer/synthmorph). You edited the Python script to save the intermediate transform `trans_vox`: this displacement field will include any affine transform you initialize with, explaining why the images match when you apply the warp but no longer match after applying the affine transform (a second time).

1. The intermediate displacement field you saved as transvoxel.npz transforms fixed voxel coordinates to moving voxel coordinates, so it would make sense for it to align with the fixed image in FreeView, as you showed.

1. Yes, step 1 of your first post should have been all you needed to do.

1. As part of step 3, you applied the world-space coordinate shift `warp_matrix` to fixed voxel coordinates. Do you first have to transform the fixed voxel coordinates `mesh` to RAS using `fixed.affine`?

**Comment by Ireneyou33** [comment]
Thank you sooo much, @mu40! I figured out both versions! 

_New version:_ Just like you said in step 4, I converted the `mesh` to the world space using `fixed.affine`, and got a beautiful result!

_Old version:_ I continued from the step 1 in the first post, and everything else came together smoothly!

Thank you once again for your kindness and support! You rock!
