### ISSUE TITLE
Torch train.py problem

### ISSUE THREAD

**Issue by TrikstarP** [voxelmorph/voxelmorph#599]
what are you trying to do/register?
to train both CT and MR image(files mixed) of my own datasets spine L1-L5 using example code from torch, train.py

Problem?
RuntimeError: input size (32x248x150x1). calculated output size: (32x124x75x0) is too small

![issue1](https://github.com/voxelmorph/voxelmorph/assets/99407740/3389d417-7a0f-4524-90d5-dab361ab78dd)

What have i tried?
-in networks.py, tinker with kernel_size, padding, stride -> doesnt works, produces same error
-increase input files size(width,height) -> doesnt works, produces same error with different pixel value
-in networks.py, decrease max_pool=2 to max_pool=1 -> produces new problems in layers.py spatialTransformer: The size of tensfor a (3) must match tensor b (2) at non-singleton dimension4

![issue3](https://github.com/voxelmorph/voxelmorph/assets/99407740/569adea0-0d7a-47be-bbd6-6c21261702f0)

im wondering if my approach is correct before trying to change everything else

**Comment by anudeepk17** [comment]
Hey I am facing the same issue. How did you solve it? Thanks!

**Comment by TrikstarP** [comment]
> Hey I am facing the same issue. How did you solve it? Thanks!

Make sure all the data files are the same size(dimension) in x,y,z and make it divisible by 16, for example all data sizes are 192, 96, 192. If your data size is too big it would also produce the same problem, for example I tried 640, 640, 640 and it produced the same error
