### ISSUE TITLE
Using lung segmentation during training

### ISSUE THREAD

**Issue by paul-quique** [voxelmorph/voxelmorph#604]
Hello VoxelMorph Team,

I have read your scientific paper (thank you for your work on this impressive project!) and learned that segmentation can be utilized during the training of the model. I managed to train a model that works well on lung images without using segmentation.

However, I am having difficulty finding Python code examples that demonstrate how to train VoxelMorph using my segmented lung masks. Could you please provide guidance or an example for this?

Thank you for your assistance!

Best regards,
Paul

**Comment by adalca** [comment]
Hi @paul-quique 
Thanks for your message. Have you taken a look at this script? https://github.com/voxelmorph/voxelmorph/blob/dev/scripts/tf/train_semisupervised_seg.py

**Comment by paul-quique** [comment]
I'm trying to adapt it to my usage! My problem is solved thanks !
