### ISSUE TITLE
How to use the HyperVxmJoint network

### ISSUE THREAD

**Issue by Pei-mao** [voxelmorph/voxelmorph#611]
Excuse me, I have been using the method you proposed recently. Thank you for your contributions to the medical field. 
I have a question. 
HyperVxmJoint is used to train affine registration networks for multi-contrast brain images, right?
Why haven't you released the training code for using this network?

**Comment by mu40** [comment]
Thank you for your interest in our work! [Training scripts](https://github.com/voxelmorph/voxelmorph/tree/dev/scripts/tf) for affine and joint affine-deformable registration with SynthMorph are now available. We currently use the `VxmAffineFeatureDetector` network for affine and `HyperVxmJoint` for joint registration.

**Comment by Pei-mao** [comment]
Thank you very much, I will give it a try.
