### ISSUE TITLE
about normalization

### ISSUE THREAD

**Issue by zzx332** [voxelmorph/voxelmorph#62]
hi,
I want to know if your normalization operation normalized to 0-1?
Did you use freesurfer to complete it?But Freesurfer cannot normalized it to 0-1.

**Comment by adalca** [comment]
we took the `norm.mgz` given by FreeSurfer and divded by 255 (which is overkill since the volumes are only up to 128, but this was to be consistent with some other processing). So in reality our data is in [0, 0.5], but that's a subset of [0, 1] :)

**Comment by zzx332** [comment]
thank you!
