### ISSUE TITLE
Errors creating model with image dimensions (160, 192, 220) 

### ISSUE THREAD

**Issue by mpernow** [voxelmorph/voxelmorph#621]
Hi,
I am getting an issue when creating a VoxelMorph model with certain image dimensions. For example, the following:
```
vol_shape = (160, 192, 220)
nb_features = [
    [16, 32, 32, 32],
    [32, 32, 32, 32, 32, 16, 16]
]
vxm_model = vxm.networks.VxmDense(vol_shape, nb_features, int_steps=0)
```
produces the error:
`ValueError: A `Concatenate` layer requires inputs with matching shapes except for the concatenation axis. Received: input_shape=[(None, 20, 24, 26, 32), (None, 20, 24, 27, 32)]`.

On the other hand, using `vol_shape = (160, 192, 224)` works. 
Similarly, `vol_shape = (512, 512, 112)` works but `vol_shape = (512, 512, 50)` does not.

What is the cause of this and how can I make VoxelMorph work with other image shapes?

I installed VoxelMorph from source a few weeks ago. I also installed neurite from source a few weeks ago. I use Keras version 3.4.1 and Tensorflow version 2.16.2.

**Comment by Magic-Xin** [comment]
Given that your model consists of 4 encode layers ([16, 32, 32, 32] in nb_features), each dimension will be halved four times. However, when you set the third dimension of vol_shape to 220, it cannot be an integer after being divided by 2 three times, resulting in an error. Similarly, the configuration (512, 512, 50) encounters the same issue, as the dimensions cannot be integers following the downsampling process.

**Comment by mpernow** [comment]
Thanks, that makes a lot of sense!
