### ISSUE TITLE
freesurfer talairace

### ISSUE THREAD

**Issue by zzx332** [voxelmorph/voxelmorph#63]
hi,
sorry to bother you again.
I want to do the same preprocess on input as you.I do not know how to use Freesurfer to affine alignment.I use the following command:
recon-all -i my_nii_file -s subjd -talairach -motioncor
Output a transform matrix(talairach.xfm).Should I use this matrix to transform my original image?
The matrix is as follows:

Linear_Transform = 
1.186050 -0.019824 0.021026 141.668289
0.030688 1.376910 0.008199 -140.199280
-0.029249 -0.272340 1.468586 -166.189056;
Is the last column a bias?Why are they so big?How to use this matrix to transform my original image?
sry that I have too many problems using this software to preprocess the data. I want to be consistent with your preprocess in the paper...
I am going to use the Freesurfer for skull stripping, affine alignment, and normalization. Is these processing enough?

**Comment by adalca** [comment]
yes, this sounds right. We use 
`mri_convert` with the option `--apply_transform`. 

The last column is a translation with respect to a coordinate system used by FreeSurfer  (see http://www.grahamwideman.com/gw/brain/fs/coords/fscoords.htm). 

FreeSurfer should give you all those aspects, all we did after freesurfer was divide by 255 and crop.

**Comment by hassaanmahmood** [comment]
@adalca 
hi
1-if we run complete recon-all , is brain.mgz is already transformed to talairach in the end, Or do we need to use mri_convert after running complete recone-all?
2- after doing talairach transform, even then do we need to affinely register input volume to atlas volume provided by?
Thanks.

**Comment by adalca** [comment]
@hassaanmahmood I forget about brain.mgz, but we used norm.mgz. If you used the tralairach transform, you should not have to do any more affine warping.

**Comment by norris9410** [comment]
Hi, thanks for your work.

based on your comments:

> @hassaanmahmood I forget about brain.mgz, but we used norm.mgz. If you used the tralairach transform, you should not have to do any more affine warping.

> yes, this sounds right. We use
> `mri_convert` with the option `--apply_transform`.


Just to confirm, did you use "mri_convert on norm.mgz with the option --apply_transform talairach.xfm"?

Thanks in advance

**Comment by adalca** [comment]
@norris9410  yeah i believe that's right

**Comment by norris9410** [comment]
Thanks for quick response!

I have a follow-up question:

Is the "atlas_norm.nii.gz" and "test_vol.nii.gz" affinely registered to talairach space? The 1st and 2nd image below are 3D slice of atlas_norm.nii.gz and test_vol.nii.gz, looks like they are affinely registered and are ready to be trained/evaluate. But the following 3rd image is output from freesurfer registered talairach space, it seems to be in a different orientation compared to atlas_norm and test_vol. 

(the 3rd image is obtained by: original image -> freesurfer recon-all -> mri_convert with apply_transform of talairach.xfm)

![11](https://user-images.githubusercontent.com/32683143/80731385-10501f00-8ac8-11ea-888e-d8b52a9c8682.png)

Could you please tell me why may cause this difference?

Thank you for your time!

**Comment by adalca** [comment]
@norris9410 
There might be a couple of reasons for the differences, but basically I think somewhere along the way the file headers got dropped, which is why you'll see this flip. You should feel free to work with whatever space you want.

**Comment by GYDDHPY** [comment]
@adalca 
Hi, I was confused of the process of freesurfer. 
To get affine spatial normalization, I use the `recon-all` command with `autorecon1` and obtain the talairach.xfm file. Then I use mri_convert with `--apply_transform` option. Here's the code I used:

```
recon-all -parallel -i $sample_path -autorecon1 -subjid $sample_name -cw256

mri_convert --apply_transform mri/transforms/talairach.xfm \
mri/brainmask.mgz \
mri/brainmask_align.mgz
```
This operation moves the brain outside of the image boundary.
I also tried this which is suggested by freesurfer mri_convert documentaion:
```
mri_convert --apply_transform mri/transforms/talairach.xfm \
-oc 0 0 0 \
mri/brainmask.mgz \
mri/brainmask_align.mgz
```
This give a weird result like this:
![image](https://github.com/voxelmorph/voxelmorph/assets/56216381/2091fb59-8006-4d92-98fd-b39483ba8e0c)

I'm not sure why this happens. Do I need to modify image origin before using freesurfer? 
I'm new to this tool. Could you please suggest me more details of the way you using freesurfer to process images?

Looking forward to your reply.
