### ISSUE TITLE
brain seg data is no longer integer for each voxel after affine registered to atlas

### ISSUE THREAD

**Issue by Liang-MAC** [voxelmorph/voxelmorph#65]
Hi,
I use freesurfer to generate brainmask.mgz and aseg.mgz and follow your instruction to use ANTs to do affine registration to atlas. The test data you provide look very good and each voxel is integer (labels), while my aseg data are changed to non-integer shown in fig after affine transformation which decrease the dice accuracy.(Mine is 0.66 while yours is 0.76)
![Screenshot from 2019-06-22 22-32-28](https://user-images.githubusercontent.com/52104503/59965247-0ff90600-953e-11e9-884d-5bda3d6f70e5.png)
The commands I used are
antsRegistrationSyNQuick.sh -d 3 -f $FixedImage_path -m $MovingImage_path -o $T_affine_matrix_saving_path -t a
antsApplyTransforms -d 3 -i $aseg_path -o $Affined_aseg_path -r $FixedImage_path -t $Affine_0GenericAffine_path

Could you please tell me how you process the aseg.mgz data?
Best regards,
Liang

**Comment by Liang-MAC** [comment]
I refer to #37 to solve the issue
 thanks

**Comment by adalca** [comment]
I'm glad this was solved, thanks for following up!
