### ISSUE TITLE
Code calculating number of locations where the predicted deformation has negative jacobian

### ISSUE THREAD

**Issue by dykuang** [voxelmorph/voxelmorph#66]
Hello,
Great work! 
I am doing a project that requires examining the predicted deformations. I looked at the test scripts and did not find codes that calculate number of locations where the predicted deformations has negative Jacobians. 
Could you point out where I can find relevant codes for the calculation? Thanks.

**Comment by adalca** [comment]
sorry for the delay, we're working on releasing this part asap along with a major update. Stay tuned!

**Comment by adalca** [comment]
Since the major update is taking us more than we wanted, note that we showed example code for the jacobians in #82
