### ISSUE TITLE
Surface loss

### ISSUE THREAD

**Issue by SANCHES-Pedro** [voxelmorph/voxelmorph#67]
Hi,

Can you share the code for the surface loss that you used in the last paper?

Thanks for the great work!

**Comment by adalca** [comment]
sorry for the delay, we're working on releasing this part asap. Stay tuned!

**Comment by yf817** [comment]
Stay tuned!

**Comment by j-portmann** [comment]
I'm joining beeing tuned.
Together with the loss it would be great, if you also could explain how you put in images and the surfaces at the same time for the training as you describe in said paper.
Many thanks from my side, too!

**Comment by adalca** [comment]
I'm just catching up on these older issues -- in the new `master` branch, we have implementations for this in `train_surf_semisupervised.py` which relies on `VxmDenseSemiSupervisedPointCloud` model. Can you all check if these meet your questions?
