### ISSUE TITLE
Shape of warp transform

### ISSUE THREAD

**Issue by vmadge** [voxelmorph/voxelmorph#71]
Hello,

I have noticed that VoxelMorph outputs a warp grid with the shape (80,96,112,6), and I have a few questions regarding this shape:
1. The warp grid has 6 elements in the vector dimension, is this because it is storing the forward and backward transform simultaneously? 
2. When the warp grid is half of the size of the resampled volume, how do the voxel centres line up?
3. Where are the transforms applied within the code? I came across a potential resampling in utils.py, but was not 100% sure this was the resampling code.

Any information on these questions would be very helpful.
Thank you.

**Comment by adalca** [comment]
Hi @vmadge ,

Assuming you are referring to the MICCAI version of the code:
1. the first 3 dimensions are the mean of the expected velocity field, and the last 3 dimensions are the log_variance. 
2. Good question, I think the most specific way to answer is to send you to the code that we use to resize this deformation, and specifically look at how we treat the voxel shifts there -- https://github.com/adalca/neuron/blob/f356f3519b1ff2f1d10701b07c32afbf7361ce01/neuron/utils.py#L185. 
3. assuming you are usign the `miccai2018_net`, we use the SpatialTransformer (the last layer) (see last lines in that function) to warp. This references a layer we wrote, which calls `transform` in `neuron.utils`, which uses `neuron.utils.interpn`. 

Hope this helps!
- Adrian
