### ISSUE TITLE
How to train my own data?

### ISSUE THREAD

**Issue by omarhany1** [voxelmorph/voxelmorph#72]
Hello,

I wanted to know how to process the JPG images to be able to train my own data set?

Should I create a .npz file? And if so how to do that

Thank you

**Comment by adalca** [comment]
hi @omarhany1 

What are you registering? I would simply modify `load_volfile` to load in `jpg` files, probably using `scipy.misc.imread`. After that, the main requirement is that the images are the same size and very roughly rigidly aligned. Several other people on this forum have used jpg, so I would encourage you to read through the solved issues.

Thanks,
- Adrian

**Comment by omarhany1** [comment]
I am registering 2d ultra sound images.

Actually I don't quite understand, does the vol_data contain all images that are to be registered together or is it split into sub objects each containing a set of images that are to be registered together separately?

Thank you for your help

**Comment by adalca** [comment]
In our setup, each file in the folder is a (3D) scan -- so a stack of size 160x192x224.

**Comment by norris9410** [comment]
Hi Adrian,
Just a quick question, if i want to train the network to register 2 images, I should use subject-to-subject (miccai2018_gen_s2s) instead of atlas-based (miccai2018_gen) correct?

**Comment by adalca** [comment]
@norris9410 yup

**Comment by omarhany1** [comment]
Hi,
I still could not figure out how to modify the data loading phase to read jpg files.
I see that in train.py there is a lot to do with atlas manipulation which I am not familiar with.
Is there a direct way to transform a set of jpg images to an npz file?

**Comment by adalca** [comment]
sure, if you want to create an npz from jpg (although I'm worried about you having had jpgs in the first place) simply stack all the images from the same volume with `np.stack`, then save them using something like `np.savez('myfile.npz', vol_data=stacked_volume)`

**Comment by yohset95** [comment]
Hi Adrian,

How to open the .npz files? Or is there any software to see the images in .npz file? Thank you

**Comment by John1231983** [comment]
@yohset95 : This is numpy format. Just use numpy.load('your npz')

**Comment by yohset95** [comment]
Okey @John1231983 
Is in the '.npz' contains '.nii' or '.dcm'? Thanks

**Comment by John1231983** [comment]
just contains the vol array. Other information likes spacing, direction... are deleted

**Comment by adalca** [comment]
you can, of course, feel free to use `.nii` files or add header information to the `npz`.
