### ISSUE TITLE
MacOS updates

### ISSUE THREAD

**Issue by ankitaich09** [voxelmorph/voxelmorph#73]
The module named Neuron is not supported for Mac. Is there a way to work around this or do I have to find a windows machine and run the code there?

**Comment by adalca** [comment]
Sorry, I'm not sure I understand what you mean by neuron not being supported for mac?

`neuron` (at least the one used in voxelmorph) is simply a library we wrote, and it's included with the voxelmorph repo. There shouldn't be anything specific to windows in it (in fact most, if not all, of our work is in linux)

**Comment by ankitaich09** [comment]
Yeah I got it working, it was something wrong I was doing.

**Comment by Kanyq** [comment]
Hello, while trying to run "train.py" to train the model with liver MRI data. I'm getting an error saying, "No module named 'voxelmorph'". I'm not sure, if I'm doing something wrong here. Please let me know.
![Screenshot 2020-12-14 at 21 43 59](https://user-images.githubusercontent.com/14558146/102133539-8a65c600-3e55-11eb-888b-94db69cfefd3.png)
