### ISSUE TITLE
Dice Score instead Surface Distance in loss function.

### ISSUE THREAD

**Issue by bashkanov** [voxelmorph/voxelmorph#74]
Hi. Great work is done! Thank you for sharing this code.
I have looked at your derivation of main loss and how you define reconstruction and surface loss, and I'm curious whether it is the right way to introduce the dice loss in the main objective function as I did? (Note that dice is negative)
```
 def shape_loss(self, y_true, y_pred):
        """ shape matching loss """
        return 1. / (self.shape_sigma ** 2) * K.mean(-self.dice_coef(y_true, y_pred))
```
I’m eager to receive your response!

**Comment by adalca** [comment]
hi @bashkanov 

This seems like a reasonable implementation to me (assuming `dice_coef` is a function that outputs the Dice coefficient).
