### ISSUE TITLE
Size mismatch?

### ISSUE THREAD

**Issue by ankitaich09** [voxelmorph/voxelmorph#75]
When I try to run train_miccai2018.py as follows.

1. Moved train_vol.npz to a new folder called test_data.
2. Atlast_norm.npz in another folder called npz
3. Running 

train_miccai2018.py C:/Users/cisguest/Downloads/voxelmorph-master/voxelmorph-master/test_data --atlas_file C:/Users/cisguest/Downloads/voxelmorph-master/voxelmorph-master/npz/atlas_norm.npz --gpu 0

getting error 

F .\tensorflow/core/util/mkl_util.h:607] Check failed: dims == sizes.size() (5 vs. 4)

and python crashes.

What am I doing wrong?

**Comment by ShibaPrasad** [comment]
Hi ,
Need a small help. I am trying to reproduce the code. But I donot have the below for testing. I have seen the below instruction - on the website.

    Put test filenames in data/test_examples.txt, and anatomical labels in data/test_labels.mat.

Would you please share the above required data to reproduce the result?

**Comment by adalca** [comment]
sorry for the delay, -- can you provide more detail (e.g. what is the full error trace, for example). Note that you should not be *training* a new model with the test volume -- while this should not give you an error, it won't do anything too interesting. You could try running `register.py` with our test subject, though.
