### ISSUE TITLE
Issue on running the test_miccai2018.py

### ISSUE THREAD

**Issue by ShibaPrasad** [voxelmorph/voxelmorph#76]
Hi All,

I am trying to reproduce the code for my future work and would like to make sure with existing data (reproduce). I have not trained the model and using the exiting models (.h5).

**_Executed command:_** 
test_miccai2018.py --gpu 0 --model_dir /user/iibi/skuanar/Downloads/voxelmorph/models 10 and getting below error at  test_brain_file = open('...path/here//test_examples.txt')

**Errror Message:**
/voxelmorph/src/test_miccai2018.py --gpu 0 --model_dir /user/iibi/skuanar/Downloads/voxelmorph/models 10
Using TensorFlow backend.
Traceback (most recent call last):
  File "Downloads/voxelmorph/src/test_miccai2018.py", line 27, in <module>
    test_brain_file = open('...path/here//test_examples.txt')
FileNotFoundError: [Errno 2] No such file or directory: '...path/here//test_examples.txt'

**_instruction_**
According to instruction I need to put 
- Put test filenames in data/test_examples.txt, and anatomical labels in data/test_labels.mat.

**Would you please provide me files to reproduce the results?**

**Comment by adalca** [comment]
Hi @ShibaPrasad 

Unfortunately we cannot provide the datasets as they are not ours and the agreements do not allow us to redistribute them. Please see issue #12 for more details. The name of all the datasets are in the paper.

If you get these data or have your own data, please:
- put them in a folder
- to use our test.py please see how to construct a [`test_examples.txt` file here](https://github.com/voxelmorph/voxelmorph/issues/48#issuecomment-497709534)


Would you please remove your posts in the three other unrelated threads that were about other topics? 

Thank you!

**Comment by qiheihelan** [comment]
@ShibaPrasad Hello. Can you solve this problem? I also have this problem at runtime. Can you tell me how to solve it?

**Comment by adalca** [comment]
@qiheihelan please see my response in #80
