### ISSUE TITLE
Convolution on Dense STN

### ISSUE THREAD

**Issue by nazib** [voxelmorph/voxelmorph#77]
Hi @adalca 
I found that the STN implementation used in your code provide a warped tensor with all the shapes "None". For my work I tried to use your implementation (surely I will acknowledge you if we publish it) and wanted to apply convolution operation on the dense STN output. But tensorflow does not allow it due to "None" in shape. Is there any way to get a tensor from your STN with shape other then None.
Hope you understand. 
Kind regards
Abdullah

**Comment by adalca** [comment]
@nazib interesting, I did not notice that output shape, I will look into it. 
In the meanwhile, one quick way to get around this is to reshape the output of the layer to what you want (e.g. the input size, if you're sure this is the case): in layers.py in the STN class, change:

```
        # map transform across batch
        if self.single_transform:
            fn = lambda x: self._single_transform([x, trf[0,:]])
            return tf.map_fn(fn, vol, dtype=tf.float32)
        else:
            return tf.map_fn(self._single_transform, [vol, trf], dtype=tf.float32)
```

to 

```
        # map transform across batch
        if self.single_transform:
            fn = lambda x: self._single_transform([x, trf[0,:]])
            outvol = tf.map_fn(fn, vol, dtype=tf.float32)
        else:
            outvol = tf.map_fn(self._single_transform, [vol, trf], dtype=tf.float32)

        return K.reshape(outvol, [-1, *self.inshape[0][1:]])
```

Warning - I have not tested this, but I think this is along the lines of what you want.

**Comment by nazib** [comment]
Hi @adalca 
Sorry, I was using the first version of Dense STN. I just check your present version and it works fine. THanks a lot.

**Comment by adalca** [comment]
great!
