### ISSUE TITLE
test_seg.npz and my own data aseg.mgz

### ISSUE THREAD

**Issue by xyzxzj** [voxelmorph/voxelmorph#78]
Hi,
I use freesurfer to generate norm.mgz and aseg.mgz and follow your preprocess steps describe in your paper.
1-intensity normalize to [0-1] for norm.mgz
2-crop for norm.mgz and aseg.mgz
3-affine transformation using FSL flirt for norm.mgz and aseg.mgz
I just use the following cmd to register my norm.nii.gz,it performs well.
python3  register.py  ../data/norml.nii.gz ../data/atlas_norm.nii.gz --out_img ../data/out.nii.gz --model_file ../models/cvpr2018_vm2_cc.h5
When I want to use the aseg.npz to test the dice,I found that the aseg.nii.gz was different from the atlas_seg.nii.gz which you supply.the segmentation parts of aseg.nii.gz was different from the atlas_seg.nii.gz.but the aseg.nii.gz was generated from freesurfer recon-all  .
![image](https://user-images.githubusercontent.com/43518644/61780733-9f435300-ae35-11e9-917c-427555e0d29a.png) aseg.nii.gz
![image](https://user-images.githubusercontent.com/43518644/61780808-c863e380-ae35-11e9-9478-3c2ab7b412c9.png) atlas_seg.nii.gz

Could you please tell me why my aseg.nii.gz was different from your atlas_seg.nii.gz,and I found they have the same labels in the volume.
Best regards,
xiang

**Comment by balakg** [comment]
Hi, sorry for the late reply. The atlas_seg.nii.gz and aseg may contain slightly different number of structures. Just use the labels.mat file as shown in 'test.py' for the 30 structures that we used. These structures are the ones we found to be shared among all our test data and the atlas.

**Comment by xyzxzj** [comment]
Hi,
I use the aseg.nii.gz and label.mat to test the dice ,using the following command:

python3 test.py ../models/cvpr2018_vm2_cc.h5 0

![image](https://user-images.githubusercontent.com/43518644/63399740-0d167680-c404-11e9-97a8-a317afd3375f.png)
 the dice was low,but i  use the following cmd to register my norm.nii.gz,it performs well.
python3 register.py ../data/norml.nii.gz ../data/atlas_norm.nii.gz --out_img ../data/out.nii.gz --model_file ../models/cvpr2018_vm2_cc.h5
The following picture is preprocessed image,atas image ,and result moved image.
![image](https://user-images.githubusercontent.com/43518644/63399970-ce34f080-c404-11e9-9833-fe34ae06ce06.png) 
![image](https://user-images.githubusercontent.com/43518644/63399963-bfe6d480-c404-11e9-88ee-e584210784a3.png)
![image](https://user-images.githubusercontent.com/43518644/63399933-a5146000-c404-11e9-862a-c6f06ee7fcce.png)

and I found that the  aseg.nii.gz was generated from freesurfer recon-all  the aseg.nii.gz was different from the atlas_seg.nii.gz which you supply. the segmentation parts of aseg.nii.gz was different from the atlas_seg.nii.gz. but .So I don't know where something went wrong.

**Comment by adalca** [comment]
what result do you get if you use the provided `test_seg.npz`?

**Comment by xyzxzj** [comment]
Hi:
 I use the 
python3 test.py ../models/cvpr2018_vm2_cc.h5 0
to test test_seg.npz ,the dice result is :
![image](https://user-images.githubusercontent.com/43518644/63408834-79a06e00-c422-11e9-9573-334cb1d3a4f3.png)

**Comment by xyzxzj** [comment]
Hi,
I use freesurfer to do the preprocessing:
recon-all  -i sub-A00000159/mprage.nii.gz  -subjid sub-A00000159 -autorecon1
recon-all  -subjid sub-A00000159 -autorecon2
then I extract norm.mgz and aseg.mgz and follow your preprocess steps describe in your paper.
1-intensity normalize to [0-1] for norm.mgz
2-crop for norm.mgz and aseg.mgz
3-affine transformation using FSL flirt for norm.mgz and aseg.mgz
note: I didn't do intensity normalize for aseg.mgz

and I can convert the aseg.mgz to aseg.nii.gz ,and the aseg.nii.gz is shows as follows:
![image](https://user-images.githubusercontent.com/43518644/63409469-d6e8ef00-c423-11e9-98f6-2827c4c2f0c3.png)
and the labels in the aseg.nii.gz is shows as follows:
![image](https://user-images.githubusercontent.com/43518644/63409554-fda72580-c423-11e9-85c3-ac047509b5fd.png)
Meantime,I also print the labels in the atlas_seg,
![image](https://user-images.githubusercontent.com/43518644/63409657-2deec400-c424-11e9-815c-3648ff92b553.png)
and the atlas_seg.nii.gz shows as follows:
![image](https://user-images.githubusercontent.com/43518644/63409712-4b239280-c424-11e9-9a92-0d863d0ff6e5.png)
the labels in label.mat are all on the labels in aseg.nii.gz and atlas_seg.nii.gz
But it is obvious that the areas of the same label of the aseg.nii.gz and atlas_seg.nii.gz 
are just on the opposite sides.
But the aseg.mgz was anatomically segmented with FreeSurfer,So I have no idea about the problem of labels in the two image .



I just use the following cmd to register my norm.nii.gz,it performs well.
python3 register.py ../data/norml.nii.gz ../data/atlas_norm.nii.gz --out_img ../data/out.nii.gz --model_file ../models/cvpr2018_vm2_cc.h5
When I want to use the aseg.npz to test the dice,I found that the aseg.nii.gz was different from the atlas_seg.nii.gz which you supply.the segmentation parts of aseg.nii.gz was different from the atlas_seg.nii.gz.but the aseg.nii.gz was generated from freesurfer recon-all .

**Comment by adalca** [comment]
> Hi:
> I use the
> python3 test.py ../models/cvpr2018_vm2_cc.h5 0
> to test test_seg.npz ,the dice result is :
> ![image](https://user-images.githubusercontent.com/43518644/63408834-79a06e00-c422-11e9-9573-334cb1d3a4f3.png)

So the Dice result with our image looks good, which probably means that the `aseg` computed from your pipline is somehow different.

> But it is obvious that the areas of the same label of the aseg.nii.gz and atlas_seg.nii.gz
are just on the opposite sides.

If this is the case, it sounds like there could be a flip going on -- I'm not sure why this is happened, but could you try flipping the image and segmentations, registering, and see how it goes?

**Comment by xyzxzj** [comment]
Hi:
  I am so sorry to bother you again. I still don't understand why my aseg.nii.gz is  different from atlas_seg.nii.gz what you provided. The follows is the aseg.nii.gz generated from freesurfer:
![image](https://user-images.githubusercontent.com/43518644/63495371-4b8a5f00-c4f2-11e9-9550-d252f9605411.png)

Is the preprocessing steps correct? and I use the mri_convert to convert the aseg.mgz to NIFTI,the aseg.nii.gz is as follows:
![image](https://user-images.githubusercontent.com/43518644/63495713-f4d15500-c4f2-11e9-9c4c-dc1a8a764229.png)
then I perform the crop,affine transformation on the aseg.nii.gz, the preprocessed aseg.nii.gz is as follows:
![image](https://user-images.githubusercontent.com/43518644/63495821-2d712e80-c4f3-11e9-9554-3235439d7506.png)
 I extracted the atlas_seg.nii.gz from the atlas_norm.npz,then the atlas_seg.nii.gz is as follows:
![image](https://user-images.githubusercontent.com/43518644/63496014-a6708600-c4f3-11e9-8e89-027ca8731efb.png)

Could you tell me how do you get the test_seg.nii.gz, because the the positions of labels in test_seg.nii.gz  are the same with the atlas_seg.nii.gz. I don't know which step went wrong.

**Comment by adalca** [comment]
I don't know which step went wrong either, perhaps slightly different ways or versions of FreeSurfer. 
I would recommend you try the following:

1. Perhaps this is related to @hassaanmahmood's problem in #44, and perhaps the two of you can communicate. 
2. try flipping and rotating (see numpy flip and transpose functions) to get to the right orientation. This might be an issue with headers.
3. You could alternatively build your own atlas from the current dataset using our new tool: https://github.com/voxelmorph/voxelmorph/blob/master/src/train_img_template.py . This will basically train a voxelmorph as well as lean an atlas at the same time. Here's the paper: https://arxiv.org/abs/1908.02738

It seems like in this case voxelmorph is actually doing well (via `register.py`) and this is just an issue with the labels/orientation. Unfortunately we're not able to help at this level of detail as we're preparing for the next big release in a few weeks. I encourage you to explore the ideas above.

**Comment by xyzxzj** [comment]
Hi:
 I found a problem, The follows is the 
origin_moving_img| fixed_img | affine_moving_img| moved_img
origin_moving_seg | fixed_seg | affine_moving_seg| moved_seg
![image](https://user-images.githubusercontent.com/43518644/63633999-6dffb200-c683-11e9-996b-a188b37f6d56.png)
I found that the the labels in origin_seg is similiar to atlas_seg, so I tried to use the origin_seg to test the dice,the result is follows:
![image](https://user-images.githubusercontent.com/43518644/63634063-efefdb00-c683-11e9-8bb8-a3d8caf9b0cf.png)
I use the Ants to do the affine transform
![image](https://user-images.githubusercontent.com/43518644/63634160-3560d800-c685-11e9-94ac-811d99429c0b.png)
but the transform img is different from the origin_moving_seg. It looks like the transform img has been reversed，I don't know why the affine_seg becomes like this after affine transformation.
