### ISSUE TITLE
License

### ISSUE THREAD

**Issue by stity** [voxelmorph/voxelmorph#8]
You didn't choose a license for this repository.

> Code without an explicit license is protected by copyright and is by default All Rights Reserved. 

If you want other people to use your code, you can choose a license : 
https://blog.github.com/2013-07-15-choosing-an-open-source-license/

Thank you for your work

**Comment by adalca** [comment]
Thank you for pointing this out! We will select a license (probably MIT) when we update the code with a variety of improvements soon.
