### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by qiheihelan** [voxelmorph/voxelmorph#80]
@adalca 
Hello 
 I  run test.py . But found error: File"test.py",line83,in test(sys.argv[1], sys.argv[2]) list index out of range. Can you give me some advice?
Thanks.

**Comment by qiheihelan** [comment]
@adalca 
Another question：test_brain_file = open('...path/here//test_examples.txt')  
 What does this statement mean?
Looking forward to your reply.

**Comment by adalca** [comment]
Related to `test.py`:
how did you call it, with what parameters? Also, what are you trying to do?

to use our test.py please see how to construct a [`test_examples.txt` file here](https://github.com/voxelmorph/voxelmorph/issues/48#issuecomment-497709534)

I think it's important if you tell me what you are trying to do. `test.py` tests registrations using external segmentation data. Most users don't have these data, and instead are probably looking for `register.py`.

**Comment by qiheihelan** [comment]
@adalca
hello
I wanted to train my own model（miacci2018）, using CT images of the lungs. The image has no additional segmentation data. The image size is 282×208×224. I've learned that images need affine changes and normalization. I don't know how to modify the program next, where to modify, and how to import the data.
I run test.py to see if the environment is configured correctly. I didn't make any changes or input to test.py. But found error: File"test.py",line83,in test(sys.argv[1], sys.argv[2]) list index out of range.
Thank you very much for your reply. I just started to learn python, but my friends and teachers gave me few instructions, so it was quite difficult. So some simple questions I do not understand, I hope it didn't cause you trouble. Thanks again for your reply.

**Comment by adalca** [comment]
You would want to use `train.py` or `train_miccai2018.py` if you'd like to train on your own images.
Then you would want to use `register.py` to use the trained model.

The `test.py` is really for testing *when you have segmentation data*. If you don't, I don't think you should use it.

**Comment by qiheihelan** [comment]
@adalca

 Thank you very much. I should have made a mistake before. I'll try again.
