### ISSUE TITLE
About shift_center flag

### ISSUE THREAD

**Issue by lalithnag** [voxelmorph/voxelmorph#83]
Hi! In the spatial transformer layer implementation, you call the function affine_to_shift as follows:

```
   def _single_aff_to_shift(self, trf, volshape):
        if len(trf.shape) == 1:  # go from vector to matrix
            trf = tf.reshape(trf, [self.ndims, self.ndims + 1])

        # note this is unnecessarily extra graph since at every batch entry we have a tf.eye graph
        trf += tf.eye(self.ndims+1)[:self.ndims,:]  # add identity, hence affine is a shift from identity
        return affine_to_shift(trf, volshape, shift_center=True)
```

And in the function definition, the following happens:
```
    if shift_center:
        mesh = [mesh[f] - (volshape[f]-1)/2 for f in range(len(volshape))]
```

I wasn't able to understand why you were doing this and in what cases to toggle the flag. It would be great if you can throw some light on it. Thanks in advance!

**Comment by adalca** [comment]
This is for essentially applying the affine transform, which can be applied with different conventions. For example, if you are rotating the image, should you rotate around the top left corner of the image, or around the center?. Here, we shift the mesh to make sure everything is done with respect to the center.
