### ISSUE TITLE
The tensorflow code that warps points with a given flow

### ISSUE THREAD

**Issue by white-hy** [voxelmorph/voxelmorph#84]
Hi @adalca,Thanks for your wonderful work and  code! It help me a lot.
I want to calculate the TRE of the landmarks of two images and I am using the code you provided.
```
def point_spatial_transformer(surface_points, trf, single=False):
    """
    surface_points is a N x D or a N x (D+1) Tensor
    trf is a *volshape x D Tensor
    """

    surface_pts_D = surface_points.get_shape().as_list()[-1]
    trf_D = trf.get_shape().as_list()[-1]
    assert surface_pts_D in [trf_D, trf_D + 1]

    if surface_pts_D == trf_D + 1:
        li_surface_pts = K.expand_dims(surface_points[..., -1], -1)
        surface_points = surface_points[..., :-1]

    # just need to interpolate.
    # at each location determined by surface point, figure out the trf...
    # Note: if surface_points are on the grid, gather_nd should work as well
    fn = lambda x: nrn_utils.interpn(x[0], x[1])
    diff = tf.map_fn(fn, [trf, surface_points], dtype=tf.float32)
    ret = surface_points + diff

    if surface_pts_D == trf_D + 1:
        ret = tf.concat((ret, li_surface_pts), -1)

    return ret
```
My code is as follows：
```
moving_image_landmarks = np.loadtxt('./landmarksmoving_image_landmarks.txt')
fixed_image_landmarks = np.loadtxt( './landamrks/fixed_image_landmarks.txt')
dvf_Data = nib.load(./dvf/displacement.nii.gz)
...
...
...
moved_image_landmarks = point_spatial_transformer(moving_image_landmarks, dvf_Data).
difference = moved_image_landmarks - fixed_image_landmarks
# Landmarks include 300 points
for i in range(0,300,1):
        sum_difference += np.linalg.norm(difference[i])
# TRE
print(sum_difference/300)
```
I used the code to get a result that is similar to not applying displacement.So I think I might have made some mistakes.Am I doing it right in these places?
![image](https://user-images.githubusercontent.com/33248778/62719562-d707e880-ba3a-11e9-9482-0e93711eeb29.png)

**Comment by adalca** [comment]
Hi @white-hy 

When warping image `moving` to image `fixed`, the deformation field is in the space of the `fixed` image -- it tells you how to move the moving image to get to each grid location in the fixed image. For example, to get to location (123, 143) into the fixed space, it might tell you to grab (2.2, 1.3) voxels from the `moving image`. The reason this is a bit "backwards" is because moving pixels in this way enables us to *interpolate from the moving image* -- that is, we can get the "intensity value" at location (125.2, 144.3) from the moving image by bilinear interpolation, and move it to (123, 143).

But since this warp field is int he *fixed* space, warping *points* is a different story. If you have an exact point you want to move (e.g. at location (73.3, 54.1)), then this warp field only tells you how to move it from *fixed* to *moving* (since that's how it's set up. So, the `point_spatial_transformer` should be given the `fixed_image_landmarks`, not the moving image landmarks.

**Comment by white-hy** [comment]
@adalca Thank you very much for answer. I will do what you said right away.

**Comment by zoujinger** [comment]
@white-hy 
Hello, sorry to bother you.
May I ask how do you generate dvf_data(nifti format) from h5 file?
Thanks!

**Comment by white-hy** [comment]
@zoujinger Hi!
If you use voxelmorph to register two images, you will get a deformation field in nifity format.

**Comment by zoujinger** [comment]
@white-hy 
Hello, I use your code to calculate the tre, but there is an error I don't know how to fix.
Would you please help me?
The dvf_data is generated from register.py.

Traceback (most recent call last):
  File "/Users/jinger/Documents/DL_registration/voxelmorph/src/tre_calculate.py", line 55, in <module>
    moved_image_landmarks = point_spatial_transformer(fixed_image_landmarks, dvf_Data)
  File "/Users/jinger/Documents/DL_registration/voxelmorph/src/tre_calculate.py", line 26, in point_spatial_transformer
    surface_pts_D = surface_points.get_shape().as_list()[-1]
AttributeError: 'numpy.ndarray' object has no attribute 'get_shape'

**Comment by zoujinger** [comment]
@white-hy I solved the problem by changing first two lines like that:
   
<img width="354" alt="image" src="https://user-images.githubusercontent.com/27009979/67267617-40997e00-f4e5-11e9-9294-cfd018a22884.png">


but there is another error I don't know to fix?
![image](https://user-images.githubusercontent.com/27009979/67267551-1d6ece80-f4e5-11e9-9c01-d132da370442.png)

Looking forward to your reply. thanks!

**Comment by white-hy** [comment]
@zoujinger I am sorry for my late reply.  Maybe this is because the dimensions of the data are inconsistent. I can give you my code that I use to calculate TRE. 

```
moving_image_landmarks = np.loadtxt('./landmarksmoving_image_landmarks.txt')
fixed_image_landmarks = np.loadtxt( './landamrks/fixed_image_landmarks.txt')
dvf_Data = nib.load('./dvf/displacement.nii.gz')

fixed_image_landmarks = fixed_image_landmarks [np.newaxis, ...]
fixed_image_landmarks = tf.Variable(fixed_image_landmarks )

dvf_Data = dvf_Data[np.newaxis, ...]
dvf_Data = tf.Variable(dvf_Data)

# obtain moved_image_landmarks
moved_image_landmarks = point_spatial_transformer(fixed_image_landmarks , dvf_Data)
# moved_image_landmarks convert into ndarray
os.environ["CUDA_VISIBLE_DEVICES"] = '0'
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)
moved_image_landmarks = moved_image_landmarks .eval(session=sess)
moved_image_landmarks = np.squeeze(moved_image_landmarks )

difference = moved_image_landmarks - moving_image_landmarks 
# Landmarks include 300 points
for i in range(0,300,1):
        sum_difference += np.linalg.norm(difference[i])
# TRE
print(sum_difference/300)
```
Note that I used the `point_spatial_transformer `provided by  @adalca ，and You can find it up there. Also note that `moving_image_landmarks`, `fixed_image_landmarks`, and `dvf_Data` are all defined in the world coordinate system.

**Comment by zoujinger** [comment]
Thanks so much for your help!

**Comment by white-hy** [comment]
@zoujinger You're welcome

**Comment by zoujinger** [comment]
@white-hy Hello, May I ask another question?
I know that the landmarks can be transformed into world coordinate system by sitk.TransformIndexToPhysicalPoint(). But how to understand dvf_Data in world coordinate system?
