### ISSUE TITLE
2D/3D registration

### ISSUE THREAD

**Issue by alenauus** [voxelmorph/voxelmorph#85]
Sorry, it might be a not entirely relevant question - but how difficult it will be to modify (or whether it will be feasible at all) this architecture for 3D-to-2D registration? 
Monomodal / the same subject / motion correction of deformable organs. 

Thank you,
Alena

**Comment by adalca** [comment]
@alenauus 
do you mean non-rigid or affine (i'm asking since it would be the same subject)?
My intuition is that this is quite possible, honestly. If you give us more specifics we could try to give more specific hints.

**Comment by alenauus** [comment]
Thank you for your reply. 

We are are planning to use CNN for deformable registration of volume to slices (to account for out-of-plane motion) for fetal body MRI motion correction ( similarly to https://arxiv.org/pdf/1906.08827.pdf pipeline).

Conventional registration methods produce sufficiently accurate results - but we need to make the pipeline faster / more robust. 

Thanks,
Alena
