### ISSUE TITLE
I applied voxelmorph on the lung image

### ISSUE THREAD

**Issue by white-hy** [voxelmorph/voxelmorph#86]
Hi @adalca,Thanks for your wonderful work and code! I'm applying voxelmorph to lung imaging.I have achieved a visually good result.Here is the result I got.
![image](https://user-images.githubusercontent.com/33248778/63146483-abce5c00-c02d-11e9-8461-db1164cd5ad7.png)
This result looks good, but when I want to use the TRE evaluation of landmarks, I found that the TRE of the landmarks after registration is no less than the TRE before registration.
I am very confused now, can you give me some tips?

**Comment by adalca** [comment]
can you share with us how you computed TRE, and visualize the warp field?

**Comment by white-hy** [comment]
Here is how I calculate TRE：
```
moving_image_landmarks = np.loadtxt('./landmarksmoving_image_landmarks.txt')
fixed_image_landmarks = np.loadtxt( './landamrks/fixed_image_landmarks.txt')
dvf_Data = nib.load(./dvf/displacement.nii.gz)

dvf_Data = dvf_Data[np.newaxis, ...]
dvf_Data = tf.Variable(dvf_Data)

# get moved_landmarks
moved_image_landmarks = point_spatial_transformer(fixed_image_landmarks, dvf_Data).

os.environ["CUDA_VISIBLE_DEVICES"] = '5'
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)
landmarks_moved = landmarks_moved.eval(session=sess)

# the difference between moved_landmarks and moving_lanmarks
landmarks_moved = np.squeeze(landmarks_moved)
difference = moved_image_landmarks - fixed_image_landmarks

# Landmarks include 300 points
for i in range(0,300,1):
        sum_difference += np.linalg.norm(difference[i])
# TRE
print(sum_difference/300)
```
Here is the warp field.In turn, x direction, y direction, z direction：
![image](https://user-images.githubusercontent.com/33248778/63196224-5c2c7680-c0a7-11e9-9105-3afd7e1015aa.png)
![image](https://user-images.githubusercontent.com/33248778/63196245-69e1fc00-c0a7-11e9-9e99-c05d202085c6.png)
![image](https://user-images.githubusercontent.com/33248778/63196280-7b2b0880-c0a7-11e9-975e-ab7eba296fee.png)

**Comment by adalca** [comment]
interesting, this field seems a bit forced to me but not too bad. Can you tell me the TRE before and after?

**Comment by white-hy** [comment]
Hi @adalca 
The TRE before applying the warp field is `3.8924`, and after applying the warp field is `3.9865`.
I used the Case1Pack of the public dataset Dir-lab 4DCT to calculate the TRE. If necessary, I can send you my scans, landmarks and warp fields.

**Comment by adalca** [comment]
Hm, I'm really unsure to be honest. 3.89 does seem a bit too good at the beginning, but I don't know enough about lungs. 

Is this behaviour consistent on other lungs as well?

Have you tried your implementation on some other dataset (perhaps a toy dataset? like one with simulations with disks or something, just as a sanity check that your code is doing what you want)

**Comment by kangmiao15** [comment]
Hi @white-hy 
Do you solve this problem? I also got a larger TRE after applying the warp field on  Dir-lab 4DCT with the code you mentioned above.

**Comment by adalca** [comment]
@kangmiao15  can you share the code you are using?

**Comment by kangmiao15** [comment]
Hi @adalca 
Thanks for your reply. I use  a different networks to predict an dense dvf_Data. Then I use following code to calculate the TRE.  

moving_image_landmarks = np.loadtxt('./landmarksmoving_image_landmarks.txt')
fixed_image_landmarks = np.loadtxt( './landamrks/fixed_image_landmarks.txt')
dvf_Data = nib.load(./dvf/displacement.nii.gz)

dvf_Data = dvf_Data[np.newaxis, ...]
dvf_Data = tf.Variable(dvf_Data)

# get moved_landmarks
moved_image_landmarks = point_spatial_transformer(fixed_image_landmarks, dvf_Data).

os.environ["CUDA_VISIBLE_DEVICES"] = '5'
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)
moved_image_landmarks = moved_image_landmarks.eval(session=sess)

# the difference between moved_landmarks and moving_lanmarks
moved_image_landmarks = np.squeeze(moved_image_landmarks)
difference = moved_image_landmarks - moving_image_landmarks

# Landmarks include 300 points
for i in range(0,300,1):
        sum_difference += np.linalg.norm(difference[i])
# TRE
print(sum_difference/300)

After applying the warp field,  the calculated of TRE(4.167) is larger than  the initial TRE (3.908).
ps: the dvf_Data is scaled with the size of volume, which means the absolute  shift of a grid.

**Comment by adalca** [comment]
@kangmiao15 

Are you sure that when you computed the dvf, it moved "moving" to "fixed"? Can you show the images  (moving, fixed, moved) ? Remember, the dvf warps moving images to fixed, but fixed *points* to moving space. It's a bit counterintuitive.

**Comment by kangmiao15** [comment]
Hi @adalca,
Yes, I do pay attention to the difference of points and images warping. The attached link is the warp results with dvf. From left to right is  moving, fixed and  moved image. I also visualize the landmarks and moved landmarks on images with red dot. The moved image and fixed images matched very well but the landmarks is disorder.   
(https://user-images.githubusercontent.com/27987763/103493300-76691f00-4e6b-11eb-8e6d-f28d7c5409a7.jpg)

**Comment by adalca** [comment]
@kangmiao15 It may also be a visualization issue. Can you take a look at the annotation tutorial here: https://colab.research.google.com/drive/1V0CutSIfmtgDJg1XIkEnGteJuw0u7qT-

This should make it clear how to use the voxelmorph tools to warp both images and annotations.

**Comment by computerAItest** [comment]
> Hi @adalca,Thanks for your wonderful work and code! I'm applying voxelmorph to lung imaging.I have achieved a visually good result.Here is the result I got.

May I ask where did you find the mask file of this 4DCT lung dataset? I don’t think it is officially provided. Can you provide a preprocessed dataset? I would be very grateful

**Comment by computerAItest** [comment]
> Hi @adalca The TRE before applying the warp field is `3.8924`, and after applying the warp field is `3.9865`. I used the Case1Pack of the public dataset Dir-lab 4DCT to calculate the TRE. If necessary, I can send you my scans, landmarks and warp fields.
Hello, can you provide the preprocessing data script file on the dirlab 4dct dataset, I would be very grateful

**Comment by computerAItest** [comment]
> point_spatial_transformer

请问下这个函数point_spatial_transformer，您能分享下代码吗，我将不胜感激

**Comment by adalca** [comment]
@yuanpengpeng https://github.com/voxelmorph/voxelmorph/blob/08d433cc6077977bd1a0b1eff0d012c65857d31a/voxelmorph/tf/utils/utils.py#L445

**Comment by computerAItest** [comment]
> 3.8924

May I ask why the deformation field dvf is not seen in this function?

**Comment by adalca** [comment]
Sorry, this wasn't one of our main functions and its poorly documented. 

`x` should include both the image and field, as you can see in the first line:

```    
# surface_points is a N x D or a N x (D+1) Tensor  
# trf is a *volshape x D Tensor  
surface_points, trf = x
```
