### ISSUE TITLE
Multi GPU version of Voxelmorph

### ISSUE THREAD

**Issue by nazib** [voxelmorph/voxelmorph#9]
Hi
In your paper you have mentioned that multiple gpu's were used during training. I can run single gpu version simply, but can't make it working for multiple gpus. Could you please give any direction to run thi network with multiple gpus?
What I tried currently is as follows: (networks.py file) 
with tf.device('/gpu:0'):
        src = Input(shape=vol_size + (1,))
        tgt = Input(shape=vol_size + (1,))

        x_in = concatenate([src, tgt])
        x0 = myConv(x_in, enc_nf[0], 2)  # 80x96x112
        x1 = myConv(x0, enc_nf[1], 2)  # 40x48x56
        x2 = myConv(x1, enc_nf[2], 2)  # 20x24x28
        x3 = myConv(x2, enc_nf[3], 2)  # 10x12x14

        x = myConv(x3, dec_nf[0])
        x = UpSampling3D()(x)
        x = concatenate([x, x2])
        x = myConv(x, dec_nf[1])
        x = UpSampling3D()(x)
        x = concatenate([x, x1])
        x = myConv(x, dec_nf[2])
        x = UpSampling3D()(x)
        x = concatenate([x, x0])
        x = myConv(x, dec_nf[3])
        x = myConv(x, dec_nf[4])

    with tf.device('/gpu:1'):
        x = UpSampling3D()(x)
        x = concatenate([x, x_in])
        x = myConv(x, dec_nf[5])
        if(len(dec_nf) == 8):
            x = myConv(x, dec_nf[6])
        flow = Conv3D(dec_nf[-1], kernel_size=3, padding='same',
                    kernel_initializer=RandomNormal(mean=0.0, stddev=1e-5), name='flow')(x)
        
        y = Dense3DSpatialTransformer()([src, flow])

**Comment by adalca** [comment]
I believe that we always used a single GPU 
(where did we say in the paper that we used multi-gpu?)

Either way, I think the simplest way to use multi gpus is to use keras' direct support: https://keras.io/utils/#multi_gpu_model . Specifically, define the model in networks.py, then run `multi_gpu_model` to create a parallel model, then finally fit that model. Although not for voxelmorph, I've done this for other projects and it works well.

**Comment by nazib** [comment]
thanks

**Comment by meggiezhou** [comment]
Hi sir , I want to run the train.py with multi-gpu , but the commend line  ''assert np.mod(batch_size, nb_gpus) == 0, \
        'batch_size should be a multiple of the nr. of gpus. ' + \
        'Got batch_size %d, %d gpus' % (batch_size, nb_gpus)'' get wrong with output
loading /data/zhoumeiqi/voxelmorph-master/models/cvpr2018_vm2_l2.h5
Traceback (most recent call last):
  File "/data/zhoumeiqi/voxelmorph-master/src/train.py", line 189, in <module>
    train(**vars(args))
  File "/data/zhoumeiqi/voxelmorph-master/src/train.py", line 115, in train
    'Got batch_size %d, %d gpus' % (batch_size, nb_gpus)
AssertionError: batch_size should be a multiple of the nr. of gpus. Got batch_size 1, 2 gpus
could you tell me how to solve the problem?
thank you
