### ISSUE TITLE
How to obtain invert displacement field?

### ISSUE THREAD

**Issue by John1231983** [voxelmorph/voxelmorph#90]
Hello, I used ANTs and it provided both displacement and invert displacement field, in which the invert displacement field is used to warp back the moved image to moving image

Do you have any idea to obtain the inv_grid, given the moved and displacement field?

**Comment by adalca** [comment]
- If you use the CVPR method, it's not trivial to do this. You essentially have to use [griddate](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.griddata.html) to do some non-gridded interpolation. As a template, you can see the 'forward' implementation of this general invertability function in MATLAB [here](https://github.com/adalca/matlib/blob/master/matlib/visual/volwarp.m#L78)

- The better direction is to simply use our MICCAI method, where we actually have an option to return the inverse. Or equally simple (if you'd rather not use the MICCAI version) you can use the CVPR method, but append a `VecInt` integration layer at the end of the UNet (that layer is available in our neuron library) which is quite easy to do, and re-train the network. If you do this, inverting is trivial -- basically the quantity before the integration is called a SVF (stationary velicity field), and
while the normal field is optained via `phi = integra(SVF)`, the inverse is simply `phi_inverse = integral(-SVF)` . See the MICCAI implementation (search for `bidir` flag) for an example of how easy this is to do. See section 2.4 of our [MedIA paper](https://arxiv.org/pdf/1903.03545.pdf) for quick explanation, and citations to more papers on this.
