### ISSUE TITLE
Paper Implementation

### ISSUE THREAD

**Issue by yohset95** [voxelmorph/voxelmorph#91]
I read your paper with title "Unsupervised deep learning for Bayesian brain MRI segmentation" in arXiv. I want to try the implementation, but I confused where it has been implemented in this github? In "train.py" or "trainMiccai.py"? Thanks for your attention.

**Comment by adalca** [comment]
Hi @yohset95 ,

The unsupervised segmentation code is currently in the `unified_seg` folder, where it has its own readme.md with instructions!

**Comment by yohset95** [comment]
Hi @adalca 
Thanks for your reply.
I have problem when I run the test_unsupervised_segmentation code in the Google Colaboratory.
The problem is the notification "Can't found 'load_data;"
I don't understand what it is since I just input my ".nii" data to test my own dataset.

And, in train_unsupervised_segmentation , what is the use of "data_dir"?

Thank you very much.

**Comment by yohset95** [comment]
One question again:
I want to implement your code to segment the subcortical structures in MRI image (such as thalamus, globus pallidus, etc). Where do I find the atlas for it? Is there any free download atlas ready to use, or I've to make the atlas by expert?

Thank you very much, sorry if I've too much question.

**Comment by adalca** [comment]
@yohset95 
 - Can you give more details about the `load_data` error? The function is in the same file.
 - `data_dir` is the path of the folder where your training data is
 - we provide a default 41-class atlas in [data/prob_atlas_41_class.npz] that might be helpful

**Comment by yohset95** [comment]
@adalca 
Thanks for your help, I've found problem of the load_data. It's because I forget to add the path of the folder.

Now I want to ask: what the difference between prob_atlas_41_class.npz with the atlas_norm.nii ? Are they same atlas? Thanks.

**Comment by adalca** [comment]
ah, no, they are not the same atlas!

**Comment by yohset95** [comment]
@adalca

Alright. Thank you for your reply.
And, why all MRI scans were preprocessed with FreeSurfer?
How if I input MRI scans without preprocessed?
Thank you very much.

**Comment by John1231983** [comment]
@yohset95 : In brain MRI, the FreeSurfer is most power and famous pipeline

**Comment by adalca** [comment]
@yohset95 

We had these data processed and this allowed us to test the core of the algorithm. Going forward, we're testing the ability of our algorithm to work with less and less processing. If you don't have processed data you can still try the algorithm -- but the one thing that I think is absolutely necessary is **some** rigid/affine registration to the atlas.
