### ISSUE TITLE
Question about train on custom dataset and fixed image

### ISSUE THREAD

**Issue by John1231983** [voxelmorph/voxelmorph#93]
I think this is great work and I will give you one vote for best paper award in miccai if I have :).

In this question, I want to talk about the application of your method. Given a fixed (atlas image) and a moving image. In the training, we try to find a displacement field between the moving and the atlas image. Then the testing, we apply the trained displacement field to the new moving image. This step likes register a moving to the atlas image.

In real application, we have to regisger image of a subject to other subject. So, we cannot apply your method in this case but ants or flirt still work well. The reason is that your trained displacement filed is trained with paired of moving and atlas. And in my case, the fixed subject is not your atlas. Am I right?

If I am right, so your method may limited application. For example, we have t1 and t2 that capture from same subject. We have to register t2 to t1 to make them are alignment for segmentation. So, the moving is t2 and fixed is t1, not atlas. Do you think your idea still work for that case? For example, I have 10 subjects with t1 and t2 for training, and 5 subject with t1 and t2 for validation. After training 10 subjects, Can we make a displacement field that can register for 5 subjects. 

Sorry if I ask so many question

**Comment by John1231983** [comment]
Hi. I have run your source code with both ncc and mse. 

The log is for ncc with your pretrained model and the result looks fine
```
Epoch 1/100
2019-08-28 17:44:03.000256: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
20/20 [==============================] - 55s 3s/step - loss: -0.1844 - spatial_transformer_1_loss: -0.2145 - flow_loss: 0.0300
Epoch 2/100
20/20 [==============================] - 31s 2s/step - loss: -0.1941 - spatial_transformer_1_loss: -0.2219 - flow_loss: 0.0278
Epoch 3/100
20/20 [==============================] - 31s 2s/step - loss: -0.1880 - spatial_transformer_1_loss: -0.2201 - flow_loss: 0.0322
Epoch 4/100
20/20 [==============================] - 31s 2s/step - loss: -0.1949 - spatial_transformer_1_loss: -0.2234 - flow_loss: 0.0285
Epoch 5/100
20/20 [==============================] - 31s 2s/step - loss: -0.1927 - spatial_transformer_1_loss: -0.2216 - flow_loss: 0.0289
Epoch 6/100
20/20 [==============================] - 31s 2s/step - loss: -0.1981 - spatial_transformer_1_loss: -0.2263 - flow_loss: 0.0282
Epoch 7/100
20/20 [==============================] - 31s 2s/step - loss: -0.1944 - spatial_transformer_1_loss: -0.2235 - flow_loss: 0.0290
Epoch 8/100
20/20 [==============================] - 31s 2s/step - loss: -0.1988 - spatial_transformer_1_loss: -0.2239 - flow_loss: 0.0251
Epoch 9/100
20/20 [==============================] - 31s 2s/step - loss: -0.1978 - spatial_transformer_1_loss: -0.2256 - flow_loss: 0.0278
Epoch 10/100
20/20 [==============================] - 31s 2s/step - loss: -0.1980 - spatial_transformer_1_loss: -0.2272 - flow_loss: 0.0292
Epoch 11/100
20/20 [==============================] - 31s 2s/step - loss: -0.1907 - spatial_transformer_1_loss: -0.2197 - flow_loss: 0.0289
Epoch 12/100
20/20 [==============================] - 31s 2s/step - loss: -0.1919 - spatial_transformer_1_loss: -0.2211 - flow_loss: 0.0292
Epoch 13/100
20/20 [==============================] - 32s 2s/step - loss: -0.1920 - spatial_transformer_1_loss: -0.2214 - flow_loss: 0.0294
Epoch 14/100
20/20 [==============================] - 32s 2s/step - loss: -0.1958 - spatial_transformer_1_loss: -0.2244 - flow_loss: 0.0286
Epoch 15/100
20/20 [==============================] - 32s 2s/step - loss: -0.2037 - spatial_transformer_1_loss: -0.2314 - flow_loss: 0.0277
Epoch 16/100
20/20 [==============================] - 32s 2s/step - loss: -0.2184 - spatial_transformer_1_loss: -0.2401 - flow_loss: 0.0216
Epoch 17/100
20/20 [==============================] - 32s 2s/step - loss: -0.1982 - spatial_transformer_1_loss: -0.2254 - flow_loss: 0.0272
Epoch 18/100
20/20 [==============================] - 32s 2s/step - loss: -0.2041 - spatial_transformer_1_loss: -0.2298 - flow_loss: 0.0257
Epoch 19/100
20/20 [==============================] - 32s 2s/step - loss: -0.2046 - spatial_transformer_1_loss: -0.2297 - flow_loss: 0.0251
Epoch 20/100
20/20 [==============================] - 32s 2s/step - loss: -0.1986 - spatial_transformer_1_loss: -0.2259 - flow_loss: 0.0274
```

However, if I ran **without pretrained model**, I have log for ncc
```
20/20 [==============================] - 55s 3s/step - loss: -0.0841 - spatial_transformer_1_loss: -0.0841 - flow_loss: 3.9684e-06
Epoch 2/100
20/20 [==============================] - 30s 2s/step - loss: -0.0682 - spatial_transformer_1_loss: -0.0682 - flow_loss: 2.5551e-05
Epoch 3/100
20/20 [==============================] - 31s 2s/step - loss: -0.0616 - spatial_transformer_1_loss: -0.0616 - flow_loss: 3.9303e-06
Epoch 4/100
20/20 [==============================] - 30s 2s/step - loss: -0.0733 - spatial_transformer_1_loss: -0.0734 - flow_loss: 1.1691e-05
Epoch 5/100
20/20 [==============================] - 30s 2s/step - loss: -0.0611 - spatial_transformer_1_loss: -0.0611 - flow_loss: 2.1747e-05
Epoch 6/100
20/20 [==============================] - 30s 2s/step - loss: -0.0721 - spatial_transformer_1_loss: -0.0721 - flow_loss: 9.2168e-06
Epoch 7/100
20/20 [==============================] - 30s 2s/step - loss: -0.0704 - spatial_transformer_1_loss: -0.0704 - flow_loss: 1.1032e-05
Epoch 8/100
20/20 [==============================] - 30s 2s/step - loss: -0.0610 - spatial_transformer_1_loss: -0.0610 - flow_loss: 3.3247e-05
Epoch 9/100
20/20 [==============================] - 30s 2s/step - loss: -0.0737 - spatial_transformer_1_loss: -0.0737 - flow_loss: 1.9089e-05
Epoch 10/100
20/20 [==============================] - 30s 2s/step - loss: -0.0747 - spatial_transformer_1_loss: -0.0747 - flow_loss: 6.2951e-06
Epoch 11/100
20/20 [==============================] - 31s 2s/step - loss: -0.0621 - spatial_transformer_1_loss: -0.0621 - flow_loss: 2.3794e-05
Epoch 12/100
20/20 [==============================] - 31s 2s/step - loss: -0.0643 - spatial_transformer_1_loss: -0.0643 - flow_loss: 1.2787e-05
Epoch 13/100
20/20 [==============================] - 31s 2s/step - loss: -0.0518 - spatial_transformer_1_loss: -0.0519 - flow_loss: 6.8648e-05
Epoch 14/100
20/20 [==============================] - 31s 2s/step - loss: -0.0834 - spatial_transformer_1_loss: -0.0835 - flow_loss: 5.8977e-05
Epoch 15/100
20/20 [==============================] - 31s 2s/step - loss: -0.0875 - spatial_transformer_1_loss: -0.0875 - flow_loss: 7.0170e-05
Epoch 16/100
20/20 [==============================] - 31s 2s/step - loss: -0.0665 - spatial_transformer_1_loss: -0.0667 - flow_loss: 1.9280e-04
Epoch 17/100
20/20 [==============================] - 32s 2s/step - loss: -0.0773 - spatial_transformer_1_loss: -0.0777 - flow_loss: 3.8204e-04
Epoch 18/100
20/20 [==============================] - 31s 2s/step - loss: -0.0534 - spatial_transformer_1_loss: -0.0541 - flow_loss: 7.4703e-04
Epoch 19/100
20/20 [==============================] - 32s 2s/step - loss: -0.0766 - spatial_transformer_1_loss: -0.0772 - flow_loss: 5.9872e-04
Epoch 20/100
20/20 [==============================] - 31s 2s/step - loss: -0.0741 - spatial_transformer_1_loss: -0.0749 - flow_loss: 8.3166e-04
Epoch 21/100
 2/20 [==>...........................] - ETA: 27s - loss: -0.0574 - spatial_transformer_1_loss: -0.0576 - flow_loss: 2.5056e-04
```

Then your output is similar my reproduce. It means the moved image is so far from fixed image. It looks not change so much. [Moving-fixed-moved by mse, moved by ncc]. Do you think I need to increase learning rate from 1e-4 to 1e-3 for training from scratch?

![step7](https://user-images.githubusercontent.com/24875971/63896901-85130c80-c9c1-11e9-893f-7ea3b4bb4f55.png)

**Comment by adalca** [comment]
Sorry, I don't have an estimate for the pytorch code, we'll announce when we're close.  I hadn't realized the issues above were with your own code.

For our code, how long did you let it run? THe results in the last screenshot certainly look better than what you have above -- so am i to understand that the last screenshot is from our provided code, and in the earlier message it's from your own pytorch code?

**Comment by John1231983** [comment]
Right. Your code ran very fast. Just 20 mins to complete all and shown in the last screenshot. While my reporoduce is fist one. I found that the smooth loss may be wrong. In the beginning, my smooth loss is very high (~100), while your smooth loss is just 0.01. Do you have any trick for the smooth loss/flow loss?

**Comment by adalca** [comment]
I am confused -- if your tensor is 5 dimension, why wouldn't you be indexing in five dimensions? Perhaps it's something I don't know about pytorch.

In your screenshots, you're not showing a colobar -- you really should, this would tell you, for example, the min and max of the resulting deformation field (the "bad" one from your pytorch), which would help you understand a bit of what's going on. The smoothing loss (as you call it) is really just a spatial derivative, so there's no magic/trick there.

**Comment by John1231983** [comment]
@adalca : I would like to share your code result on OAIS dataset. From the result we can see that many wm and gm are merged together in the moved image. Do you suggest any reason? 

[Moving, Fixed | Moved Deformation Field]
![step9](https://user-images.githubusercontent.com/24875971/63944721-17f28c00-ca40-11e9-9d3c-1b4396f9bf77.png)

**Comment by adalca** [comment]
Can you please add colorbars? It's informative for the deformation fields.

I'm not sure what you mean by mixing GM and WM, but I suspect that it's due to the smooth warp and interpolation. 

Do you find dramatically different effects with other algorithms?

**Comment by John1231983** [comment]
Hi. Here is color bar

I used syn ants and its result is fine. Yes., mixing GM and WM means the GM in the moved image becomes WM (while ground-truth, it should be GM)

![sss](https://user-images.githubusercontent.com/24875971/63958647-bee32200-ca58-11e9-87ba-63c001d44234.png)

**Comment by adalca** [comment]
I'm sorry, I don't understand what you mean. Can you show me (perhaps use neuron.plot.slices in matlab):

12 | 13 | 12-moved-with-vm | 12-moved-with-ants

and then maybe highlight  (circle?) what you mean by the wm and gm mixing in voxelmorph and not in ants.

**Comment by adalca** [comment]
@John1231983 please see #109 for a discussion about a pytorch voxelmorph version.

**Comment by YuchuanQiao** [comment]
@John1231983 hi, I saw you plot the result of [Moving, Fixed | Moved Deformation Field], however, I am wondering how you obtain the deformation filed? right now I can only get warp from register.py, or get flow filed from some specific layers. Thank you.

**Comment by adalca** [comment]
@YuchuanQiao which network are you using? Most networks we build have two outputs: a warped subject and the deformation field.

**Comment by YuchuanQiao** [comment]
@adalca right now I am trying the Miccai2018 network and use the register.py, got [moved, warp] = net.predict([mov, fix]) from register.py.

**Comment by adalca** [comment]
in the miccai model, the second output is the velocity field mean and variance. If you take the `warp[0,:,:,:,:3]` this will be the velocity field. You can integrate this using the `VecInt` layer in `neuron` to get the displacement. We do this in `VxmDense` of https://github.com/voxelmorph/voxelmorph/blob/redesign/voxelmorph/tensorflow_backend/networks.py#L75-L84

```
pos_flow = ne.layers.VecInt(method='ss', name='flow-int', int_steps=int_steps)(pos_flow)
# resize to final resolution
pos_flow = layers.RescaleTransform(2, name='diffflow')(pos_flow)
```

**Comment by YuchuanQiao** [comment]
@adalca thank you. I will try this. One more thing, right now could i use a different image size for training except (160,192,224)?  I checked the code, it looks conv_block() function give a different result other than x = upsample_layer()(x), and then x = concatenate([x, x_enc[-2]]) raise an error. ValueError: A `Concatenate` layer requires inputs with matching shapes except for the concat axis. Got inputs shapes: [(None, 18, 22, 14, 32), (None, 18, 21, 14, 32)].
do you have any idea? thank you.

**Comment by adalca** [comment]
@YuchuanQiao Yes, you can train or test with other sizes, but each dimension size needs to be a multiple of 16, because of the UNet architecture.

**Comment by YuchuanQiao** [comment]
ok, I see, thank you.
