### ISSUE TITLE
Rigid align or affine align?

### ISSUE THREAD

**Issue by John1231983** [voxelmorph/voxelmorph#96]
Hi, I want to ask you about the pre-processing step. In the TMI paper (extention of cvpr 2018), you said that
> We also assume that f and m are affinely aligned as a preprocessing step, so that the only source of misalignment between the volumes is nonlinear

Does it mean "affinely aligned" or rigid aligned"?

I am asking it because the affine transform requires 12 dof (for 3D: rotation+translation+scaling), while the rigid align requires 6 dof [source: [flirt](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FLIRT/UserGuide)]

>Restrict the transformation type. For 3D to 3D mode the DOF can be set to 12 (affine), 9 (traditional), 7 (global rescale) or 6 (rigid body).

So, if we register a subject to the atlas by affine transform, normally the shape of the subject brain will be scaled to be similar to atlas brain. While the rigid transform will maintain the shape/size of brain subject.

The second question I want to ask is that, do you think the normalization range is importance? How about the other range such as [-1,1] or even zero mean and unit variance.

The third question is that interpolation method. For given a displacement field, it is clear that we should use nearness interpolation for making a warped label. However, for the moved image, do you think bilinear or nearness which one is better? In my testing, I found that the bilinear often smooth the intensity (also constant between tissues), while the nearness can ignore it but it has some artifact in the boundary (likes zigzag artifact)

Thanks

**Comment by adalca** [comment]
We used affine, however using rigid would likely work as well.

I think any range like [0, 1] or [-1, 1] will do fine, honestly.

Re: interpolation, it depends on your task, but yes, since you are interpolating either way you will have an issue, and the trade-off you mention is well recognized. It really depends on what you are using the registration for -- in reality, very often registration is used to obtain the deformation field itself, which is then analyzed -- rather than to actually warp images around.

**Comment by John1231983** [comment]
Thanks. So what kind of interpolation for an image (not label) do you prefer?

**Comment by adalca** [comment]
I linear interpolation for that.

**Comment by John1231983** [comment]
@adalca : For the first question, although both registration ways work, the results are different. For example, we want to calculate inner brain surface thickness, that input from segmentation result. So, if we used affine transform, the brain thickness will different with original brain thickness (in physical space) because it is rescaled. However, if we use a rigid alignment method, then the thickness still maintain because it does not scale the moved image. Do you agree with me?

**Comment by adalca** [comment]
I'm not sure what you mean by brain thickness, but yes certainly if you apply affine it will normalize  the brain, so the non-linear deformations will not capture this aspect anymore. I agree that these two will give you different results, so it depends on what your task is. I just meant that I expect voxelmorph to work in both cases.

**Comment by John1231983** [comment]
Brain thickness meant the inner/outter surface thickness of brain that obtain by wm/gm segmentation and surface reconstruction. For example, given a brain mri from one subject, we want to measure the thickness of wm surface. Then result called inner surface thickness.
